"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    - "type": "docx"
      "path": "CTR.docx"
    - "type": "xml"
      "path": "CTR.xml"
    - "type": "csv"
      "path": "CTR.csv"
    - "type": "json"
      "path": "CTR.json"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "ESRP_003"
    "requirements":
    - "name": "RQ_ESRP_022"
      "variations":
      - "SIP_INVITE_location_garbled_PIDF-LO_body.xml"
      - "SIP_INVITE_incorrect_geolocation_for_dereference.xml"
    - "name": "RQ_ESRP_023"
      "variations":
      - "SIP_INVITE_from_OSP.xml"
    - "name": "RQ_ESRP_024"
      "variations":
      - "SIP_INVITE_incorrect_geolocation_for_dereference.xml"
    - "name": "RQ_ESRP_025"
      "variations":
      - "SIP_INVITE_location_garbled_PIDF-LO_body.xml"
    - "name": "RQ_ESRP_026"
      "variations":
      - "SIP_INVITE_incorrect_geolocation_for_dereference.xml"
    "variations":
    - "name": "SIP_INVITE_from_OSP.xml"
      "mode": 'online'
      "pcap_file": '# Optional'
      "params":
        "messages":
        - "action": "receive"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ''
          "http_url": ''
          "body": ''
          "sipp_scenario":
            "scenario_file_path": "test_files/sipp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml"
            "kwargs": {}
            "save_response_as": "ESRP_003_var1_RECEIVE_response.log"
            "save_log_as": "ESRP_003_var1_RECEIVE.log"
          "save_response_as": 'True'
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ''
          "http_url": ''
          "body": ''
          "sipp_scenario":
            "scenario_file_path": "file.test_files/sipp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml"
            "kwargs": {}
            "save_response_as": "ESRP_003_var1_SEND_response.log"
            "save_log_as": "ESRP_003_var1_SEND.log"
          "save_response_as": 'False'
      "filtering_options":
      - "message_type": 'stimulus'
        "src_interface": 'IF_O-BCF_ESRP'
        "dst_interface": 'IF_ESRP_O-BCF'
        "sip_method": 'INVITE'
        "http_request_method": ''
        "response_status_code": '200'
        "header_contains": ''
        "body_contains": ''
      - "message_type": 'output'
        "src_interface": 'IF_ESRP_T-BCF'
        "dst_interface": 'IF_T-BCF_ESRP'
        "sip_method": 'INVITE'
        "http_request_method": ''
        "response_status_code": '200'
        "header_contains": ''
        "body_contains": ''
    - "name": "SIP_INVITE_location_garbled_PIDF-LO_body.xml"
      "mode": 'online'
      "pcap_file": '# Optional'
      "params":
        "messages":
        - "action": "receive"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ''
          "http_url": ''
          "body": ''
          "sipp_scenario":
            "scenario_file_path": "file.test_files/sipp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml"
            "kwargs": {}
            "save_response_as": "ESRP_003_var2_RECEIVE_response.log"
            "save_log_as": "ESRP_003_var2_RECEIVE.log"
          "save_response_as": 'True'
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ''
          "http_url": ''
          "body": ''
          "sipp_scenario":
            "scenario_file_path": "file.test_files/sipp_scenarios/SIP_INVITE/SIP_INVITE_location_garbled_PIDF-LO_body.xml"
            "kwargs": {}
            "save_response_as": "ESRP_003_var2_SEND_response.log"
            "save_log_as": "ESRP_003_var2_SEND.log"
          "save_response_as": 'False'
      "filtering_options":
      - "message_type": 'stimulus'
        "src_interface": 'IF_O-BCF_ESRP'
        "dst_interface": 'IF_ESRP_O-BCF'
        "sip_method": 'INVITE'
        "http_request_method": ''
        "response_status_code": '200'
        "header_contains": ''
        "body_contains": ''
      - "message_type": 'output'
        "src_interface": 'IF_ESRP_T-BCF'
        "dst_interface": 'IF_T-BCF_ESRP'
        "sip_method": 'INVITE'
        "http_request_method": ''
        "response_status_code": '200'
        "header_contains": ''
        "body_contains": ''
    - "name": "SIP_INVITE_incorrect_geolocation_for_dereference.xml"
      "mode": 'online'
      "pcap_file": '# Optional'
      "params":
        "messages":
        - "action": "receive"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ''
          "http_url": ''
          "body": ''
          "sipp_scenario":
            "scenario_file_path": "file.test_files/sipp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml"
            "kwargs": {}
            "save_response_as": "ESRP_003_var3_RECEIVE_response.log"
            "save_log_as": "ESRP_003_var3_RECEIVE.log"
          "save_response_as": 'True'
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ''
          "http_url": ''
          "body": ''
          "sipp_scenario":
            "scenario_file_path": "file.test_files/sipp_scenarios/SIP_INVITE/SIP_INVITE_incorrect_geolocation_for_dereference.xml"
            "kwargs": {}
            "save_response_as": "ESRP_003_var3_SEND_response.log"
            "save_log_as": "ESRP_003_var3_SEND.log"
          "save_response_as": 'False'
      "filtering_options":
      - "message_type": 'stimulus'
        "src_interface": 'IF_O-BCF_ESRP'
        "dst_interface": 'IF_ESRP_O-BCF'
        "sip_method": 'INVITE'
        "http_request_method": ''
        "response_status_code": '200'
        "header_contains": ''
        "body_contains": ''
      - "message_type": 'output'
        "src_interface": 'IF_ESRP_T-BCF'
        "dst_interface": 'IF_T-BCF_ESRP'
        "sip_method": 'INVITE'
        "http_request_method": ''
        "response_status_code": '200'
        "header_contains": ''
        "body_contains": ''