REQUIREMENTS_SCHEMA = {
    "RQ_CHE_3": {
        "requirement_text": "Callback and other non-emergency outbound call INVITE messages MUST comply with the SIP "
                            "call interface as defined in Section 3.1, and constructed using the guidance provided in "
                            "section 4.20 (OCIF), with the following clarifications.",
        "document_section": "4.6.1",
        "description": "Callback and non-emergency outbound calls must follow the SIP call interface rules. These "
                       "calls must be constructed using guidance from Section 3.1 and 4.20.",
        "test_id": "CHE_004",
        "subtests": []
    },
    "RQ_CHE_4": {
        "requirement_text": "The To header field value of the callback INVITE message MUST be set to a value that will"
                            "allow reaching the home network of the target.",
        "document_section": "4.6.1",
        "description": "The To header in callback INVITE messages must point to the target's home network. This ensures "
                       "that the call is directed to the correct network.",
        "test_id": "CHE_004",
        "subtests": []
    },
    "RQ_CHE_5": {
        "requirement_text": "If the To header field value is a sip URI, the domain SHALL be the one of the home network"
                            "of the target.",
        "document_section": "4.6.1",
        "description": "If the To header contains a SIP URI, it must use the home network domain of the target. This "
                       "ensures correct routing of the call.",
        "test_id": "CHE_004",
        "subtests": []
    },
    "RQ_CHE_6": {
        "requirement_text": "All i3 PSAPs MUST support all media, voice, video, and text.",
        "document_section": "4.6.2",
        "description": "All i3 PSAPs must support media types including voice, video, and text. This ensures compatibility "
                       "with all communication modes.",
        "test_id": "CHE_002",
        "subtests": []
    },
    "RQ_CHE_8": {
        "requirement_text": "SDP offers and answers generated by the PSAP MUST include appropriate language tags.",
        "document_section": "4.6.2",
        "description": "PSAPs must include language tags in SDP offers and answers. This ensures that media is offered "
                       "in the correct language.",
        "test_id": "CHE_003",
        "subtests": []
    },
    "RQ_CHE_9": {
        "requirement_text": "Answers to offers that included language tags MUST include language tags.",
        "document_section": "4.6.2",
        "description": "Any answers to offers containing language tags must also include the same tags. This maintains "
                       "language consistency in the communication.",
        "test_id": "CHE_003",
        "subtests": []
    },
    "RQ_CHE_10": {
        "requirement_text": "The PSAP MUST implement a LoST client interface as defined in Section 3.4.",
        "document_section": "4.6.3",
        "description": "PSAPs must implement a LoST client interface. This interface is crucial for location-based "
                       "routing as outlined in Section 3.4.",
        "test_id": "",
        "subtests": []
    },
    "RQ_CHE_11": {
        "requirement_text": "The PSAP MUST implement both SIP Presence Event Package and HELD dereferencing interfaces "
                            "to any LIS function as described in Section 4.10.",
        "document_section": "4.6.4",
        "description": "PSAPs must implement SIP Presence Event Package and HELD dereferencing interfaces. This is "
                       "required for LIS interaction as described in Section 4.10.",
        "test_id": "CHE_001",
        "subtests": []
    },
    "RQ_CHE_13": {
        "requirement_text": "The PSAP MUST use TCP with TLS for the LIS dereferencing interface, with fallback to TCP "
                            "(without TLS) on failure to establish a TLS connection when TLS is used.",
        "document_section": "4.6.4",
        "description": "PSAPs must use TCP with TLS for the LIS dereferencing interface. If TLS fails, fallback to "
                       "TCP without TLS should be allowed.",
        "test_id": "",
        "subtests": []
    },
    "RQ_CHE_29": {
        "requirement_text": "The PSAP MUST deploy a dereference (HTTPS GET) interface for additional data as described "
                            "in Section 7, as well as the IS ADR identity query mechanism.",
        "document_section": "4.6.15",
        "description": "PSAPs must deploy a dereference interface for additional data. The IS ADR identity query "
                       "mechanism must also be implemented.",
        "test_id": "",
        "subtests": []
    },
    "RQ_CHE_32": {
        "requirement_text": "PSAPs MUST support the test call interface as described in Section 9...",
        "document_section": "4.6.17",
        "description": "PSAPs must support a test call interface, which is outlined in Section 9.",
        "test_id": "CHE_005",
        "subtests": []
    },
    "RQ_CHE_33": {
        "requirement_text": "PSAPs MUST support test of all media – voice, video, and text.",
        "document_section": "4.6.17",
        "description": "PSAPs must support testing of all media types including voice, video, and text. This ensures "
                       "compatibility with all forms of communication.",
        "test_id": "CHE_005",
        "subtests": []
    },
    "RQ_CHE_34": {
        "requirement_text": "These test calls MUST originate from within the ESInet and MUST come from an entity with "
                            "credentials traceable to the PCA and trusted by the ESRP.",
        "document_section": "4.6.18",
        "description": "Test calls must originate from within the ESInet and come from a trusted entity with credentials "
                       "traceable to the PCA and ESRP.",
        "test_id": "",
        "subtests": []
    },
    "RQ_CHE_35": {
        "requirement_text": "The credentials used by the server MUST be traceable to the PCA and MUST occur in the ESRP"
                            "policy.",
        "document_section": "4.6.18",
        "description": "The server credentials must be traceable to the PCA and must be part of the ESRP policy. "
                       "This ensures accountability and trust.",
        "test_id": "",
        "subtests": []
    }
}
