REQUIREMENTS_SCHEMA = {
    "INTEROP_2.4_TMS_2": {
        "requirement_text": "The ESInet BCF receives the INVITE",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESInet BCF receives the INVITE",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_4": {
        "requirement_text": "The ESInet BCF sends a 100 Trying provisional response to the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESInet BCF sends a 100 Trying provisional response to the OSP",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_6": {
        "requirement_text": "The OSP receives the 100 Trying provisional response sent by the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The OSP receives the 100 Trying provisional response sent by the BCF",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_7": {
        "requirement_text": 'The BCF scrubs the INVITE to remove inappropriate Resource-Priority and "verstat" values',
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": 'The BCF scrubs the INVITE to remove inappropriate Resource-Priority and "verstat" values',
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_8": {
        "requirement_text": "The BCF sends the INVITE to an ESRP (Originating ESRP)",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF sends the INVITE to an ESRP (Originating ESRP)",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_10": {
        "requirement_text": "The ESRP receives the INVITE from the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP receives the INVITE from the BCF",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_12": {
        "requirement_text": "The ESRP sends a 100 Trying provisional response to the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP sends a 100 Trying provisional response to the BCF",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_14": {
        "requirement_text": "The BCF receives the 100 Trying provisional response from the ESRP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF receives the 100 Trying provisional response from the ESRP",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_53": {
        "requirement_text": "The ESRP sends the call to the SIP URI specified in the RouteAction. (PoC: should be sent to the CHFE, ESRP has RouteAction manually preconfigured)",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP sends the call to the SIP URI specified in the RouteAction. (PoC: should be sent to the CHFE, ESRP has RouteAction manually preconfigured)",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_69": {
        "requirement_text": "The PSAP's CHFE may send a 180 Ringing or other non-100 provisional response to the ESRP or BCF that sent it the INVITE. If so: The ESRP receives this provisional response. The ESRP sends that response to the BCF. BCF received this provisional response. The BCF sends that response to the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The PSAP's CHFE may send a 180 Ringing or other non-100 provisional response to the ESRP or BCF that sent it the INVITE. If so: The ESRP receives this provisional response. The ESRP sends that response to the BCF. BCF received this provisional response. The BCF sends that response to the OSP",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_70": {
        "requirement_text": "The PSAP's CHFE sends a 200 OK final response to the ESRP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The PSAP's CHFE sends a 200 OK final response to the ESRP",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_72": {
        "requirement_text": "The ESRP receives the 200 OK final response",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP receives the 200 OK final response",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_74": {
        "requirement_text": "The ESRP sends the 200 OK to the BCF from which it received the INVITE",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP sends the 200 OK to the BCF from which it received the INVITE",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_75": {
        "requirement_text": "The BCF sends 200 OK to the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF sends 200 OK to the OSP",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_76": {
        "requirement_text": "The OSP receives the 200 OK sent by the Originating BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The OSP receives the 200 OK sent by the Originating BCF",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_77": {
        "requirement_text": "The OSP sends an ACK to the Originating BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The OSP sends an ACK to the Originating BCF",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_78": {
        "requirement_text": "The BCF receives the ACK sent by the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF receives the ACK sent by the OSP",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_80": {
        "requirement_text": "The BCF sends the ACK to the Originating ESRP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF sends the ACK to the Originating ESRP",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_81": {
        "requirement_text": "The Originating ESRP receives the ACK from the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The Originating ESRP receives the ACK from the BCF",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_84": {
        "requirement_text": "That ESRP sends the ACK to the CHFE",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "That ESRP sends the ACK to the CHFE",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_TMS_89": {
        "requirement_text": "The call taker answers the call; interactive media is established between caller and call taker OSP<->CHFE (media is anchored at each call-anchoring point - BCF)",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The call taker answers the call; interactive media is established between caller and call taker OSP<->CHFE (media is anchored at each call-anchoring point - BCF)",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_CTES_1": {
        "requirement_text": "Verify that at each step in the Test Message Sequence the input and output messages contain correct content",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "Verify that at each step in the Test Message Sequence the input and output messages contain correct content",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_IETES_6": {
        "requirement_text": "Originating BCFs anchor media (the RTP media goes through the BCF)",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "Originating BCFs anchor media (the RTP media goes through the BCF)",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_IETES_7": {
        "requirement_text": "media stream(s) successfully established between OSP and Originating BCF",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "media stream(s) successfully established between OSP and Originating BCF",
        "test_id": "",
        "subtests": [],
    },
    "INTEROP_2.4_IETES_8": {
        "requirement_text": "media stream(s) successfully established between PSAP CHFE and OSP",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "media stream(s) successfully established between PSAP CHFE and OSP",
        "test_id": "",
        "subtests": [],
    },
}
