REQUIREMENTS_SCHEMA = {
    "RQ_INTEROP_2": {
        "requirement_text": "The ESInet BCF receives the INVITE",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESInet BCF receives the INVITE",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF receives the INVITE from OSP",
        ],
    },
    "RQ_INTEROP_4": {
        "requirement_text": "The ESInet BCF sends a 100 Trying provisional response to the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESInet BCF sends a 100 Trying provisional response to the OSP",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends 100 Trying to OSP",
        ],
    },
    "RQ_INTEROP_6": {
        "requirement_text": "The OSP receives the 100 Trying provisional response sent by the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The OSP receives the 100 Trying provisional response sent by the BCF",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends 100 Trying to OSP",
        ],
    },
    "RQ_INTEROP_7": {
        "requirement_text": 'The BCF scrubs the INVITE to remove inappropriate Resource-Priority and "verstat" values',
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": 'The BCF scrubs the INVITE to remove inappropriate Resource-Priority and "verstat" values',
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF INVITE: 'Resource-Priority' header values preserved",
            "BCF INVITE: 'From' header values preserved",
        ],
    },
    "RQ_INTEROP_8": {
        "requirement_text": "The BCF sends the INVITE to an ESRP (Originating ESRP)",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF sends the INVITE to an ESRP (Originating ESRP)",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends INVITE to ESRP",
        ],
    },
    "RQ_INTEROP_10": {
        "requirement_text": "The ESRP receives the INVITE from the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP receives the INVITE from the BCF",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends INVITE to ESRP",
        ],
    },
    "RQ_INTEROP_12": {
        "requirement_text": "The ESRP sends a 100 Trying provisional response to the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP sends a 100 Trying provisional response to the BCF",
        "test_id": "INTEROP_001",
        "subtests": [
            "ESRP sends 100 Trying to BCF",
        ],
    },
    "RQ_INTEROP_14": {
        "requirement_text": "The BCF receives the 100 Trying provisional response from the ESRP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF receives the 100 Trying provisional response from the ESRP",
        "test_id": "INTEROP_001",
        "subtests": [
            "ESRP sends 100 Trying to BCF",
        ],
    },
    "RQ_INTEROP_53": {
        "requirement_text": "The ESRP sends the call to the SIP URI specified in the RouteAction. (PoC: should be sent to the CHFE, ESRP has RouteAction manually preconfigured)",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP sends the call to the SIP URI specified in the RouteAction. (PoC: should be sent to the CHFE, ESRP has RouteAction manually preconfigured)",
        "test_id": "INTEROP_001",
        "subtests": [
            "ESRP send SIP INVITE to CHFE",
        ],
    },
    "RQ_INTEROP_54": {
        "requirement_text": "The PSAP's CHFE may send a 180 Ringing or other non-100 provisional response to the ESRP that sent it the INVITE. If so: The ESRP receives this provisional response + The ESRP sends that response to the BCF.",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The PSAP's CHFE may send a 180 Ringing or other non-100 provisional response to the ESRP that sent it the INVITE. If so: The ESRP receives this provisional response + The ESRP sends that response to the BCF.",
        "test_id": "INTEROP_001",
        "subtests": [
            "ESRP sends 180 Ringing to BCF",
        ],
    },
    "RQ_INTEROP_55": {
        "requirement_text": "The PSAP's CHFE may send a 180 Ringing or other non-100 provisional response to the BCF that sent it the INVITE. If so: BCF receives this provisional response + The BCF sends that response to the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The PSAP's CHFE may send a 180 Ringing or other non-100 provisional response to the BCF that sent it the INVITE. If so: BCF receives this provisional response + The BCF sends that response to the OSP",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends 180 Ringing to OSP",
        ],
    },
    "RQ_INTEROP_70": {
        "requirement_text": "The PSAP's CHFE sends a 200 OK final response to the ESRP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The PSAP's CHFE sends a 200 OK final response to the ESRP",
        "test_id": "INTEROP_001",
        "subtests": [
            "CHFE sends 200 OK to ESRP",
        ],
    },
    "RQ_INTEROP_72": {
        "requirement_text": "The ESRP receives the 200 OK final response",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP receives the 200 OK final response",
        "test_id": "INTEROP_001",
        "subtests": [
            "CHFE sends 200 OK to ESRP",
        ],
    },
    "RQ_INTEROP_74": {
        "requirement_text": "The ESRP sends the 200 OK to the BCF from which it received the INVITE",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The ESRP sends the 200 OK to the BCF from which it received the INVITE",
        "test_id": "INTEROP_001",
        "subtests": [
            "ESRP sends 200 OK to BCF",
        ],
    },
    "RQ_INTEROP_75": {
        "requirement_text": "The BCF sends 200 OK to the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF sends 200 OK to the OSP",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends 200 OK to OSP",
        ],
    },
    "RQ_INTEROP_76": {
        "requirement_text": "The OSP receives the 200 OK sent by the Originating BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The OSP receives the 200 OK sent by the Originating BCF",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends 200 OK to OSP",
        ],
    },
    "RQ_INTEROP_77": {
        "requirement_text": "The OSP sends an ACK to the Originating BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The OSP sends an ACK to the Originating BCF",
        "test_id": "INTEROP_001",
        "subtests": ["OSP sends ACK to BCF"],
    },
    "RQ_INTEROP_78": {
        "requirement_text": "The BCF receives the ACK sent by the OSP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF receives the ACK sent by the OSP",
        "test_id": "INTEROP_001",
        "subtests": ["OSP sends ACK to BCF"],
    },
    "RQ_INTEROP_80": {
        "requirement_text": "The BCF sends the ACK to the Originating ESRP",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The BCF sends the ACK to the Originating ESRP",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends ACK to ESRP",
        ],
    },
    "RQ_INTEROP_81": {
        "requirement_text": "The Originating ESRP receives the ACK from the BCF",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The Originating ESRP receives the ACK from the BCF",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF sends ACK to ESRP",
        ],
    },
    "RQ_INTEROP_84": {
        "requirement_text": "That ESRP sends the ACK to the CHFE",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "That ESRP sends the ACK to the CHFE",
        "test_id": "INTEROP_001",
        "subtests": [
            "ESRP sends ACK to CHFE",
        ],
    },
    "RQ_INTEROP_89": {
        "requirement_text": "The call taker answers the call; interactive media is established between caller and call taker OSP<->CHFE (media is anchored at each call-anchoring point - BCF)",
        "document_section": "Interop Criteria for Use Cases - section 2.4",
        "description": "The call taker answers the call; interactive media is established between caller and call taker OSP<->CHFE (media is anchored at each call-anchoring point - BCF)",
        "test_id": "INTEROP_001",
        "subtests": [
            "Media stream established between OSP and BCF",
            "Media stream established between BCF and CHFE",
        ],
    },
    "RQ_INTEROP_100": {
        "requirement_text": "Verify that at each step in the Test Message Sequence the input and output messages contain correct content",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "Verify that at each step in the Test Message Sequence the input and output messages contain correct content",
        "test_id": "INTEROP_001",
        "subtests": [
            "BCF INVITE: Route header added on top",
            "BCF INVITE: Via header added on top",
            "BCF INVITE: Record-Route header added on top",
            "BCF INVITE: out messages headers preserved",
            "BCF INVITE: 'To' header values preserved",
            "BCF INVITE: 'From' header values preserved",
            "BCF INVITE: 'Request URI' header values preserved",
            "BCF INVITE: 'Resource-Priority' header values preserved",
            "BCF INVITE: out messages body preserved except SDP",
            "BCF INVITE: To header set to urn:service:sos",
            "BCF INVITE: Request-URI set to urn:service:sos",
            "BCF INVITE: Call-Info contains Emergency Call Identifier (CallId)",
            "BCF INVITE: Emergency Call Identifier URN",
            "BCF INVITE: Emergency Call Identifier String ID",
            "BCF INVITE: Emergency Call Identifier FQDN",
            "BCF INVITE: Call-Info contains Incident Tracking Identifier (IncidentId)",
            "BCF INVITE: Incident Tracking Identifier String ID",
            "BCF INVITE: Incident Tracking Identifier FQDN",
            "BCF INVITE: Call-Info contains emergency-source",
            "BCF INVITE: Resource-Priority is esnet value",
            "BCF INVITE: 'Call-Info' was added with value pattern ALPHANUMERIC_UNIQUE_ID@BCF_FQDN with parameter purpose=emergency-source",
            "BCF INVITE: 'Contact' header field must be changed to SIP URI with the BCF FQDN/IP",
            "BCF INVITE: SDP message body must be changed to anchor media",
            "BCF INVITE: Geolocation present",
            "BCF BYE: Route header added on top",
            "BCF BYE: Via header added on top",
            "BCF BYE: Record-Route header added on top",
            "BCF BYE: out messages headers preserved",
            "BCF BYE: 'To' header values preserved",
            "BCF BYE: 'From' header values preserved",
            "BCF BYE: 'Request URI' header values preserved",
            "BCF BYE: 'Resource-Priority' header values preserved",
            "ESRP INVITE: Route header added on top",
            "ESRP INVITE: Via header added on top",
            "ESRP INVITE: Record-Route header added on top",
            "ESRP INVITE: Non-variable headers preserved",
            "ESRP INVITE: To header remains urn:service:sos",
            "ESRP INVITE: 'To' header values preserved",
            "ESRP INVITE: 'Request URI' header values preserved",
            "ESRP INVITE: 'Resource-Priority' header values preserved",
            "ESRP INVITE: Request-URI remains urn:service:sos",
            "ESRP INVITE: Emergency Call Identifier (CallId) preserved from BCF",
            "ESRP INVITE: Emergency Call Identifier URN",
            "ESRP INVITE: Emergency Call Identifier String ID",
            "ESRP INVITE: Emergency Call Identifier FQDN",
            "ESRP INVITE: Incident Tracking Identifier (IncidentId) preserved from BCF",
            "ESRP INVITE: Geolocation present",
            "ESRP BYE: Route header added on top",
            "ESRP BYE: Via header added on top",
            "ESRP BYE: Record-Route header added on top",
            "ESRP BYE: Non-variable headers preserved",
            "ESRP BYE: 'To' header values preserved",
            "ESRP BYE: 'Request URI' header values preserved",
            "ESRP BYE: 'Resource-Priority' header values preserved",
        ],
    },
    "RQ_INTEROP_600": {
        "requirement_text": "Originating BCFs anchor media (the RTP media goes through the BCF)",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "Originating BCFs anchor media (the RTP media goes through the BCF)",
        "test_id": "INTEROP_001",
        "subtests": [
            "Media stream established between OSP and BCF",
            "Media stream established between BCF and CHFE",
        ],
    },
    "RQ_INTEROP_700": {
        "requirement_text": "media stream(s) successfully established between OSP and Originating BCF",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "media stream(s) successfully established between OSP and Originating BCF",
        "test_id": "INTEROP_001",
        "subtests": [
            "Media stream established between OSP and BCF",
        ],
    },
    "RQ_INTEROP_800": {
        "requirement_text": "media stream(s) successfully established between PSAP CHFE and OSP",
        "document_section": "Interop Criteria for Use Cases 2.4",
        "description": "media stream(s) successfully established between PSAP CHFE and OSP",
        "test_id": "INTEROP_001",
        "subtests": ["Media stream established between BCF and CHFE"],
    },
}
