REQUIREMENTS_SCHEMA = {
    "RQ_ECRF-LVF_001": {
        "requirement_text": "The NENA NG9-1-1 solution MUST properly route incoming IP packet-based emergency calls to the appropriate or designated PSAP, as well as support the dispatch of responders to the right location",
        "document_section": "4.3",
        "description": "The NENA NG9-1-1 solution must correctly route incoming IP emergency calls to the appropriate PSAP and support dispatching responders to the correct location.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_002": {
        "requirement_text": "The location information used, when provided in civic form, MUST be proved sufficient for routing and dispatch prior to the call being placed.",
        "document_section": "4.3",
        "description": "Civic location information must be verified as sufficient for routing and dispatch purposes before the emergency call is placed.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_003": {
        "requirement_text": "LVFs MUST support draft-ecrit-lost-planned-changes [178] allowing a LIS to be notified of planned changes in GIS data and for it to pre-validate a location against this new GIS data before it becomes live.",
        "document_section": "4.3",
        "description": "LVFs must support LoST planned-changes (draft-ecrit-lost-planned-changes) so a LIS can pre-validate a location against future GIS data before the data goes live.",
        "test_id": "ECRF_LVF_006",
        "subtests": [],
    },
    "RQ_ECRF-LVF_004": {
        "requirement_text": "As specified in Section 3.4.2, the LVF MUST support the validation of location around planned changes as defined by draft-ecrit-lost-planned-changes [178].",
        "document_section": "4.3",
        "description": "The LVF must support the validation of location information based on planned GIS data changes, as defined by draft-ecrit-lost-planned-changes (Section 3.4.2).",
        "test_id": "ECRF_LVF_006",
        "subtests": [],
    },
    "RQ_ECRF-LVF_005": {
        "requirement_text": "An ECRF or LVF provided by a 9-1-1 Authority and accessible from outside the ESInet MUST permit querying by an IP client/endpoint, an IP routing proxy, a Legacy Network Gateway, and any other entity outside the ESInet.",
        "document_section": "4.3",
        "description": "An ECRF or LVF provided by a 9-1-1 Authority and reachable from outside the ESInet must allow queries from any external entity, including IP clients, proxies, and Legacy Network Gateways.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_006": {
        "requirement_text": "An ECRF or LVF accessible inside an ESInet MUST permit querying from any entity inside the ESInet.",
        "document_section": "4.3",
        "description": "An ECRF or LVF that is reachable from inside the ESInet must allow queries from any internal ESInet entity.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_008": {
        "requirement_text": "Authentication MUST apply to all entities that initiate queries to the ECRF within the ESInet.",
        "document_section": "4.3.2.1",
        "description": "All entities originating queries to the ECRF from within the ESInet must be subject to authentication.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_009": {
        "requirement_text": "TLS is used by all ECRFs and LVFs within the ESInet, and credentials issued to the querying entity that are traceable to the PCA MUST be accepted.",
        "document_section": "4.3.2.1",
        "description": "All ECRFs and LVFs within the ESInet must use  TLS . They must accept credentials provided by the querying entity that are traceable back to the Policy Certification Authority ( PCA ).",
        "test_id": "ECRF_LVF_001",
        "subtests": [],
    },
    "RQ_ECRF-LVF_011": {
        "requirement_text": "If the proffered location is not specified as a point (i.e., the location in the query is a shape) and the shape intersects more than one service boundary with a given service URN, the ECRF response SHALL be the URI of the service boundary with the greatest area of overlap (with a tie-breaking policy for the case of equal area of overlap).",
        "document_section": "4.3.2.1",
        "description": "If a non-point shape location overlaps multiple service boundaries for the same URN, the ECRF must return the URI of the boundary with the largest area of overlap, and use a tie-breaker policy if the overlap areas are equal.",
        "test_id": "ECRF_LVF_003",
        "subtests": [],
    },
    "RQ_ECRF-LVF_012": {
        "requirement_text": "If more than one service boundary for the same service URN at a given location exists in the ECRF, multiple <mapping> elements will be returned. The querier (e.g., a PSAP), MUST have local policy to determine how to handle the call.",
        "document_section": "4.3.2.1",
        "description": "If the ECRF finds multiple service boundaries for the same URN and location, it will return multiple `<mapping>` elements, and the querying entity (e.g., PSAP) must use local policy to decide how to proceed with the call.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_013": {
        "requirement_text": "In some cases, the ECRF can use the identity of the querier, or a distinguished Service URN to return the URI of the correct agency. This condition only occurs for queries to an ECRF from within an ESInet. External queries will only return one (PSAP) URI.",
        "document_section": "4.3.2.1",
        "description": "For queries originating inside an ESInet, the ECRF can use the querier's identity or a specific Service URN to return the correct agency URI; external queries are limited to returning only one PSAP URI.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_014": {
        "requirement_text": 'All LoST server implementations, deployed as an LVF, MUST support the inclusion of location validation information in the "findServiceResponse" message.',
        "document_section": "4.3.2.2",
        "description": "All LoST servers functioning as an LVF must support including location validation information within the `findServiceResponse` message.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_015": {
        "requirement_text": "As specified in Section 3.4.2, the LVF MUST support the validation of location around planned changes as defined by draft-ecrit-lost-planned-changes [178].",
        "document_section": "4.3.2.2",
        "description": "The LVF must support the validation of location information based on planned GIS data changes, as defined by draft-ecrit-lost-planned-changes (Section 3.4.2).",
        "test_id": "ECRF_LVF_006",
        "subtests": [],
    },
    "RQ_ECRF-LVF_016": {
        "requirement_text": "The ECRF/LVF MUST implement an NTP client interface for time of day information.",
        "document_section": "4.3.2.4",
        "description": "The ECRF/LVF is required to implement an  NTP  (Network Time Protocol) client interface for accurate time of day synchronization.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_017": {
        "requirement_text": "The ECRF/LVF MUST be capable of generating LogEvents per Section 4.12.",
        "document_section": "4.3.2.5",
        "description": "The ECRF/LVF must be capable of generating the required  LogEvents , as described in Section 4.12.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_018": {
        "requirement_text": "The ECRF/LVF MUST be capable of logging every incoming routing/validation request along with every recursive request and all response messages.",
        "document_section": "4.3.2.5",
        "description": "The ECRF/LVF must log all incoming routing/validation requests, every recursive request, and all corresponding response messages.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_019": {
        "requirement_text": "In addition, the ECRF/LVF MUST log all provisioning and synchronization messages and actions. Specific LogEvent records for these are provided in Section 4.12.3.",
        "document_section": "4.3.2.5",
        "description": "The ECRF/LVF must log all provisioning and synchronization messages and actions; specific LogEvent records for these are defined in Section 4.12.3.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_020": {
        "requirement_text": "Each ECRF and each LVF MUST implement the server-side of the ElementState event notification package. The ECRF/LVF MUST promptly report changes in its state to its subscribed elements. Any change in state that affects its ability to route (ECRF) or validate (LVF) MUST be reported.",
        "document_section": "4.3.2.6",
        "description": "Each ECRF and LVF must implement the server-side of the  ElementState  notification package. They must promptly report any state changes that affect their ability to route (ECRF) or validate (LVF) locations to subscribed elements.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_021": {
        "requirement_text": "The set of ECRF and LVF FEs within an ESInet MUST implement the server side of the ServiceState event notification package for the ECRF and the LVF service.",
        "document_section": "4.3.2.7",
        "description": "The collective set of ECRF and LVF Functional Elements ( FEs ) within an ESInet must implement the server-side of the  ServiceState  event notification package for both the ECRF and LVF services.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_022": {
        "requirement_text": "The ECRF MUST be able to provide routing information based on location information represented by a civic address. To do so, it is expected that the ECRF will represent the geographic service boundary in a manner that allows the association of a given address with the service boundary within which it is located.",
        "document_section": "4.3.3.1",
        "description": "The ECRF must be able to route calls based on a  civic address . It is expected to associate the address with the correct geographic service boundary for routing.",
        "test_id": "ECRF_LVF_002",
        "subtests": [],
    },
    "RQ_ECRF-LVF_023": {
        "requirement_text": "..if the provisioning data changes, the ECRF MUST respond immediately to the change, which may invalidate (for at least some time) the precalculated tabular data.",
        "document_section": "4.3.3.1",
        "description": "If the provisioning data changes, the ECRF must respond immediately to the update, even if the change temporarily invalidates its precalculated tabular data.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_024": {
        "requirement_text": "ECRFs MUST accept location information conforming to U.S. addressing standards defined/ in CLDXF [77] and its eventual Canadian equivalents.",
        "document_section": "4.3.3.1",
        "description": "ECRFs are required to accept location information that conforms to U.S. addressing standards (CLDXF [77]) and any future Canadian equivalents.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_025": {
        "requirement_text": "Unless the ECRF/LVF is provisioned to return different responses to different credentials of the querier, all queries with the same URN and location SHALL return the same response.",
        "document_section": "4.3.3.2",
        "description": "If not explicitly configured otherwise, the ECRF/LVF must return the same response for all queries that use the identical URN and location.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_026": {
        "requirement_text": 'The ECRF response SHALL be the service boundary with the greatest area of overlap. The ECRF will return multiple <mapping> elements in a response if the query has multiple matches (e.g., a query within an ESInet for "emergency:service:responder:police" with a location within the jurisdiction of campus, city, county, and state police agencies)',
        "document_section": "4.3.3.3",
        "description": "The ECRF must return the service boundary with the greatest area of overlap. It will return multiple `<mapping>` elements if the location matches multiple service boundaries for the same query (e.g., in a campus police scenario).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_027": {
        "requirement_text": "When dereferenced by a client using PCA-traceable credentials, URIs returned for the Additional Data service MUST resolve to Additional Data blocks registered in the IANA Emergency Call Additional Data registry [179].",
        "document_section": "4.3.3.4",
        "description": "URIs returned by the Additional Data service must resolve to valid Additional Data blocks registered in the  IANA Emergency Call Additional Data registry  [179] when dereferenced by a client using PCA-traceable credentials.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_028": {
        "requirement_text": "When provisioning data for an ECRF and LVF through the SI, a 9-1-1 Authority (or 9-1-1 Authority designee) MUST only include GIS data for their geographic area of responsibility and MUST ensure the data includes coverage for the entire extent of that area.",
        "document_section": "4.3.4",
        "description": "When provisioning ECRF/LVF data via the SI, a 9-1-1 Authority must only use GIS data for its area of responsibility and must ensure this data fully covers that entire geographic area.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_029": {
        "requirement_text": "The ECRF/LVF MUST have a provisionable threshold parameter that indicates the maximum gap/overlap that is ignored by it. This threshold is expressed in square meters. Gaps or overlaps that are smaller than this parameter MUST be handled by the ECRF/LVF using an algorithm of its choice. For example, it may split the gap/overlap roughly in half and consider the halves as belonging to one of the constituent sources.",
        "document_section": "4.3.4",
        "description": "The ECRF/LVF must have a configurable threshold, in square meters, for the maximum gap or overlap it ignores. Gaps or overlaps smaller than this threshold must be resolved by the ECRF/LVF using an internal algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_030": {
        "requirement_text": "The ECRF/LVF MUST report gaps and overlaps larger than the provisioned threshold. To do so, it makes use of the GapOverlap event.",
        "document_section": "4.3.4",
        "description": "The ECRF/LVF must use the  GapOverlap  event to report any gaps or overlaps in service boundaries that exceed the configured threshold.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_031": {
        "requirement_text": "All 9-1-1 Authorities which provide source GIS data to an ECRF/LVF MUST subscribe to its GapOverlap event.",
        "document_section": "4.3.4",
        "description": "All 9-1-1 Authorities that supply source GIS data to an ECRF/LVF are required to subscribe to its  GapOverlap  event notifications.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_032": {
        "requirement_text": "The response of the agencies MUST be to provide updates to the data that address the gap/overlap.",
        "document_section": "4.3.4",
        "description": "Agencies must respond to gap/overlap reports by providing updated GIS data that resolves the identified inconsistencies.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_033": {
        "requirement_text": "During the period when the gap/overlap exists, notifications have been issued, and queries arrive (which could be at call time) with a location in the gap/overlap, the ECRF/LVF MUST resolve the query using an algorithm of its choice. For example, it may split the gap/overlap roughly in half and consider the halves as belonging to one of the constituent sources.",
        "document_section": "4.3.4",
        "description": "While a reported gap/overlap exists, and until it is fixed, the ECRF/LVF must use an internal algorithm to resolve queries with locations in that area (e.g., splitting the area between the constituent sources).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_034": {
        "requirement_text": "A service may have areas within the service area of the ECRF for which there is no responder. For example, the mountain rescue service is not available in flat terrain. Also, there are still some areas where 9-1-1 service is not available. In such cases, a service boundary MUST exist in the ECRF with the Service URI field set to urn:emergency:servicenotimplemented. The ECRF MUST return the <serviceNotImplemented> error if asked to provide a route for a location within that areas.",
        "document_section": "4.3.4",
        "description": "For areas with no available responder (e.g., no 9-1-1 service), the ECRF must define a service boundary with a  'urn:emergency:servicenotimplemented ' URI and return a `<serviceNotImplemented>` error for location queries within that area.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_035": {
        "requirement_text": "Any ECRF that is authoritative for a top level URN MUST also be authoritative for all lower level URNs for the same coverage regions.",
        "document_section": "4.3.6",
        "description": "An ECRF that is authoritative for a top-level URN must also be authoritative for all lower-level (sub-service) URNs within the same geographic coverage regions.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_036": {
        "requirement_text": "Since it is not possible that all entities that need to access an ECRF will have one in their local domain, an ECRF for each 9-1-1 Authority MUST be accessible from the Internet",
        "document_section": "4.3.8",
        "description": "Since not all entities will have a local ECRF, an ECRF for each 9-1-1 Authority must be reachable and accessible from the public Internet.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_038": {
        "requirement_text": "Given that NG9-1-1 elements will also need to validate civic locations that either come with an emergency call, or are conveyed over the voice path, it is also a requirement that LVF elements MUST be reachable from within any ESInet. Since it is not possible that all entities that need to access an LVF will have one in their local domain, an LVF MUST be accessible from the Internet",
        "document_section": "4.3.8",
        "description": "LVF elements, used to validate civic locations, must be reachable from within any ESInet and must also be accessible from the Internet for entities that lack a local LVF.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_039": {
        "requirement_text": "Similar considerations apply for an ECRF, but the entities that route are often different from the entities that validate, so differences in deployments may occur. All devices and services that route MUST have access to an ECRF. External ECRFs MUST be accessible to all devices and services, including those on the Internet.",
        "document_section": "4.3.8",
        "description": "While ECRF and LVF functions may be deployed differently, all devices and services that route must have access to an ECRF, and external ECRFs must be accessible to all services, including those on the Internet.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_040": {
        "requirement_text": "Within the ESInet, ECRFs MUST be accessible from all ESRPs and all agencies that may receive or transfer calls or EIDOs related to calls.",
        "document_section": "4.3.8",
        "description": "ECRFs deployed within the ESInet must be accessible to all Emergency Services Routing Proxies ( ESRPs ) and all agencies involved in receiving or transferring calls or Emergency Incident Data Objects ( EIDOs ).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_041": {
        "requirement_text": "The LVF is a logical function that MAY share the physical platform of an ECRF, and MUST share the same data for a given jurisdiction as the ECRF.",
        "document_section": "4.3.8",
        "description": "The LVF is a logical function that may reside on the same physical platform as the ECRF, but it must use the exact same data for its jurisdiction as the ECRF.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_042": {
        "requirement_text": "An ECRF/LVF, wherever deployed, whether within an Origination or Access network, MUST be able to reach out to other ECRF/LVFs in case of missing data, or in the case in which the requested location is outside its local jurisdiction. If the ECRF/LVF doesn't know the answer, based on configuration, it will either recurse (refer) a request for validation to one or more other ECRF/LVFs, or it will iterate the request to some other ECRF/LVF, providing the other ECRF/LVF's URL in the original ECRF/LVF response.",
        "document_section": "4.3.8",
        "description": "The ECRF/LVF must be able to contact other ECRF/LVFs if the requested location is outside its jurisdiction or data is missing. It will either  recurse  (referring the query) or  iterate  (returning the other ECRF/LVF's URL) based on its configuration.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_043": {
        "requirement_text": "Localized ECRF/LVF elements MAY have limited data, sufficient to provide routing/location validation within its defined boundaries, but MUST rely on other ECRF/LVFs for routing/validation of a location outside its local area.",
        "document_section": "4.3.8",
        "description": "Localized ECRF/LVF elements can have limited data for their boundaries but must rely on other ECRF/LVFs for routing or validation of locations outside their local area.",
        "test_id": "ECRF_LVF_005",
        "subtests": [],
    },
    "RQ_ECRF-LVF_045": {
        "requirement_text": "There SHALL NOT be any single point of failure for any critical service or function hosted on the ESInet. Certain services designated as non-critical may be exempt from this requirement. These MUST NOT include the BCF, internal ECRF, ESRP, Logging Service, and security services.",
        "document_section": "2.7",
        "description": "There must be no single point of failure for any critical ESInet service or function. This requirement applies specifically to the BCF, internal ECRF, ESRP, Logging Service, and all security services.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_046": {
        "requirement_text": 'The LoST interface allows a geo-location to be expressed as a point or one of a number of defined "shapes" such as circle, ellipse, arc-band, or polygon. ECRFs MUST be able to handle all of these shapes.',
        "document_section": "3.4.3",
        "description": "The LoST interface supports geographical location input as a single point or various defined shapes, such as a circle or polygon. ECRFs must be able to process all these location shapes.",
        "test_id": "ECRF_LVF_002",
        "subtests": [],
    },
    "RQ_ECRF-LVF_047": {
        "requirement_text": 'The "service" element identifies the service requested by the client. Valid service names MUST be "urn:service:sos" or one of its sub-services for ECRF and LVF queries used by originating networks or devices for emergency calls.',
        "document_section": "3.4.3",
        "description": "For ECRF and LVF queries related to emergency calls, the 'service' element must be either the  'urn:service:sos ' service name or one of its valid sub-services.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_048": {
        "requirement_text": 'ECRF implementations MUST support "urn:emergency:service".',
        "document_section": "3.4.3",
        "description": "ECRF implementations are required to support the  'urn:emergency:service ' identifier.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_049": {
        "requirement_text": "Entities inside the ESInet MUST specify recursion by setting the recursive attribute in the <findService> request to 'true' and all ECRFs and LVFs MUST implement and perform recursion when requested to help mitigate the effect of an attack on the Internal Forest Guide (see Section 4.13.6).",
        "document_section": "3.4.3",
        "description": "Internal ESInet entities must enable recursion by setting the 'recursive' attribute to 'true' in a `<findService>` request. All ECRFs/LVFs must perform recursion when requested to help protect against Internal Forest Guide attacks.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_050": {
        "requirement_text": "All ECRF and LVF implementations MUST support both recursive and iterative modes.",
        "document_section": "3.4.4",
        "description": "All ECRF and LVF implementations are required to support both  recursive  and  iterative  modes of query resolution.",
        "test_id": "ECRF_LVF_005",
        "subtests": [],
    },
    "RQ_ECRF-LVF_051": {
        "requirement_text": 'An ECRF outside the ESInet is REQUIRED to support the "urn:service:sos" service. Service substitution, as described in RFC 5222 [48], SHALL be used to substitute "urn:service:sos" for all subservices such as "urn:service:sos.police", which would cause the call to be routed the same as a call to "urn:service:sos".',
        "document_section": "3.4.4",
        "description": "External ECRFs must support  'urn:service:sos '. Service substitution (RFC 5222) must be used to treat all sub-services (like 'urn:service:sos.police') the same as a generic 'urn:service:sos' for routing purposes.",
        "test_id": "ECRF_LVF_004",
        "subtests": [],
    },
    "RQ_ECRF-LVF_052": {
        "requirement_text": 'ECRFs inside the ESInet MUST support both "urn:service:sos" and "urn:emergency:service:sos".',
        "document_section": "3.4.4",
        "description": "ECRFs operating inside the ESInet must support both the  'urn:service:sos ' and  'urn:emergency:service:sos ' URNs.",
        "test_id": "ECRF_LVF_004",
        "subtests": [],
    },
    "RQ_ECRF-LVF_053": {
        "requirement_text": 'The <serviceNumber> element in the <mapping> response contains the emergency services number appropriate for the location provided in the query. This allows a foreign end device to recognize a dialed emergency number. The service number returned by an ECRF or LVF for an emergency call MUST be "911".',
        "document_section": "3.4.4",
        "description": "The `<serviceNumber>` element in the `<mapping>` response must contain the appropriate emergency number (which must be  '911 ' for an emergency call) to help foreign end devices recognize the dialed emergency number.",
        "test_id": "ECRF_LVF_002",
        "subtests": [],
    },
    "RQ_ECRF-LVF_054": {
        "requirement_text": "All ECRFs and LVFs MUST implement listServices and listServicesByLocation. The response to this request may depend on the (TLS) credentials of the querier.",
        "document_section": "3.4.7",
        "description": "All ECRFs and LVFs are required to implement both the  listServices  and  listServicesByLocation  functions. The response may vary based on the querier's TLS credentials.",
        "test_id": "ECRF_LVF_004",
        "subtests": [],
    },
    "RQ_ECRF-LVF_055": {
        "requirement_text": "An LVF SHOULD NOT return a degradedMatch warning if there is no potential for improvement (e.g., a road centerline match in a region where address points are not able to be provisioned).",
        "document_section": "3.4.10.2",
        "description": "An LVF should not return a  degradedMatch  warning if there is no practical way to improve the location match, such as matching a road centerline in an area lacking address points.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_056": {
        "requirement_text": "Vias MUST be returned to be compliant with RFC 5222 and are essential for use in error resolution.",
        "document_section": "3.4.4",
        "description": "Vias (LoST routing hops) must be returned to comply with RFC 5222 and are necessary for resolving errors.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_057": {
        "requirement_text": "All elements that implement LoST MUST implement the Call and Incident ID extension.",
        "document_section": "3.4.10.4",
        "description": "All elements implementing the LoST protocol are required to implement the  Call and Incident ID extension .",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_060": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_061": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_062": {
        "requirement_text": "ElementStateChangeLogEvent: When an element sends a notification of state change as described in the Element State section of this document, it MUST log the ElementStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When an element sends a notification of a state change, it must log the event using the ElementStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_063": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services",
        "document_section": "4.12.1",
        "description": "Clients of the Logging Service must support logging to at least two Logging Services for redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_064": {
        "requirement_text": "ServiceStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ServiceStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_065": {
        "requirement_text": "ServiceStateChangeLogEvent: When a Service sends a notification of state change as described in the Service State section of this document, which includes Security Posture, it MUST log the ServiceStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When a Service notifies of a state change, including security posture, it must log the event using the ServiceStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_066": {
        "requirement_text": "All agencies and NG9 1 1 functional elements MUST have access to a conformant Logging Service and log all relevant events in that service.",
        "document_section": "4.12.4",
        "description": "All agencies and NG9-1-1 functional elements must have access to and log all relevant events in a conformant Logging Service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_067": {
        "requirement_text": "ElementStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ElementStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_068": {
        "requirement_text": "(common LogEvent prologue (base object/header) table)",
        "document_section": "4.12.3.1",
        "description": "Refers to the table defining the common prologue (base object/header) that must be present in all LogEvents.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_069": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "KeepAliveFailureLogEvent must log malformed, invalid, or missing responses in the 'responseStatus' member, including text and a status code from the Status Codes Registry, such as 'TimeOut' for OPTIONS failures.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_070": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_071": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients of the Logging Service must support logging to at least two Logging Services to ensure redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_072": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations must be protected for integrity using TLS with at least  SHA-256 . SHA-256 is a mandatory feature for all implementations.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_073": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations must be protected for integrity using TLS with at least  SHA-256 . SHA-256 is a mandatory feature for all implementations.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_074": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations must use TLS for privacy, preferably with  AES-256  or a stronger encryption algorithm. Shorter key lengths are not permitted, and older systems using DES/3DES must be upgraded.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_075": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "KeepAliveFailureLogEvent must log malformed, invalid, or missing responses in the 'responseStatus' member, including text and a status code from the Status Codes Registry, such as 'TimeOut' for OPTIONS failures.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_076": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_077": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations must be protected for integrity using TLS with at least  SHA-256 . SHA-256 is a mandatory feature for all implementations.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_078": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients of the Logging Service must support logging to at least two Logging Services to ensure redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_079": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations must use TLS for privacy, preferably with  AES-256  or a stronger encryption algorithm. Shorter key lengths are not permitted, and older systems using DES/3DES must be upgraded.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_080": {
        "requirement_text": "FEs that use a Logging Service MUST NOT depend on a Logging Service accepting an extension to provide services conformant to this document.",
        "document_section": "4.12.3.1",
        "description": "Functional Elements (FEs) using a Logging Service must not rely on that service accepting an extension to maintain compliance with this document's services.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_081": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services must be capable of verifying the signature of a signed LogEvent before responding. A failed verification is a warning, returning a 'Signature Verification Failed' status, but the LogEvent must still be recorded, and the client should not retry the request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_082": {
        "requirement_text": "(LogEvents POST parameters)",
        "document_section": "4.12.3.1.2",
        "description": "Refers to the required parameters for a LogEvents POST request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_083": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services must be capable of verifying the signature of a signed LogEvent before responding. A failed verification is a warning, returning a 'Signature Verification Failed' status, but the LogEvent must still be recorded, and the client should not retry the request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_084": {
        "requirement_text": 'LostQueryLogEvent:  A "queryId" member is used to relate the request to the response. The id is generated locally, MUST be globally unique',
        "document_section": "4.12.3.7",
        "description": "The LostQueryLogEvent uses a locally-generated, globally unique 'queryId' member to link the query to its eventual response.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_085": {
        "requirement_text": "LostResponseLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the LostResponseLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_086": {
        "requirement_text": 'LostResponseLogEvent:  A "responseId" member is used to relate the request to the response, and MUST match the id used in the LostQueryLogEvent.',
        "document_section": "4.12.3.7",
        "description": "The LostResponseLogEvent must use a 'responseId' member that exactly matches the 'queryId' from the corresponding LostQueryLogEvent to relate the request and response.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_087": {
        "requirement_text": "SubscribeLogEvent: The Server MUST log this event",
        "document_section": "4.12.3.7",
        "description": "The Server is required to log the SubscribeLogEvent whenever a subscription request is processed.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_088": {
        "requirement_text": "SubscribeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the SubscribeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_089": {
        "requirement_text": "SubscribeLogEvent: The Server MUST log this event",
        "document_section": "4.12.3.7",
        "description": "The Server is required to log the SubscribeLogEvent whenever a subscription request is processed.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_090": {
        "requirement_text": "SubscribeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the SubscribeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_091": {
        "requirement_text": "LostQueryLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the LostQueryLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_092": {
        "requirement_text": "All DRs MUST contain common data elements (a prolog) that include: [see list]",
        "document_section": "3.7",
        "description": "All Discrepancy Reports (DRs) must contain a common set of data elements (a prolog).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_093": {
        "requirement_text": 'Implementations MUST support (be capable of generating and using) algorithm "EdDSA" and MUST NOT use other algorithms except that implementations of the Logging Service and clients of the Logging Service MUST support (be capable of generating and using) unsigned (algorithm "none")',
        "document_section": "2.8.1",
        "description": "Implementations must support the  'EdDSA ' algorithm and no others, except for the Logging Service and its clients, which must also support the unsigned  'none ' algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_094": {
        "requirement_text": 'If a Web Service request receives an "Unacceptable Algorithm" error, the client MUST make a new request on the Versions entry point and retry the request with a JWS that uses a signing algorithm acceptable to the Web Service.',
        "document_section": "2.8.2",
        "description": "If a Web Service client receives an 'Unacceptable Algorithm' error, it must query the Versions entry point and retry the request using a JWS with an acceptable signing algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_095": {
        "requirement_text": 'When this document indicates that a set of Web Service interface parameters is a JWS (e.g., for LogEvents), the set of parameters is conveyed in the web service request as a string consisting of a JWS. The JWS is formed by applying the JWS algorithm to the set of parameters per the JWS standard [171]. The JWS Protected Header MUST contain exactly one "alg" field. The "alg" field MUST have a value acceptable to the Web Service. An unsigned (unprotected) JWS is indicated by an "alg" field set to the value "none". For signed LogEvents, and all other uses of JWS requiring signatures (e.g., policy documents), the JWS Protected Header MUST have its "alg" field set to a value acceptable to the Web Service that MUST NOT be "none" and MUST specify the signing entity\'s X.509 certificate and all intermediate certificates up to one signed by the trusted root58. The certificate is provided either by reference or by value. A certificate provided by value is contained in an "x5c" field. A certificate is provided by reference using the "x5u" and "x5t#256" fields. When the "x5u" field is present, it MUST contain a URL that is stable (resolvable) for a minimum of 10 years. The JWS Protected Header MAY contain other fields. When the "x5u" field is used, the "x5t#256" field MUST also be used, to allow an entity to more easily detect when a certificate chain needs to be retrieved.',
        "document_section": "2.8.3",
        "description": "Web Service parameters, such as for LogEvents, are conveyed as a JWS string with an acceptable 'alg' field in the Protected Header. Signed LogEvents must use a non-'none' algorithm and include the signing entity's X.509 certificate, either by value ('x5c') or by reference ('x5u' and 'x5t#256').",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_096": {
        "requirement_text": "The functional elements described in this document MUST support the discrepancy report (DR) function.",
        "document_section": "2.8.3",
        "description": "All functional elements described in this document must be capable of supporting the discrepancy report (DR) function.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_097": {
        "requirement_text": "Clients MUST appropriately handle all status codes listed for each supported entry point, and MUST react appropriately to other status codes received, based on the first digit as per RFC 7231 [223] Section 6.",
        "document_section": "2.8.3",
        "description": "Clients must appropriately handle all listed status codes for supported entry points and react to all other status codes based on the first digit, as per RFC 7231, Section 6.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_098": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand",
        "document_section": "2.9",
        "description": "Implementations are required to ignore any elements within data structures that they do not understand.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_099": {
        "requirement_text": "Clients MUST retry transactions on redundant elements that that could not be completed on the initial element.",
        "document_section": "2.9",
        "description": "Clients must retry failed transactions on redundant elements if the initial element could not complete them.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_100": {
        "requirement_text": "Every implementation MUST be capable of using a DNS based implementation of redundant elements where more than one address may be returned for the URI provided.",
        "document_section": "2.9",
        "description": "All implementations must be capable of using a DNS-based approach for redundant elements where multiple addresses are returned for a single URI.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_101": {
        "requirement_text": "Implementations MUST be capable of preferring the first returned address, and using the second, third and optionally additional addresses returned as representing redundant elements for the service.",
        "document_section": "2.9",
        "description": "Implementations must prefer the first address returned but be capable of using subsequent addresses as redundant elements for the service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_102": {
        "requirement_text": "Other mechanisms to achieve redundancy MAY be provided, but the DNS based mechanism MUST be supported by all services and clients of those services.",
        "document_section": "3.1.3.2",
        "description": "While other redundancy mechanisms are optional, all services and clients must support the DNS-based mechanism for redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_103": {
        "requirement_text": 'a JWS MUST use the Flat JSON serialization format (not JWS Compact Serialization and not General JWS JSON Serialization Syntax), and only the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448 (algorithm "EdDSA") [227] [228] signature method is used.',
        "document_section": "3.7",
        "description": "A JWS must use the Flat JSON serialization format. The only permitted signature method is the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448, identified by the 'EdDSA' algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_104": {
        "requirement_text": "The services, unless specified otherwise, MUST support HTTP/1.1 (RFC 7230) [162] and SHOULD support HTTP/2.0 (RFC 7540) [197].",
        "document_section": "3.7",
        "description": "Services must support HTTP/1.1 and should also support HTTP/2.0, unless an exception is specified.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_105": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand and MUST return 404 errors to entry points to the web interfaces they don't provide as a server.",
        "document_section": "5.10",
        "description": "Implementations must ignore unknown elements in data structures and return a 404 error for web interface entry points they do not provide as a server.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_106": {
        "requirement_text": "Each database, service, and agency MUST provide a Discrepancy Reporting web service.",
        "document_section": "5.10",
        "description": "Every database, service, and agency is required to provide a Discrepancy Reporting web service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_107": {
        "requirement_text": 'Each Web Service MUST implement an entry point called "Versions".',
        "document_section": "5.10",
        "description": "Each Web Service must implement a mandatory entry point called  'Versions ' to indicate its supported version(s).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ECRF-LVF_108": {
        "requirement_text": "Entities implementing a notifier MUST implement RFC 3857 [26].",
        "document_section": "5.10",
        "description": "Any entity that implements a notifier function is required to implement RFC 3857.",
        "test_id": "",
        "subtests": [],
    },
}
