REQUIREMENTS_SCHEMA = {
    "RQ_BCF_001": {
        "requirement_text": 'The BCF, as the first active SIP element in the path of an emergency call, MUST add to the call the emergency-Call Identifier, emergency-Incident Tracking Identifier and a SIP Resource-Priority header field with a value from the "esnet" namespace (if not already present).',
        "document_section": "4.1.2",
        "description": "As the first SIP element, the BCF must add the emergency-Call Identifier, Incident Tracking Identifier, and a SIP Resource-Priority header using the 'esnet' namespace to emergency calls if they are not already present.",
        "test_id": "BCF_001",
        "subtests": [],
    },
    "RQ_BCF_002": {
        "requirement_text": "NG9‐1‐1 elements that process 9‐1‐1 calls MUST accept calls that do not strictly follow the SIP standards. As long as the messages can be parsed, and the method discerned, at least the first SIP element (the BCF) MUST be able to accept the call and forward the call onward (see Section 4.1) Support for the following SIP Methods is summarized and specified in the following table: (See underlying table)",
        "document_section": "3.1.1",
        "description": "BCF must accept and forward emergency calls even if they do not strictly follow SIP standards, provided the messages can be successfully parsed.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_003": {
        "requirement_text": 'BCFs[1] MUST police Resource-Priority of incoming SIP calls when the value comes from the "esnet" namespace. Any other namespace is ignored. BCFs MUST add a Resource-Priority header with an appropriate value from the "esnet" namespace if it is not present and should be included. BCFs MUST change or delete a value that is present on an incoming call that appears to be invalid or illegitimate.',
        "document_section": "3.1.7 & 4.1.2",
        "description": "BCF must validate the Resource-Priority header for incoming SIP calls using the 'esnet' namespace, ignoring others. It must add a missing 'esnet' value or correct/delete any invalid or illegitimate 'esnet' value.",
        "test_id": "BCF_001",
        "subtests": [
            "Stimulus and Output messages comparison",
            "Resource Priority header",
        ],
    },
    "RQ_BCF_004": {
        "requirement_text": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order when a queue of calls is waiting for service at the proxy server and, when needed, preempt lower priority calls",
        "document_section": "3.1.7",
        "description": "SIP proxy servers must use Resource-Priority to process queued calls in priority order and preempt lower-priority calls when necessary.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_005": {
        "requirement_text": 'BCFs MUST add a Resource-Priority header with an appropriate value from the "esnet"namespace if it is not present and should be included.',
        "document_section": "3.1.7",
        "description": "BCF must add a Resource-Priority header with an appropriate value from the 'esnet' namespace if it is missing from an emergency call.",
        "test_id": "BCF_001",
        "subtests": [
            "Stimulus and Output messages comparison",
            "Resource Priority header",
        ],
    },
    "RQ_BCF_006": {
        "requirement_text": "BCFs MUST change or delete a value that is present on an incoming call that appears to be invalid or illegitimate.",
        "document_section": "3.1.7",
        "description": "BCF must correct or remove any Resource-Priority value on an incoming call that is considered invalid or illegitimate.",
        "test_id": "BCF_001",
        "subtests": [
            "Verify 'urn:service:sos' in request URI",
            "Verify 'urn:service:sos' is in 'TO' header field",
        ],
    },
    "RQ_BCF_007": {
        "requirement_text": 'Those calls that appear to be emergency calls (such as those To: 911 but without a Request-URI of "urn:service:sos") MUST be marked with a provisioned Resource-Priority, which defaults to "esnet.1".',
        "document_section": "3.1.7",
        "description": "Calls that look like emergency calls (e.g., To: 911) but lack the 'urn:service:sos' Request-URI must be assigned a Resource-Priority, which defaults to 'esnet.1'.",
        "test_id": "BCF_001",
        "subtests": [
            "Stimulus and Output messages comparison",
            "Resource Priority header",
        ],
    },
    "RQ_BCF_008": {
        "requirement_text": "Elements on an ESInet SHALL assume a SIP call entering the ESInet is an emergency call unless it can determine it is something else, such as a call to an administrative number. Even if the call does not have the emergency service URN in the Request-URI, the call SHOULD be assumed to be an emergency call and the Request-URI SHALL be rewritten to urn:service:sos by the BCF or originating ESRP.",
        "document_section": "3.1.7",
        "description": "ESInet elements must assume a call is an emergency call by default, unless otherwise identified. The BCF or ESRP must rewrite the Request-URI to 'urn:service:sos' if the emergency service URN is missing.",
        "test_id": "BCF_001",
        "subtests": [
            "Stimulus and Output messages comparison",
            "Verify 'urn:service:sos' in request URI",
            "Verify 'urn:service:sos' is in 'TO' header field",
        ],
    },
    "RQ_BCF_009": {
        "requirement_text": "The functional elements described in this document MUST support the discrepancy report (DR) function.",
        "document_section": "3.7",
        "description": "All functional elements described in this document must be capable of supporting the discrepancy report (DR) function.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_013": {
        "requirement_text": "The SBC component of the BCF SHALL support SIP/SDP protocol normalization and/or repair, including adjustments of encodings to a core network profile. ",
        "document_section": "4.1.1",
        "description": "The BCF's SBC component must be able to normalize and repair SIP/SDP protocols to ensure encodings match the core network profile.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_014": {
        "requirement_text": "The SBC component of the BCF SHALL perform NAT traversal for authorized calls/sessions using the SIP protocol. The SBC component MUST be able to recognize that a NAT or NAPT has been performed on Layer 3 but not above and correct the signaling messages for SIP.",
        "document_section": "4.1.1",
        "description": "The BCF's SBC must handle NAT traversal for authorized SIP calls. It must detect Layer 3 NAT/NAPT and correct the SIP signaling messages accordingly.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_015": {
        "requirement_text": "The SBC component of the BCF SHALL enable interworking between networks utilizing IPv4 and networks using IPv6 through the use of dual stacks, selectable for each SBC interface. All valid IPv4 addresses and parameters SHALL be translated to/from the equivalent IPv6 values. ",
        "document_section": "4.1.1",
        "description": "The BCF's SBC must support interworking between IPv4 and IPv6 networks using selectable dual stacks on each interface. It must translate all valid IPv4 addresses and parameters to/from their IPv6 equivalents.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_016": {
        "requirement_text": "The SBC component of the BCF SHALL support SIP over the following protocols: TCP, UDP, TLS-over-TCP, and SCTP. Protocols supported MUST be selectable for each SBC interface to external systems.",
        "document_section": "4.1.1",
        "description": "The BCF's SBC must support SIP over TCP, UDP, TLS-over-TCP, and SCTP, with the supported protocols selectable per external interface.",
        "test_id": "BCF_003",
        "subtests": [],
    },
    "RQ_BCF_017": {
        "requirement_text": "The SBC component of the BCF MUST use TLS with AES-256 or better towards the ESInet.",
        "document_section": "4.1.1",
        "description": "The BCF's SBC component must secure its communication towards the ESInet using TLS with a minimum of AES-256 encryption.",
        "test_id": "BCF_003",
        "subtests": [],
    },
    "RQ_BCF_018": {
        "requirement_text": "The SBC component of the BCF SHALL support terminating the IP signaling received from a foreign carrier onto the ESInet address space. The SBC component of the BCF SHALL support B2BUA functions to enable VPN bridging if needed.",
        "document_section": "4.1.1",
        "description": "The BCF's SBC must terminate IP signaling from foreign carriers onto the ESInet address space. It must also support B2BUA functions to enable VPN bridging if required.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_019": {
        "requirement_text": "The SBC component of the BCF SHALL be capable of populating the layer 2 and layer 3 headers/fields, based on call/session type (e.g., 9 1 1 calls) in order to facilitate priority routing of the packets.",
        "document_section": "4.1.1",
        "description": "The BCF's SBC must be able to populate Layer 2 and Layer 3 headers/fields based on the call type, such as 9-1-1 calls, to enable priority packet routing.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_020": {
        "requirement_text": "The SBC component of the BCF SHALL be capable of producing CDRs based on call/session control information (e.g., SIP/SDP). ",
        "document_section": "4.1.1",
        "description": "The BCF's SBC component must be capable of generating Call Detail Records (CDRs) using information from call/session control protocols like SIP/SDP.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_021": {
        "requirement_text": "All media connections exiting the SBC towards the ESInet MUST be protected against eavesdropping, alteration, and replay using AES-256 or better.",
        "document_section": "4.1.1",
        "description": "All media connections leaving the SBC and going to the ESInet must be protected against eavesdropping, alteration, and replay using at least AES-256 encryption.",
        "test_id": "BCF_003",
        "subtests": [],
    },
    "RQ_BCF_022": {
        "requirement_text": "An SBC component of the BCF which always anchors media achieves this by accepting any media, with SRTP or not, and MUST protect the media towards the ESInet.",
        "document_section": "4.1.1",
        "description": "A BCF SBC that always anchors media must accept any media format, with or without SRTP, and must encrypt the media towards the ESInet.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_023": {
        "requirement_text": "An SBC that does not routinely anchor media MUST anchor media for calls entering without sufficient protection (AES-256 or better) and MUST protect the media towards the ESInet.",
        "document_section": "4.1.1",
        "description": "An SBC that doesn't usually anchor media must do so for calls lacking sufficient protection (AES-256 or better) and must then protect that media towards the ESInet.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_024": {
        "requirement_text": "Provide both application and network layer protection and scanning;",
        "document_section": "4.1.1",
        "description": "The BCF must provide security protection and scanning capabilities at both the application and network layers.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_025": {
        "requirement_text": 'The BCF SHALL support an automated interface that allows a downstream element to mark a particular source of a call as a "bad actor" (usually due to receipt of a call that appears to be part of a deliberate attack on the system) and send a message to the BCF notifying it of this marking.  Reference the "BadActors" interface.',
        "document_section": "4.1.2",
        "description": "The BCF must support an automated interface, like the 'BadActors' interface, to receive and process notifications from downstream elements marking a call source as a 'bad actor'.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_026": {
        "requirement_text": 'To facilitate this notification, the BCF SHALL insert a Call-Info header field with a purpose parameter of "emergency-source" in the outgoing INVITE message associated with every call.',
        "document_section": "4.1.2",
        "description": "To assist with 'bad actor' notifications, the BCF must add a Call-Info header with the 'emergency-source' purpose parameter to every outgoing INVITE message.",
        "test_id": "BCF_004",
        "subtests": [
            "Validate if outgoing SIP INVITE messages contain correct source-ID"
        ],
    },
    "RQ_BCF_027": {
        "requirement_text": 'calls MUST be marked by the SBC component in a way that allows the recipient to identify the BCF that processed the call. The source-ID is formatted as follows: <unique source-id>@<domain name of BCF> (e.g., "a7123gc42@sbc22.example.net" ).',
        "document_section": "4.1.2",
        "description": "The SBC component must mark calls with a source-ID (e.g., '<unique source-id>@<domain name of BCF>') so the recipient can identify the BCF that processed the call.",
        "test_id": "BCF_004",
        "subtests": [
            "Validate if outgoing SIP INVITE messages contain correct source-ID"
        ],
    },
    "RQ_BCF_028": {
        "requirement_text": "The notification MUST be propagated to all such SBCs. The mechanism for doing so is not specified.",
        "document_section": "4.1.2",
        "description": "Bad actor notifications must be spread to all relevant SBCs, although the exact mechanism for this propagation is not defined.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_029": {
        "requirement_text": "Source-Ids MUST be unguessable.",
        "document_section": "4.1.2",
        "description": "The source identifiers used to mark calls must be cryptographically unguessable and unpredictable.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_030": {
        "requirement_text": "If the BCF does not recognize the source-id, it MUST ignore the request.",
        "document_section": "4.1.2",
        "description": "The BCF must ignore any 'bad actor' request if it does not recognize the source-id included in that request.",
        "test_id": "BCF_004",
        "subtests": [
            "Validate BCF 433 response code for HTTP POST to /BadActors with unknown source-ID"
        ],
    },
    "RQ_BCF_031": {
        "requirement_text": "BCFs that anchor media MUST implement the Session Recording Client interface defined by SIPREC (RFC 7866) [116].",
        "document_section": "4.1.2",
        "description": "Any BCF that anchors media is required to implement the Session Recording Client (SRC) interface as defined in SIPREC (RFC 7866).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_033": {
        "requirement_text": "All Bridge elements (Section 5.7), Gateway elements (Section 7), BCF elements that anchor media, and PSAP Call Handling elements, MUST implement the SRC interface.",
        "document_section": "4.12.2",
        "description": "Bridge, Gateway, media-anchoring BCF, and PSAP Call Handling elements must all implement the Session Recording Client (SRC) interface.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_034": {
        "requirement_text": 'For the purposes of this requirement there was no specific text to reference, but the group agreed that BCFs should always be stateful, with that understanding the group progressed through table 10.21 "LogEvent" registry and selected those events that would apply to a stateful BCF.',
        "document_section": "4.12.3.7 & 10.21",
        "description": "BCFs must be stateful and log all relevant events from the 'LogEvent' registry (Table 10.21) that apply to a stateful BCF.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_035": {
        "requirement_text": "The SBC component of the BCF SHALL be capable of producing CDRs based on call/session control information (e.g., SIP/SDP).",
        "document_section": "4.1.1",
        "description": "The BCF's SBC component must be capable of generating Call Detail Records (CDRs) using information from call/session control protocols like SIP/SDP.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_036": {
        "requirement_text": "All elements in the ESInet MUST accept RSA-2048 with a certificate rooted in the PCA.",
        "document_section": "5.5",
        "description": "All ESInet elements must accept RSA-2048 security certificates that are rooted in the Policy Certification Authority (PCA).",
        "test_id": "BCF_003",
        "subtests": [],
    },
    "RQ_BCF_037": {
        "requirement_text": "Authorization and Data Rights Management",
        "document_section": "5.6",
        "description": "BCF must implement controls for Authorization and Data Rights Management.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_038": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA‐256 [62] or stronger. SHA‐256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations must use TLS for integrity protection, with SHA-256 or stronger. SHA-256 must be supported by all implementations.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_039": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES‐256). Shorter key length MUST NOT be used.",
        "document_section": "5.8",
        "description": "All protocol operations must be protected for privacy via TLS, using at least AES-256 encryption. Shorter key lengths are forbidden.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_040": {
        "requirement_text": "Stored data which contains confidential information MUST be stored encrypted, using AES‐256 or an equivalently strong algorithm.",
        "document_section": "5.8",
        "description": "Any stored data containing confidential information must be encrypted using AES-256 or an equivalently strong algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_041": {
        "requirement_text": "JSON Web Signature",
        "document_section": "5.1",
        "description": "BCF must support the use of JSON Web Signature (JWS) for data authentication.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_042": {
        "requirement_text": "Data and the Emergency Incident Data Object",
        "document_section": "7",
        "description": "BCF must properly handle and manage data, including the Emergency Incident Data Object (EIDO).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_043": {
        "requirement_text": "All SIP elements MUST support TLS (See Section 2.8.1), TCP, and UDP transport. SIP signaling within the ESInet SHOULD be carried with TLS. If TLS transport fails or is not available, SIP elements SHOULD attempt to use TCP. If TLS and TCP transports both fail or are unavailable, SIP elements SHOULD fall back to UDP transport.",
        "document_section": "3.1.13",
        "description": "All SIP elements must support TLS, TCP, and UDP transport, with a preference for TLS, then TCP, and finally UDP if others fail.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_044": {
        "requirement_text": "Media streams for voice, video, and text MUST be carried on RTP over UDP (User Datagram Protocol). All endpoints in an ESInet MUST implement media security with Secure Real Time Protocol (SRTP) using Datagram Transport Layer Security (DTLS) as specified in RFC 5763 [166] and RFC 5764 [167].",
        "document_section": "3.1.9",
        "description": "Voice, video, and text media streams must use RTP over UDP. All ESInet endpoints must secure this media using Secure Real Time Protocol (SRTP) with Datagram Transport Layer Security (DTLS).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_045": {
        "requirement_text": 'The form of a Call Identifier is a Uniform Resource Name (URN) (RFC 2141) [112] formed by the prefix "urn:emergency:uid:callid:", a unique string containing alpha and/or numeric characters, the ":" character, and the Element Identifier of the element that first handled the call. The unique string portion of the Call Identifier MUST be unique for each call the element handles over time. The length of the unique string portion of the Call Identifier MUST be a string of 10 to 32 characters.',
        "document_section": "2.1.6",
        "description": "A Call Identifier must be a URN starting with 'urn:emergency:uid:callid:'. It includes a unique 10-to-32-character string followed by the Element Identifier of the first handling element.",
        "test_id": "BCF_001",
        "subtests": [
            "Stimulus and Output messages comparison",
            "Emergency Call Identifier header",
            "Emergency Call Identifier URN",
            "Emergency Call Identifier String ID",
            "Emergency Call Identifier FQDN",
        ],
    },
    "RQ_BCF_046": {
        "requirement_text": 'The form of an Incident Tracking Identifier is a URN formed by the prefix "urn:emergency:uid:incidentid:", a unique string containing alpha and/or numeric characters, the ":" character, and the Element Identifier of the entity that first declared the incident. For example, "urn:emergency:uid:incidentid:a56e556d871:bcf.state.pa.us" is a properly formatted Incident Tracking Identifier. The string MUST be unique for each Incident the element handles over time. The length of the unique string portion of the Incident Tracking Identifier MUST be a string of 10 to 32 characters.',
        "document_section": "2.1.7",
        "description": "An Incident Tracking Identifier must be a URN starting with 'urn:emergency:uid:incidentid:'. It includes a unique 10-to-32-character string and the Element Identifier of the entity that first declared the incident.",
        "test_id": "BCF_001",
        "subtests": [
            "Stimulus and Output messages comparison",
            "Incident Tracking Identifier URN",
            "Incident Tracking Identifier String ID",
            "Incident Tracking Identifier FQDN",
        ],
    },
    "RQ_BCF_047": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements:request (If the discrepancy concerns a dialog, the initial INVITE that initiated the dialog )',
        "document_section": "3.7.6",
        "description": "When a BCF Discrepancy Report is sent, the 'problemService' must be 'BCF'. If the issue is dialog-related, the report must include the initial INVITE message that started the dialog.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_048": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: problem (One of the following tokens: InitialTrafficBlocked, MidTrafficBlocked, BadSDP, BadSIP, MediaLoss, TrafficNotBlockedBadActor, TrafficNotBlocked, QoS, BadCDR, TTY, Firewall, OtherBCF)',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF' and include a 'problem' token from a defined list indicating the issue type (e.g., BadSIP, MediaLoss, Firewall).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_049": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: sosSource (The emergency-source parameter of the dialog request (i.e., the initial INVITE))',
        "document_section": "3.7.6",
        "description": "When submitting a BCF Discrepancy Report, the 'problemService' is 'BCF' and the object must include the 'sosSource' parameter from the initial INVITE of the dialog request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_050": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: EventTimestamp (Timestamp of event being reported)',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF' and include the 'EventTimestamp' to record when the reported event occurred.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_051": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: packetHeader (For InitialTrafficBlocked, MidTrafficBlocked, TrafficNotBlockedBadActor, TrafficNotBlocked, or Firewall, contains the packet\'s header, encoded using base64)',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF'. For traffic-related problems, the report must include the packet's header encoded in base64.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_052": {
        "requirement_text": "All Bridge elements (Section 5.7), Gateway elements (Section 7), BCF elements that anchor media, and PSAP Call Handling elements, MUST implement the SRC interface.",
        "document_section": "4.12.2",
        "description": "Bridge, Gateway, media-anchoring BCF, and PSAP Call Handling elements must all implement the Session Recording Client (SRC) interface.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_053": {
        "requirement_text": "Provide both application and network layer protection and scanning;",
        "document_section": "4.1.1",
        "description": "BCF must provide security protection and scanning capabilities at both the application and network layers.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_054": {
        "requirement_text": "Denial of Service (DoS) detection and protection;",
        "document_section": "4.1.1",
        "description": "BCF must include functionality for detecting and protecting against Denial of Service (DoS) attacks.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_055": {
        "requirement_text": "Provide a mechanism such that malware definitions and patterns can be easily and quickly updated by a national 9 1 1 Computer Emergency Response Team (CERT) or other managing authority;",
        "document_section": "4.1.1",
        "description": "BCF must provide a mechanism for easily and quickly updating malware definitions and patterns from a national 9-1-1 CERT or other managing authority.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_056": {
        "requirement_text": "Capability to receive and update 9 1 1 Malicious Content (NMC) filtering automatically for use by federated firewalls in protecting multiple disparate ESInets.",
        "document_section": "4.1.1",
        "description": "BCF must be capable of automatically receiving and updating 9-1-1 Malicious Content (NMC) filtering for use by federated firewalls protecting different ESInets.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_057": {
        "requirement_text": "Opening and closing of a pinhole (firewall)",
        "document_section": "4.1.1",
        "description": "BCF must support the dynamic opening and closing of a firewall pinhole for media traffic.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_058": {
        "requirement_text": "Resource and admission control",
        "document_section": "4.1.1",
        "description": "BCF must implement resource and admission control mechanisms to manage call capacity and network resources.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_059": {
        "requirement_text": "IP payload processing",
        "document_section": "4.1.1",
        "description": "BCF must include functionality for the appropriate processing of IP packet payloads.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_060": {
        "requirement_text": "The SBC component of the SBC SHALL perform the following functions: … Performance measurement",
        "document_section": "4.1.1",
        "description": "The BCF's SBC component must perform performance measurement functions.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_061": {
        "requirement_text": "Elements that implement the SRC interface MUST be capable of supporting redundant implementations of the SRS (RFC 7866) [116] and MUST insert the Call Identifier and Incident Tracking Identifier (Call-Info header fields) defined in this document into the INVITE sent to the Logging Service.",
        "document_section": "4.12.2",
        "description": "SRC-implementing elements must support redundant SRS (Logging Service) implementations. They must include the Call Identifier and Incident Tracking Identifier in the INVITE sent to the Logging Service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_062": {
        "requirement_text": "The Logging Service and its SRC interface MUST log the SIPREC Metadata LogEvent (see the LogEvent section for details).",
        "document_section": "4.12.2",
        "description": "The Logging Service and its Session Recording Client (SRC) interface must record the SIPREC Metadata LogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_063": {
        "requirement_text": "When an SRC sends SIPREC Metadata, it MUST generate a SiprecMetadata LogEvent to the Logging Service.",
        "document_section": "4.12.2",
        "description": "When a Session Recording Client (SRC) sends SIPREC Metadata, it must generate an accompanying SiprecMetadata LogEvent to the Logging Service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_064": {
        "requirement_text": "The SRC MUST include the CallId and IncidentId for the emergency call being recorded in the SIPREC INVITE it generates and when generating an associated SiprecMetadata LogEvent.",
        "document_section": "4.12.2",
        "description": "The SRC must include the CallId and IncidentId for the emergency call in both the generated SIPREC INVITE and the associated SiprecMetadata LogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_065": {
        "requirement_text": "Each emergency call (that is, each Communication Session), MUST result in a separate Recording Session.",
        "document_section": "4.12.2",
        "description": "Every emergency call (Communication Session) must be logged as a unique and separate Recording Session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_066": {
        "requirement_text": "All SRCs and SRSes MUST implement RTCP on the recording session.",
        "document_section": "4.12.2",
        "description": "All Session Recording Clients (SRCs) and Session Recording Servers (SRSes) must implement RTCP for the recording session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_067": {
        "requirement_text": "The SRC MUST send wall clock time in sender reports",
        "document_section": "4.12.2",
        "description": "The Session Recording Client (SRC) must include the wall clock time when sending RTCP sender reports.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_068": {
        "requirement_text": "SRCs MUST support recording of media to at least two SRSes.",
        "document_section": "4.12.2",
        "description": "Session Recording Clients (SRCs) must support recording of media to a minimum of two Session Recording Servers (SRSes) for redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_069": {
        "requirement_text": "The call MUST go on even if there is no recorder.",
        "document_section": "4.12.2",
        "description": "The emergency call must continue even if a recorder is unavailable. The media anchor logs the MediaEndLogEvent when media ends in a communication session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_070": {
        "requirement_text": "CallStartLogEvent: Logged by an FE that is call stateful, when it begins processing a call.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The CallStartLogEvent is logged by a call-stateful functional element (FE) when it begins processing a call.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_071": {
        "requirement_text": "CallEndLogEvent: Logged by an element that is call stateful, when its processing of a call ends. ",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The CallEndLogEvent is logged by a call-stateful element when its processing of a call is complete.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_072": {
        "requirement_text": "RecCallStartLogEvent: RecCallStartEvent is identical to CallStartEvent, but is logged by the Logging Service (SRS) and the client (SRC) to denote the beginning of a SIPREC recording session.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The RecCallStartLogEvent is logged by both the Logging Service (SRS) and the client (SRC) to mark the beginning of a SIPREC recording session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_073": {
        "requirement_text": "RecCallEndLogEvent: RecCallEndEvent is identical to CallEndEvent, but is logged by the Logging Service (SRS) and the client (SRC) to denote the end of a SIPREC recording session.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The RecCallEndLogEvent is logged by both the Logging Service (SRS) and the client (SRC) to mark the end of a SIPREC recording session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_074": {
        "requirement_text": "RouteLogEvent: When a call is transferred, the transfer is logged by the transferor (the entity that had the call prior to transferring it).",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The RouteLogEvent must be logged by the entity that transfers a call, recording the details of the transfer.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_075": {
        "requirement_text": "MediaStartLogEvent: This event is logged by any media anchor (call recipient for an emergency call, caller for a callback, bridge, or BCF if the BCF anchors media) when at the start of media reception or transmission as appropriate.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The MediaStartLogEvent is logged by any media anchor, including the BCF if it anchors media, at the start of media reception or transmission.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_076": {
        "requirement_text": "MediaEndLogEvent: This event is logged by any media anchor (call recipient for an emergency call, caller for a callback, bridge, or BCF if the BCF anchors media) for the communication session media.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The MediaEndLogEvent is logged by any media anchor, including the BCF if it anchors media, when the media for the communication session ends.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_077": {
        "requirement_text": "RecMediaStartLogEvent: Both the SRC and SRS log RecMediaStartLogEvent/RecMediaEndLogEvent. ",
        "document_section": "4.12.3.7 & 10.21",
        "description": "Both the Session Recording Client (SRC) and Session Recording Server (SRS) must log the RecMediaStartLogEvent and RecMediaEndLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_078": {
        "requirement_text": "RQ_BCF_078",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The ElementStateChangeLogEvent is logged by an element to notify a state change.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_079": {
        "requirement_text": "RecordingFailedLogEvent: The Session Recording Client in a SIPREC media recording session is responsible for logging this event.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The Session Recording Client (SRC) must log the RecordingFailedLogEvent if a SIPREC media recording session fails.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_080": {
        "requirement_text": "MessageLogEvent: A SIP Message is logged with a MessageLogEvent",
        "document_section": "4.12.3.7 & 10.21",
        "description": "Any SIP message is logged using the MessageLogEvent.",
        "test_id": "BCF_005",
        "subtests": [
            "Validate BCF sends HTTP POST to /LogEvents",
            "Validate BCF forwards SIP from OSP to ESRP",
            "Validate Log Event depends on SIP MESSAGE",
            "Validate Log Event depends on SIP Other message type",
        ],
    },
    "RQ_BCF_081": {
        "requirement_text": "CallSignalingMessageLogEvent: An element MUST log outgoing messages it originates. ",
        "document_section": "4.12.3.7 & 10.21",
        "description": "An element must log all outgoing messages that it originates using the CallSignalingMessageLogEvent.",
        "test_id": "BCF_005",
        "subtests": [
            "Validate BCF sends HTTP POST to /LogEvents",
            "Validate BCF forwards SIP from OSP to ESRP",
            "Validate Log Event depends on SIP MESSAGE",
            "Validate Log Event depends on SIP Other message type",
        ],
    },
    "RQ_BCF_082": {
        "requirement_text": "NonRtpMediaMessageLogEvent: An element MUST log outgoing messages it originates.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "An element must log all outgoing non-RTP media messages it originates using the NonRtpMediaMessageLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_083": {
        "requirement_text": "MalformedMessageLogEvent: An element that receives a malformed SIP message logs it with the MalformedMessageLogEvent. ",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The MalformedMessageLogEvent must be used by an element to log any malformed SIP message it receives.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_084": {
        "requirement_text": "DiscrepancyReportLogEvent: Any element that sends or receives a Discrepancy Report, or that sends or receives an update (Status, Resolution, etc.) for one, logs what it sent or received with the DiscrepancyReportLogEvent.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "Any element sending or receiving a Discrepancy Report or an update for one must log the transaction using the DiscrepancyReportLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_085": {
        "requirement_text": "ElementStateeChangeLogEvent: When an element sends a notification of state change as described in the Element State section of this document, it MUST log the ElementStateChangeLogEvent.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "When an element sends a state change notification, it must log the event using the ElementStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_086": {
        "requirement_text": "ServiceStateChangeLogEvent: When a Service sends a notification of state change as described in the Service State section of this document, which includes Security Posture, it MUST log the ServiceStateChangeLogEvent.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "When a Service notifies of a state change, including security posture, it must log the event using the ServiceStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_087": {
        "requirement_text": "CallStateChangeLogEvent: CallStateChangeLogEvent MUST be logged by all elements that change the state of the call, which would include a bridge and all entities within the ESInet that request bridge actions when an emergency call is on a bridge.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "All elements that change the state of a call, including a bridge and entities requesting bridge actions, must log the CallStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_088": {
        "requirement_text": 'KeepAliveFailureLogEvent: The OPTIONS request is the "keep alive" mechanism specified in this document (Section 3.1.2.3).',
        "document_section": "4.12.3.7 & 10.21",
        "description": "The KeepAliveFailureLogEvent logs failures related to the OPTIONS request, which serves as the 'keep alive' mechanism.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_089": {
        "requirement_text": "VersionsLogEvent: Records the response to a web service Versions request (See Section 2.8).",
        "document_section": "4.12.3.7 & 10.21",
        "description": "The VersionsLogEvent records the response received following a web service Versions request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_090": {
        "requirement_text": "SubscribeLogEvent: When a subscription request is processed for any defined Event Package, the transaction is logged with SubscribeLogEvent.",
        "document_section": "4.12.3.7 & 10.21",
        "description": "When any defined Event Package subscription request is processed, the transaction must be logged using the SubscribeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_091": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements:request (If the discrepancy concerns a dialog, the initial INVITE that initiated the dialog )',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF'. If the discrepancy is about a dialog, it must include the initial INVITE that started the dialog.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_092": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: problem (One of the following tokens: InitialTrafficBlocked, MidTrafficBlocked, BadSDP, BadSIP, MediaLoss, TrafficNotBlockedBadActor, TrafficNotBlocked, QoS, BadCDR, TTY, Firewall, OtherBCF)',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF' and include a 'problem' token from a defined list indicating the issue type, such as BadSIP, MediaLoss, or Firewall.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_093": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: sosSource (The emergency-source parameter of the dialog request (i.e., the initial INVITE))',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF' and include the 'sosSource' parameter from the initial INVITE of the dialog request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_094": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: EventTimestamp (Timestamp of event being reported)',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF' and include the 'EventTimestamp' to record when the reported event occurred.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_095": {
        "requirement_text": 'When a BCFDiscrepancyReport is submitted, the "problemService" parameter is set to "BCF" and the object contains the following elements: packetHeader (For InitialTrafficBlocked, MidTrafficBlocked, TrafficNotBlockedBadActor, TrafficNotBlocked, or Firewall, contains the packet\'s header, encoded using base64)',
        "document_section": "3.7.6",
        "description": "A BCF Discrepancy Report must set 'problemService' to 'BCF'. For traffic-related problems, the report must include the packet's header encoded in base64.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_096": {
        "requirement_text": "It MUST send a 200 OK indicating that the party was successfully added.",
        "document_section": "4.7.2",
        "description": "The element must send a 200 OK response to indicate that a party was successfully added to the call/session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_097": {
        "requirement_text": "All endpoints and media intermediaries within an ESInet/NGCS MUST support CPIM.",
        "document_section": "4.7.6",
        "description": "All endpoints and media intermediaries within the ESInet/NGCS must support the Common Presence and Instant Messaging (CPIM) protocol.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_098": {
        "requirement_text": "Negotiation of multi-party awareness SHALL be performed by mixers and endpoints at session initiation and modification.",
        "document_section": "4.8.1",
        "description": "Mixers and endpoints must negotiate multi-party awareness when a session is initiated or modified.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_107": {
        "requirement_text": "SIP entities implementing REFER MUST implement RFC 4508 [38] and the Replaces Header Field, RFC 3891 [27].",
        "document_section": "3.1.1.2",
        "description": "SIP entities that implement the REFER method must also implement RFC 4508 and the Replaces Header Field (RFC 3891).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_108": {
        "requirement_text": "All endpoints and media intermediaries within an ESInet/NGCS MUST support CPIM.",
        "document_section": "4.7.6",
        "description": "All endpoints and media intermediaries within the ESInet/NGCS must support the Common Presence and Instant Messaging (CPIM) protocol.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_109": {
        "requirement_text": "All NG9-1-1 implementations MUST supply identity information in this manner to the bridge.",
        "document_section": "4.8",
        "description": "All NG9-1-1 implementations are required to supply identity information to the bridge in the specified manner.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_110": {
        "requirement_text": "Once the REFER is successfully acknowledged with a 200 OK, the recipient of the REFER will send notifications of the status of the adding the target participant. It MAY send a notification containing a 100 Trying to indicate the transfer is pending. It MAY also send additional provisional messages, e.g. 183 Session Progress. It MUST send a 200 OK indicating that the party was successfully added.",
        "document_section": "4.7.2",
        "description": "After a successful 200 OK acknowledgment for a REFER, the recipient must send status notifications while adding the target. It must conclude by sending a 200 OK to confirm the party was successfully added.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_111": {
        "requirement_text": 'If the B2BUA receives an INVITE from a caller that does not include a Supported header field containing the "replaces"  option-tag, it MUST include a Supported header field containing the "replaces" option-tag in the INVITE forwarded to the ESInet and provide the functionality described in this section.',
        "document_section": "4.7.1",
        "description": "If a B2BUA receives an INVITE without the 'replaces' option-tag in the Supported header, it must add the 'replaces' option-tag to the Supported header in the INVITE it forwards to the ESInet and provide the associated functionality.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_112": {
        "requirement_text": "The caller, or some element in the path, MUST implement the Replaces header field (see Section 3.1.1.2).",
        "document_section": "4.7.1",
        "description": "The Replaces header field must be implemented by the caller or by an element in the call's path.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_113": {
        "requirement_text": "All endpoints and media intermediaries within an ESInet/NGCS MUST support CPIM.",
        "document_section": "4.7.6",
        "description": "All endpoints and media intermediaries within the ESInet/NGCS must support the Common Presence and Instant Messaging (CPIM) protocol.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_114": {
        "requirement_text": "A REFER request implicitly establishes a subscription to the refer event as defined in RFC 3515 [19], but not regarding the conference as a whole. Once the REFER is successfully acknowledged with a 200 OK, the recipient of the REFER will send notifications of the status of the adding the target participant. It MAY send a notification containing a 100 Trying to indicate the transfer is pending. It MAY also send additional provisional messages, e.g. 183 Session Progress. It MUST send a 200 OK indicating that the party was successfully added. At this point the transferring PSAP MUST send a BYE to end its participation in the call. If the transferring PSAP receives an error code in the notification, e.g. 503 Service Unavailable, it MUST assume that the transfer did not occur and MUST not terminate the call. ",
        "document_section": "4.7.3",
        "description": "A REFER implicitly establishes a subscription to the 'refer' event. Once acknowledged with a 200 OK, the recipient sends status updates, concluding with a 200 OK for a successful add. A transferring PSAP must then send a BYE or, if an error is received, must not terminate the call.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_115": {
        "requirement_text": "All NG9 1 1 implementations MUST supply identity information in this manner to the bridge.",
        "document_section": "4.8",
        "description": "All NG9-1-1 implementations are required to supply identity information to the bridge in the specified manner.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_116": {
        "requirement_text": "A REFER request implicitly establishes a subscription to the refer event as defined in RFC 3515 [19], but not regarding the conference as a whole. Once the REFER is successfully acknowledged with a 200 OK, the recipient of the REFER will send notifications of the status of the adding the target participant. It MAY send a notification containing a 100 Trying to indicate the transfer is pending. It MAY also send additional provisional messages, e.g. 183 Session Progress. It MUST send a 200 OK indicating that the party was successfully added. At this point the transferring PSAP MUST send a BYE to end its participation in the call. If the transferring PSAP receives an error code in the notification, e.g. 503 Service Unavailable, it MUST assume that the transfer did not occur and MUST not terminate the call. ",
        "document_section": "4.7.3",
        "description": "A REFER implicitly establishes a subscription to the 'refer' event. Once acknowledged with a 200 OK, the recipient sends status updates, concluding with a 200 OK for a successful add. A transferring PSAP must then send a BYE or, if an error is received, must not terminate the call.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_117": {
        "requirement_text": 'If the B2BUA receives an INVITE from a caller that does not include a Supported header field containing the "replaces" option-tag, it MUST include a Supported header field containing the "replaces" option-tag in the INVITE forwarded to the ESInet and provide the functionality described in this section.',
        "document_section": "4.7.1",
        "description": "If a B2BUA receives an INVITE without the 'replaces' option-tag in the Supported header, it must add the 'replaces' option-tag to the Supported header in the INVITE it forwards to the ESInet and provide the associated functionality.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_118": {
        "requirement_text": "It MUST send a 200 OK indicating that the party was successfully added.",
        "document_section": "4.7.2",
        "description": "The element must send a 200 OK response to indicate that a party was successfully added to the call/session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_119": {
        "requirement_text": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order when a queue of calls is waiting for service at the proxy server and, when needed, preempt lower priority calls",
        "document_section": "3.1.7",
        "description": 'SIP proxy servers must use Resource-Priority to process queued calls in priority order and preempt lower-priority calls when necessary.("Duplicate of RQ_BCF_004")',
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_120": {
        "requirement_text": "MediaStartLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the MediaStartLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_121": {
        "requirement_text": 'NonRtpMediaMessageLogEvent: An element MUST always log messages it receives (with "direction" set to "incoming").',
        "document_section": "4.12.3.7",
        "description": "An element must always log incoming messages using NonRtpMediaMessageLogEvent with the 'direction' parameter set to 'incoming'.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_122": {
        "requirement_text": "NonRtpMediaMessageLogEvent: An element MUST log outgoing messages it originates.",
        "document_section": "4.12.3.7",
        "description": "An element must log all outgoing non-RTP media messages it originates using the NonRtpMediaMessageLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_123": {
        "requirement_text": "NonRtpMediaMessageLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the NonRtpMediaMessageLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_124": {
        "requirement_text": "MediaEndLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the MediaEndLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_125": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_126": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_127": {
        "requirement_text": "ElementStateChangeLogEvent: When an element sends a notification of state change as described in the Element State section of this document, it MUST log the ElementStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When an element sends a notification of a state change, it must log the event using the ElementStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_128": {
        "requirement_text": 'CallSignalingMessageLogEvent: An element MUST always log messages it receives (with "direction" set to "incoming").',
        "document_section": "4.12.3.7",
        "description": "An element must always log messages it receives using CallSignalingMessageLogEvent, with the 'direction' parameter set to 'incoming'.",
        "test_id": "BCF_007",
        "subtests": [],
    },
    "RQ_BCF_129": {
        "requirement_text": "CallSignalingMessageLogEvent: An element MUST log outgoing messages it originates.",
        "document_section": "4.12.3.7",
        "description": "An element must log all outgoing messages it originates using the CallSignalingMessageLogEvent.",
        "test_id": "BCF_005",
        "subtests": [
            "Validate Log Event depends on SIP MESSAGE",
            "Validate Log Event depends on SIP Other message type",
            "Validate Log Event direction values",
        ],
    },
    "RQ_BCF_130": {
        "requirement_text": "CallSignalingMessageLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the CallSignalingMessageLogEvent.",
        "test_id": "BCF_005",
        "subtests": [],
    },
    "RQ_BCF_131": {
        "requirement_text": "MalformedMessageLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the MalformedMessageLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_132": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services",
        "document_section": "4.12.1",
        "description": "Clients of the Logging Service must support logging to at least two Logging Services for redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_133": {
        "requirement_text": "ServiceStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ServiceStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_134": {
        "requirement_text": "ServiceStateChangeLogEvent: When a Service sends a notification of state change as described in the Service State section of this document, which includes Security Posture, it MUST log the ServiceStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When a Service notifies of a state change, including security posture, it must log the event using the ServiceStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_135": {
        "requirement_text": "All agencies and NG9 1 1 functional elements MUST have access to a conformant Logging Service and log all relevant events in that service.",
        "document_section": "4.12.4",
        "description": "All agencies and NG9-1-1 functional elements must have access to and log all relevant events in a conformant Logging Service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_136": {
        "requirement_text": "Each element that is call stateful logs the beginning and end of its processing of a call, including non-interactive calls, with Start Call and End Call events. Elements that log CallStartLogEvent/CallEndLogEvent MUST also log the actual SIP message with CallSignalingMessageLogEvent for SIP parts of a call and GatewayCallLogEvent for TDM parts of a call. For CallStartLogEvent and CallEndLogEvent, the Timestamp MUST be the time the INVITE, MESSAGE, BYE or equivalents to these messages, or the final status code was received or sent by the element logging the event. ",
        "document_section": "4.12.3.7",
        "description": "Call-stateful elements must log CallStart and CallEnd events for processing a call. They must also log the actual SIP message using CallSignalingMessageLogEvent, and the timestamp must be the time the INVITE, BYE, or equivalent message/status code was received or sent.",
        "test_id": "BCF_007",
        "subtests": [],
    },
    "RQ_BCF_137": {
        "requirement_text": "CallStartLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the CallStartLogEvent.",
        "test_id": "BCF_007",
        "subtests": [],
    },
    "RQ_BCF_138": {
        "requirement_text": "CallEndLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the CallEndLogEvent.",
        "test_id": "BCF_007",
        "subtests": [],
    },
    "RQ_BCF_139": {
        "requirement_text": "RecMediaStartLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the RecMediaStartLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_140": {
        "requirement_text": "RecordingFailedLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the RecordingFailedLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_141": {
        "requirement_text": "ElementStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ElementStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_142": {
        "requirement_text": "(common LogEvent prologue (base object/header) table)",
        "document_section": "4.12.3.1",
        "description": "Refers to the table defining the common prologue (base object/header) for all LogEvents.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_143": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "KeepAliveFailureLogEvent must log malformed, invalid, or missing responses in the 'responseStatus' member, including text and a status code from the Status Codes Registry, such as 'TimeOut' for OPTIONS failures.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_144": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_145": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients of the Logging Service must support logging to at least two Logging Services for redundancy purposes.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_146": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations must use TLS for integrity protection, with SHA-256 or stronger. SHA-256 must be supported by all implementations.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_147": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations must use TLS for integrity protection, with SHA-256 or stronger. SHA-256 must be supported by all implementations.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_148": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations must be privacy protected via TLS, using at least AES-256 encryption. Shorter key lengths are forbidden, and legacy systems must be upgraded to at least AES-256.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_149": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "KeepAliveFailureLogEvent must log malformed, invalid, or missing responses in the 'responseStatus' member, including text and a status code from the Status Codes Registry, such as 'TimeOut' for OPTIONS failures.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_150": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_151": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations must use TLS for integrity protection, with SHA-256 or stronger. SHA-256 must be supported by all implementations.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_152": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients of the Logging Service must support logging to at least two Logging Services for redundancy purposes.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_153": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations must be privacy protected via TLS, using at least AES-256 encryption. Shorter key lengths are forbidden, and legacy systems must be upgraded to at least AES-256.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_154": {
        "requirement_text": "FEs that use a Logging Service MUST NOT depend on a Logging Service accepting an extension to provide services conformant to this document.",
        "document_section": "4.12.3.1",
        "description": "Functional elements (FEs) using a Logging Service must not rely on the service accepting an extension to provide compliant services.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_155": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services must be capable of verifying the signature of a signed LogEvent before responding. A failed verification returns a 'Signature Verification Failed' warning, but the LogEvent must still be recorded, and the client should not retry the request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_156": {
        "requirement_text": "(LogEvents POST parameters)",
        "document_section": "4.12.3.1.2",
        "description": "Refers to the parameters required for a LogEvents POST request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_157": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services must be capable of verifying the signature of a signed LogEvent before responding. A failed verification returns a 'Signature Verification Failed' warning, but the LogEvent must still be recorded, and the client should not retry the request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_158": {
        "requirement_text": "RecCallStartLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the RecCallStartLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_159": {
        "requirement_text": "RecCallEndLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the RecCallEndLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_160": {
        "requirement_text": "MessageLogEvent states: Elements that log Message MUST also log the actual SIP message with CallSignalingMessageLogEvent.",
        "document_section": "",
        "description": "Elements that log a MessageLogEvent must also log the actual SIP message content using a CallSignalingMessageLogEvent.",
        "test_id": "BCF_005",
        "subtests": [
            "Validate Log Event depends on SIP MESSAGE",
            "Validate Log Event depends on SIP Other message type",
        ],
    },
    "RQ_BCF_161": {
        "requirement_text": "MessageLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the MessageLogEvent.",
        "test_id": "BCF_005",
        "subtests": [
            "Validate Log Event depends on SIP MESSAGE",
            "Validate Log Event depends on SIP Other message type",
        ],
    },
    "RQ_BCF_162": {
        "requirement_text": "MessageLogEvent: Elements that log Message MUST also log the actual SIP message with CallSignalingMessageLogEvent.",
        "document_section": "4.12.3.7",
        "description": "Elements that log a MessageLogEvent must also log the actual SIP message content using a CallSignalingMessageLogEvent.",
        "test_id": "BCF_005",
        "subtests": [
            "Validate Log Event depends on SIP MESSAGE",
            "Validate Log Event depends on SIP Other message type",
        ],
    },
    "RQ_BCF_163": {
        "requirement_text": "All forms of media described in this document MUST be logged (see the Media section for details)",
        "document_section": "4.12",
        "description": "All forms of media described in this document are required to be logged.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_164": {
        "requirement_text": "VersionsLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the VersionsLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_165": {
        "requirement_text": "VersionsLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the VersionsLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_166": {
        "requirement_text": "Elements that implement the SRC interface MUST be capable of supporting redundant implementations of the SRS (RFC 7866) [116] and MUST insert the Call Identifier and Incident Tracking Identifier (Call-Info header fields) defined in this document into the INVITE sent to the Logging Service.",
        "document_section": "4.12.2",
        "description": "SRC-implementing elements must support redundant SRS implementations and include the Call Identifier and Incident Tracking Identifier in the INVITE sent to the Logging Service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_167": {
        "requirement_text": "When an SRC sends SIPREC Metadata, it MUST generate a SiprecMetadata LogEvent to the Logging Service.",
        "document_section": "4.12.2",
        "description": "When a Session Recording Client (SRC) sends SIPREC Metadata, it must generate an accompanying SiprecMetadata LogEvent to the Logging Service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_168": {
        "requirement_text": "The SRC MUST include the CallId and IncidentId for the emergency call being recorded in the SIPREC INVITE it generates and when generating an associated SiprecMetadata LogEvent.",
        "document_section": "4.12.2",
        "description": "The SRC must include the CallId and IncidentId for the emergency call in both the generated SIPREC INVITE and the associated SiprecMetadata LogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_169": {
        "requirement_text": "Elements that implement the SRC interface MUST be capable of supporting redundant implementations of the SRS (RFC 7866) [116]",
        "document_section": "4.12.2",
        "description": "Elements that implement the SRC interface must be capable of supporting redundant implementations of the Session Recording Server (SRS).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_170": {
        "requirement_text": "SRCs MUST support recording of media to at least two SRSes.",
        "document_section": "4.12.2",
        "description": "Session Recording Clients (SRCs) must support recording of media to a minimum of two Session Recording Servers (SRSes) for redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_171": {
        "requirement_text": "All SRCs and SRSes MUST implement RTCP on the recording session.",
        "document_section": "4.12.2",
        "description": "All Session Recording Clients (SRCs) and Session Recording Servers (SRSes) must implement RTCP for the recording session.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_172": {
        "requirement_text": "The SRC MUST send wall clock time in sender reports.",
        "document_section": "4.12.2",
        "description": "The Session Recording Client (SRC) must include the wall clock time when sending RTCP sender reports.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_173": {
        "requirement_text": "All Bridge elements (Section 5.7), Gateway elements (Section 7), BCF elements that anchor media, and PSAP Call Handling elements, MUST implement the SRC interface.",
        "document_section": "4.12.2",
        "description": "Bridge, Gateway, media-anchoring BCF, and PSAP Call Handling elements must all implement the Session Recording Client (SRC) interface.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_174": {
        "requirement_text": "The call MUST still be recorded while the third party is being added as well as when all three parties are on the call.",
        "document_section": "4.12.2.2",
        "description": "The emergency call must be continuously recorded during the process of adding a third party and while all three parties are connected.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_175": {
        "requirement_text": "The call MUST still be recorded by the SRC.",
        "document_section": "4.12.2.5",
        "description": "The call must continue to be recorded by the Session Recording Client (SRC).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_176": {
        "requirement_text": "The Logging Recorder MUST be able to provide a clean shut down by sending a BYE as specified in Section 3.1.1.3, for example when one SRS in a redundant pair is going out of service. The SRC MUST respond with a 200 OK.",
        "document_section": "4.12.2.6",
        "description": "The Logging Recorder must be able to perform a clean shutdown by sending a BYE, and the SRC must respond with a 200 OK.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_177": {
        "requirement_text": "Any element inside a PSAP that provides a call queue MUST deploy an ElementState notifier as described in Section 2.4.1.",
        "document_section": "4.6.6",
        "description": "Any element within a PSAP that manages a call queue must deploy an ElementState notifier as described in Section 2.4.1.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_178": {
        "requirement_text": "The PSAP MUST implement an NTP client interface for time of day information.",
        "document_section": "4.6.16",
        "description": "The PSAP must implement an NTP client interface to synchronize with time of day information.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_180": {
        "requirement_text": "The services, unless specified otherwise, MUST support HTTP/1.1 (RFC 7230) [162] and SHOULD support HTTP/2.0 (RFC 7540) [197].",
        "document_section": "2.8.1",
        "description": "Services must support HTTP/1.1 and should also support HTTP/2.0, unless an exception is specified.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_181": {
        "requirement_text": "Clients MUST appropriately handle all status codes listed for each supported entry point, and MUST react appropriately to other status codes received, based on the first digit as per RFC 7231 [223] Section 6.",
        "document_section": "2.8.2",
        "description": "Clients must appropriately handle all listed status codes for supported entry points and react to all other status codes based on the first digit, as per RFC 7231, Section 6.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_182": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand",
        "document_section": "2.8.3",
        "description": "Implementations are required to ignore any elements within data structures that they do not understand.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_183": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand and MUST return 404 errors to entry points to the web interfaces they don't provide as a server.",
        "document_section": "2.8.3",
        "description": "Implementations must ignore unknown elements in data structures and return a 404 error for web interface entry points they do not provide as a server.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_184": {
        "requirement_text": "Clients MUST retry transactions on redundant elements that that could not be completed on the initial element.",
        "document_section": "2.9",
        "description": "Clients must retry failed transactions on redundant elements if the initial element could not complete them.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_185": {
        "requirement_text": "Every implementation MUST be capable of using a DNS based implementation of redundant elements where more than one address may be returned for the URI provided.",
        "document_section": "2.9",
        "description": "All implementations must be capable of using a DNS-based approach for redundant elements where multiple addresses are returned for a single URI.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_186": {
        "requirement_text": "Implementations MUST be capable of preferring the first returned address, and using the second, third and optionally additional addresses returned as representing redundant elements for the service.",
        "document_section": "2.9",
        "description": "Implementations must prefer the first address returned but be capable of using subsequent addresses as redundant elements for the service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_187": {
        "requirement_text": "Other mechanisms to achieve redundancy MAY be provided, but the DNS based mechanism MUST be supported by all services and clients of those services.",
        "document_section": "2.9",
        "description": "While other redundancy mechanisms are optional, all services and clients must support the DNS-based mechanism for redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_188": {
        "requirement_text": "All SIP elements in an ESInet/NGCS MUST support multipart MIME as defined in RFC 2046 [90]",
        "document_section": "3.1.12",
        "description": "All SIP elements in an ESInet/NGCS must support multipart MIME format, as specified in RFC 2046.",
        "test_id": "BCF_008",
        "subtests": [],
    },
    "RQ_BCF_189": {
        "requirement_text": "All SIP elements in the NGCS MUST allow all mime types/body parts to pass to the PSAP",
        "document_section": "3.1.12",
        "description": "All SIP elements within the NGCS must allow every mime type and body part to pass through to the PSAP.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_190": {
        "requirement_text": "all SIP elements within the NGCS MUST support connection reuse, RFC 5923 [217].",
        "document_section": "3.1.13",
        "description": "All SIP elements within the NGCS must support the connection reuse mechanism defined in RFC 5923.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_191": {
        "requirement_text": "all SIP elements MUST implement the overload control mechanisms described in RFC 7339 [56].",
        "document_section": "3.1.17",
        "description": "All SIP elements must implement the overload control mechanisms detailed in RFC 7339.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_192": {
        "requirement_text": "All elements in an ESInet that implement SIP interfaces MUST comply with RFC 5626 [42] (Outbound) to maintain connections from User Agents.",
        "document_section": "3.1.18",
        "description": "All ESInet elements with SIP interfaces must comply with RFC 5626 (Outbound) to maintain connections from User Agents.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_193": {
        "requirement_text": 'PSAPs, IMRs, bridges and other elements that terminate calls from entities outside an ESInet that may be behind NATs MUST implement "Interactive Connectivity Establishment (ICE)", RFC 8445 [44] which includes support for "Session Traversal Utilities for NAT (STUN), RFC 5389 [83].',
        "document_section": "3.1.18",
        "description": "Elements terminating external calls that may be behind NATs (like PSAPs and IMRs) must implement Interactive Connectivity Establishment (ICE), which includes support for STUN.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_194": {
        "requirement_text": "All endpoints in an ESInet/NGCS MUST use ACK.",
        "document_section": "3.1.2.4",
        "description": "All endpoints within an ESInet/NGCS are required to use the SIP ACK method.",
        "test_id": "BCF_006",
        "subtests": [],
    },
    "RQ_BCF_195": {
        "requirement_text": "The PRACK method MUST be used within systems that need reliable provisional responses (non 100)",
        "document_section": "3.1.2.5",
        "description": "The PRACK method is mandatory in systems that require reliable provisional SIP responses (any response other than 100).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_196": {
        "requirement_text": "ESInet elements MUST allow MESSAGE requests in the context of a dialog initiated by some other SIP request.",
        "document_section": "3.1.2.6",
        "description": "ESInet elements must permit SIP MESSAGE requests to occur within the context of a dialog that was started by a different SIP request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_197": {
        "requirement_text": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order when a queue of calls is waiting for service at the proxy server and, when needed, preempt lower priority calls",
        "document_section": "3.1.7",
        "description": "SIP proxy servers must use Resource-Priority to process queued calls in priority order and preempt lower-priority calls when necessary.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_198": {
        "requirement_text": "All SIP user agents that place calls within the ESInet/NGCS MUST be able to set Resource-Priority.",
        "document_section": "3.1.7",
        "description": "All SIP user agents originating calls within the ESInet/NGCS must have the capability to set the Resource-Priority header.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_199": {
        "requirement_text": "When location is passed by value, processing elements along the path MUST NOT change the location record.",
        "document_section": "3.2",
        "description": "When location information is passed directly by value, no processing element along the call path is permitted to alter the location record.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_200": {
        "requirement_text": "NGCS that receive a location reference and forward location in SIP signaling to another element MUST pass the reference, and not any value that they determine by de- referencing (although the value should be logged).",
        "document_section": "3.2",
        "description": "NGCS elements receiving a location reference and forwarding it in SIP signaling must pass the reference itself, not a dereferenced value (though the dereferenced value should be logged).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_201": {
        "requirement_text": "The functional elements described in this document MUST support the discrepancy report (DR) function.",
        "document_section": "3.7",
        "description": "All functional elements described in this document must be capable of supporting the discrepancy report (DR) function.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_203": {
        "requirement_text": 'Implementations MUST support (be capable of generating and using) algorithm "EdDSA" and MUST NOT use other algorithms except that implementations of the Logging Service and clients of the Logging Service MUST support (be capable of generating and using) unsigned (algorithm "none")',
        "document_section": "5.10",
        "description": "Implementations must support the 'EdDSA' algorithm for generation and use, and only Logging Service and its clients must also support the unsigned 'none' algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_204": {
        "requirement_text": 'If a Web Service request receives an "Unacceptable Algorithm" error, the client MUST make a new request on the Versions entry point and retry the request with a JWS that uses a signing algorithm acceptable to the Web Service.',
        "document_section": "5.10",
        "description": "If a Web Service request returns an 'Unacceptable Algorithm' error, the client must check the Versions entry point and retry the request using a JWS with an acceptable signing algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_205": {
        "requirement_text": 'When this document indicates that a set of Web Service interface parameters is a JWS (e.g., for LogEvents), the set of parameters is conveyed in the web service request as a string consisting of a JWS. The JWS is formed by applying the JWS algorithm to the set of parameters per the JWS standard [171]. The JWS Protected Header MUST contain exactly one "alg" field. The "alg" field MUST have a value acceptable to the Web Service. An unsigned (unprotected) JWS is indicated by an "alg" field set to the value "none". For signed LogEvents, and all other uses of JWS requiring signatures (e.g., policy documents), the JWS Protected Header MUST have its "alg" field set to a value acceptable to the Web Service that MUST NOT be "none" and MUST specify the signing entity \'s X.509 certificate and all intermediate certificates up to one signed by the trusted root58. The certificate is provided either by reference or by value. A certificate provided by value is contained in an "x5c" field. A certificate is provided by reference using the "x5u" and "x5t#256" fields. When the "x5u" field is present, it MUST contain a URL that is stable (resolvable) for a minimum of 10 years. The JWS Protected Header MAY contain other fields. Including a certificate (with chain) in each LogEvent increases the size of the event (in some cases by a multiple of the event size) but avoids the additional network requests necessary to retrieve the certificate chain using the "x5u" field. When the "x5u" field is used, the "x5t#256" field MUST also be used, to allow an entity to more easily detect when a certificate chain needs to be retrieved.',
        "document_section": "5.10",
        "description": "Web Service parameters, such as for LogEvents, are conveyed as a JWS string with an acceptable 'alg' field in the Protected Header. Signed LogEvents must use a non-'none' algorithm and include the signing entity's X.509 certificate, either by value ('x5c') or by reference ('x5u' and 'x5t#256').",
        "test_id": "",
        "subtests": [],
    },
    "RQ_BCF_206": {
        "requirement_text": 'a JWS MUST use the Flat JSON serialization format (not JWS Compact Serialization and not General JWS JSON Serialization Syntax), and only the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448 (algorithm "EdDSA") [227] [228] signature method is used.',
        "document_section": "5.10",
        "description": "A JWS must use the Flat JSON serialization format. The only permitted signature method is the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448, identified by the 'EdDSA' algorithm.",
        "test_id": "",
        "subtests": [],
    },
    # "RQ_BCF_916": {
    #     "requirement_text": "packetHeader (For InitialTrafficBlocked, MidTrafficBlocked, TrafficNotBlockedBadActor, TrafficNotBlocked, or Firewall, contains the packet’s header, encoded using base64)",
    #     "document_section": "3.7.6",
    #     "description": "The \" packetHeader\" contains the packet's header encoded in base64 for certain issues.",
    #     "test_id": "",
    #     "subtests": []
    # },
    # "RQ_BCF_917": {
    #     "requirement_text": "The Resolution parameter in a BCF DiscrepancyResolution report contains one of the following tokens:",
    #     "document_section": "3.7.6",
    #     "description": "The \" Resolution\" parameter in the DiscrepancyResolution report can be \" DiscrepancyCorrected.\" ",
    #     "test_id": "BCF_002",
    #     "subtests": []
    # },
    # "RQ_BCF_921": {
    #     "requirement_text": "OtherResponse",
    #     "document_section": "3.7.6",
    #     "description": "\" OtherResponse\" refers to responses not covered by predefined categories.",
    #     "test_id": "",
    #     "subtests": []
    # },
    # "RQ_BCF_945": {
    #     "requirement_text": "To facilitate this notification, the BCF SHALL insert a Call-Info header field with a purpose parameter of “emergency-source” in the outgoing INVITE message associated with every call.",
    #     "document_section": "4.1.2",
    #     "description": "The BCF must insert a Call-Info header with an \" emergency-source\" parameter in every outgoing INVITE message.",
    #     "test_id": "",
    #     "subtests": []
    # },
    # "RQ_BCF_946": {
    #     "requirement_text": "calls MUST be marked by the SBC component in a way that allows the recipient to identify the BCF that processed the call. The source-ID is formatted as follows: <unique source-id>@<domain name of BCF> (e.g., “a7123gc42@sbc22.example.net”).",
    #     "document_section": "4.1.2",
    #     "description": "Calls must be marked with a source-ID to identify the BCF that processed the call.",
    #     "test_id": "",
    #     "subtests": []
    # },
    # "RQ_BCF_947": {
    #     "requirement_text": "The notification MUST be propagated to all such SBCs. The mechanism for doing so is not specified.",
    #     "document_section": "4.1.2",
    #     "description": "Notifications of bad actors must be propagated to all relevant SBCs, though the mechanism is unspecified.",
    #     "test_id": "",
    #     "subtests": []
    # },
}
