REQUIREMENTS_SCHEMA = {
    "RQ_ESRP_001": {
        "requirement_text": "If the call arrives at an ESRP with no queue name or a queue name that the ESRP does not implement, the ESRP SHALL use a provisioned default queue for the call.",
        "document_section": "4.2.1.1",
        "description": "If the call arrives at an ESRP with no queue name or a queue name that the ESRP does not implement, the ESRP must use a provisioned default queue for the call",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_002": {
        "requirement_text": "A call sent to the queue URI MUST route to the entity that manages it.",
        "document_section": "4.2.1.2",
        "description": "A call sent to the queue URI MUST route to the entity that manages it",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_003": {
        "requirement_text": "Each queue MUST have a unique URI that routes to the ESRP.",
        "document_section": "4.2.1.2",
        "description": "Each queue MUST have a unique URI that routes to the ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_004": {
        "requirement_text": "Each ESRP element SHALL maintain a QueueState notifier and track the number of calls in queue for the queues that it manages.",
        "document_section": "4.2.1.2",
        "description": "Each ESRP element SHALL maintain a QueueState notifier and track the number of calls in queue for the queues that it manages",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_005": {
        "requirement_text": "Changing the ServiceState MUST change the state of all Queues implemented by the Service to an appropriate QueueState (for example if ServiceState is set to Unstaffed, underlying QueueState values become Disabled).",
        "document_section": "4.2.1.2",
        "description": "Changing the ServiceState MUST change the state of all Queues implemented by the Service to an appropriate QueueState",
        "test_id": "ESRP_001",
        "subtests": [],
    },
    "RQ_ESRP_006": {
        "requirement_text": "The registry includes the value “unreachable”, which MUST NOT be returned in a NOTIFY.",
        "document_section": "4.2.1.3",
        "description": "The value 'unreachable' is in the registry but is strictly forbidden from being used or returned in a NOTIFY message.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_007": {
        "requirement_text": "QueueState MUST reflect the state of the (ESRP or PSAP) service state.",
        "document_section": "4.2.1.3",
        "description": "QueueState MUST reflect the state of the",
        "test_id": "ESRP_001",
        "subtests": [],
    },
    "RQ_ESRP_008": {
        "requirement_text": "If the ESRP is down, all of its queues MUST show a state matching the reason the service is not available.",
        "document_section": "4.2.1.3",
        "description": "If the ESRP is down, all of its queues MUST show a state matching the reason the service is not available",
        "test_id": "ESRP_001",
        "subtests": [],
    },
    "RQ_ESRP_011": {
        "requirement_text": "An ESRP that dequeues a call, sends it to a downstream entity, and receives a 486 Busy Here in return, MUST continue evaluating the existing rule set per Section 3.3.3.2.1.",
        "document_section": "4.2.1.3",
        "description": "An ESRP that dequeues a call, sends it to a downstream entity, and receives a 486 Busy Here in return, MUST continue evaluating the existing rule set per Section 3.3.3.2.1",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_014": {
        "requirement_text": "When dequeueing calls, the ESRP MUST send calls to the highest DequeuePreference entity available to take the call when it reaches the head of the queue.",
        "document_section": "4.2.1.4",
        "description": "When dequeueing calls, the ESRP MUST send calls to the highest DequeuePreference entity available to take the call when it reaches the head of the queue",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_016": {
        "requirement_text": "Handling of Forked Requests: Forking between elements MUST NOT be used.",
        "document_section": "4.2.1.6",
        "description": "Handling of Forked Requests: Forking between elements is strictly forbidden",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_017": {
        "requirement_text": "Each ESRP MUST be capable of receiving location as a value or a reference and MUST be provisioned with credentials suitable to present to any LIS in its service area to be able to dereference a location reference using either SIP or HELD.",
        "document_section": "4.2.1.7",
        "description": "Each ESRP must be able to receiving location as a value or a reference and MUST be provisioned with credentials suitable to present to any LIS in its service area to be able to dereference a location reference using either SIP or HELD",
        "test_id": "ESRP_002",
        "subtests": [],
    },
    "RQ_ESRP_018": {
        "requirement_text": "The ESRP MUST be able to handle emergency calls with problems in location.",
        "document_section": "4.2.1.7",
        "description": "The ESRP must be able to handle emergency calls with problems in location",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_019": {
        "requirement_text": "In all such cases the ESRP MUST determine a suitable LVF-valid default location to use to route a call with location problems, as part of the LoSTServiceURN condition processing.",
        "document_section": "4.2.1.7",
        "description": "In all such cases the ESRP MUST determine a suitable LVF-valid default location to use to route a call with location problems, as part of the LoSTServiceURN condition processing",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_020": {
        "requirement_text": "In other words, the ESRP MUST ensure the pre-conditions as are always there for the LoSTServiceURN condition to be evaluated successfully.",
        "document_section": "4.2.1.7",
        "description": "In other words, the ESRP MUST ensure the pre-conditions as are always there for the LoSTServiceURN condition to be evaluated successfully",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_021": {
        "requirement_text": 'A PIDF-LO containing a Default Location MUST have its <method> element set to the value "Default" , and its <provided-by> element set to the identity of the NGCS provider that inserted it',
        "document_section": "4.2.1.7",
        "description": "A PIDF-LO containing a Default Location MUST have its <method> element set to the value 'Default' , and its <provided-by> element set to the identity of the NGCS provider that inserted it",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_022": {
        "requirement_text": "The location elements MUST be populated to a level that yields an appropriate route URI in the LoST response from the ECRF.",
        "document_section": "4.2.1.7",
        "description": "The location elements MUST be populated to a level that yields an appropriate route URI in the LoST response from the ECRF",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_023": {
        "requirement_text": "The ESRP SHALL perform the following procedures when handling a default location:",
        "document_section": "4.2.1.7",
        "description": "The ESRP must perform the following procedures when handling a default location:",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_024": {
        "requirement_text": "The ESRP SHALL preserve the original Geolocation header field values and PIDF-LO documents in the original INVITE;",
        "document_section": "4.2.1.7",
        "description": "The ESRP must preserve the original Geolocation header field values and PIDF-LO documents in the original INVITE;",
        "test_id": "ESRP_003",
        "subtests": [
            "Keeping original 'Geolocation' header field.",
            "Keeping original message bodies.",
        ],
    },
    "RQ_ESRP_025": {
        "requirement_text": 'If there is no Geolocation header field, the ESRP SHALL add the default location PIDF-LO document in the body of the INVITE (to do so, the ESRP MUST behave as a B2BUA), and add a Geolocation header field populated with a "cid" URI pointing to it;',
        "document_section": "4.2.1.7",
        "description": "If there is no Geolocation header field, the ESRP SHALL add the default location PIDF-LO document in the body of the INVITE",
        "test_id": "ESRP_003",
        "subtests": [
            "Adding default PIDF-LO.",
            "Adding 'Geolocation' pointing to default PIDF-LO.",
        ],
    },
    "RQ_ESRP_026": {
        "requirement_text": 'If the original INVITE contained a garbled PIDF-LO, the ESRP SHALL add a new body part with the default location PIDF-LO (to do so, the ESRP MUST behave as a B2BUA) and add a new Geolocation header field with a "cid" URI pointing to it as top-most entry of the Geolocation field sequence, retaining the garbled one;',
        "document_section": "4.2.1.7",
        "description": "If the original INVITE contained a garbled PIDF-LO, the ESRP SHALL add a new body part with the default location PIDF-LO",
        "test_id": "ESRP_003",
        "subtests": [
            "Adding default PIDF-LO.",
            "Adding 'Geolocation' pointing to default PIDF-LO.",
            "Adding 'Geolocation' as top-most entry in 'Geolocation' section.",
            "Keeping original 'Geolocation' header field.",
            "Keeping original message bodies.",
        ],
    },
    "RQ_ESRP_027": {
        "requirement_text": 'If the original INVITE contained a garbled location reference in the Geolocation header field, or the location dereferencing timed out or yielded a garbled PIDF-LO document, the ESRP SHALL add a new body part with the default location PIDF-LO document (to do so, the ESRP MUST behave as a B2BUA) and add a new Geolocation header field with a "cid" URI pointing to it as top-most entry of the Geolocation field sequence, retaining the garbled one;',
        "document_section": "4.2.1.7",
        "description": "If the original INVITE contained a garbled location reference in the Geolocation header field, or the location dereferencing timed out or yielded a garbled PIDF-LO document, the ESRP SHALL add a new body part with the default location PIDF-LO document",
        "test_id": "ESRP_003",
        "subtests": [
            "Adding default PIDF-LO.",
            "Adding 'Geolocation' pointing to default PIDF-LO.",
            "Adding 'Geolocation' as top-most entry in 'Geolocation' section.",
            "Keeping original 'Geolocation' header field.",
            "Keeping original message bodies.",
        ],
    },
    "RQ_ESRP_028": {
        "requirement_text": "Once the INVITE has been groomed with a usable location for routing, albeit a default one, the ESRP MUST reprocess the Origination-Policy rule, including the LoSTServiceURN condition.",
        "document_section": "4.2.1.7",
        "description": "Once the INVITE has been groomed with a usable location for routing, albeit a default one, the ESRP MUST reprocess the Origination-Policy rule, including the LoSTServiceURN condition",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_029": {
        "requirement_text": "If a default location is used to determine the route for the emergency call, the ESRP SHALL pass the location information received in incoming signaling forward in the outgoing SIP INVITE/MESSAGE.",
        "document_section": "4.2.1.7",
        "description": "If a default location is used to determine the route for the emergency call, the ESRP SHALL pass the location information received in incoming signaling forward in the outgoing SIP INVITE/MESSAGE",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_030": {
        "requirement_text": "Should no entity respond, the ESRP MUST reevaluate the ruleset with the rule which failed, interpreted as not satisfying its conditions.",
        "document_section": "4.2.1.7",
        "description": "Should no entity respond, the ESRP MUST reevaluate the ruleset with the rule which failed, interpreted as not satisfying its conditions",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_031": {
        "requirement_text": "Administrative calls do not have location, so they MUST be routed using a provisioned table in the ESRP that associates the called number or sip URI to a URI of a queue in the ESRP.",
        "document_section": "4.2.1.7",
        "description": "Administrative calls do not have location, so they MUST be routed using a provisioned table in the ESRP that associates the called number or sip URI to a URI of a queue in the ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_032": {
        "requirement_text": "An ESRP MUST process BYEs per RFC 3261 [10].",
        "document_section": "4.2.1.8",
        "description": "An ESRP must process BYEs per RFC 3261 [10]",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_033": {
        "requirement_text": "An ESRP MUST process CANCELs per RFC 3261.",
        "document_section": "4.2.1.9",
        "description": "An ESRP must process CANCELs per RFC 3261",
        "test_id": "ESRP_004",
        "subtests": [],
    },
    "RQ_ESRP_034": {
        "requirement_text": "An ESRP MUST process OPTIONS transactions per RFC 3261 [10].",
        "document_section": "4.2.1.10",
        "description": "An ESRP must process OPTIONS transactions per RFC 3261 [10]",
        "test_id": "ESRP_004",
        "subtests": [],
    },
    "RQ_ESRP_035": {
        "requirement_text": "If the downstream entity is not reachable, the ESRP MUST treat its queues as Inactive.",
        "document_section": "4.2.1.10",
        "description": "If the downstream entity is not reachable, the ESRP MUST treat its queues as Inactive",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_036": {
        "requirement_text": "The upstream SIP call interface for the originating ESRP must only assume the minimal methods and header fields as defined in Section 3.1.1, but MUST handle any valid SIP transaction.",
        "document_section": "4.2.2.1",
        "description": "The upstream SIP call interface for the originating ESRP must only assume the minimal methods and header fields as defined in Section 3.1.1, but MUST handle any valid SIP transaction",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_037": {
        "requirement_text": "All other ESRPs MUST handle all methods and SIP header fields.",
        "document_section": "4.2.2.1",
        "description": "All other ESRPs MUST handle all methods and SIP header fields",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_038": {
        "requirement_text": "The ESRP MUST respond to the URI returned by the ECRF and/or specified in a Route action for a rule for the upstream service the ESRP receives calls from.",
        "document_section": "4.2.2.1",
        "description": "The ESRP must respond to the URI returned by the ECRF and/or specified in a Route action for a rule for the upstream service the ESRP receives calls from",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_039": {
        "requirement_text": "The upstream interface on the originating ESRP MUST support UDP, TCP, and TCP/TLS and MAY support SCTP transports.",
        "document_section": "4.2.2.1",
        "description": "The upstream interface on the originating ESRP MUST support UDP, TCP, and TCP/TLS and MAY support SCTP transports",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_040": {
        "requirement_text": "The upstream interface on other ESRPs MUST implement TCP/TLS but MUST be capable of fallback to UDP.",
        "document_section": "4.2.2.1",
        "description": "The upstream interface on other ESRPs must implement TCP/TLS but must be able to fallback to UDP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_041": {
        "requirement_text": "The downstream SIP call interface MUST implement all SIP methods to be able to propagate any method invoked on the upstream call interface.",
        "document_section": "4.2.2.2",
        "description": "The downstream SIP call interface must implement all SIP methods to be able to propagate any method invoked on the upstream call interface",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_042": {
        "requirement_text": "The INVITE transaction exiting the ESRP MUST include a Via header field specifying the ESRP.",
        "document_section": "4.2.2.2",
        "description": "The INVITE transaction exiting the ESRP MUST include a Via header field specifying the ESRP",
        "test_id": "ESRP_006",
        "subtests": ["Adding 'Via' header field specifying ESRP"],
    },
    "RQ_ESRP_043": {
        "requirement_text": 'It MUST include a Route header field containing a URI (which should contain the "lr" parameter to avoid Request-URI rewriting) of the downstream queue that receives the call.',
        "document_section": "4.2.2.2",
        "description": "It MUST include a Route header field containing a URI (which should contain the 'lr' parameter to avoid Request-URI rewriting) of the downstream queue that receives the call.",
        "test_id": "ESRP_006",
        "subtests": [
            "Adding 'Route' header field with queue URI received from ECRF",
            "Added 'Route' header field contains 'lr' parameter",
        ],
    },
    "RQ_ESRP_044": {
        "requirement_text": 'The Request-URI remains "urn:service:sos"  (although the ESRP may not depend on that; a call presented to an ESRP that is not recognized as an emergency call, for example, a call to an admin line, MUST be treated as an emergency call and its occurrence logged) and it replaces the top Route header field with the next hop URI (this is described in RFC 6881 [46]).',
        "document_section": "4.2.2.2",
        "description": "The Request-URI remains 'urn:service:sos'",
        "test_id": "ESRP_006",
        "subtests": [],
    },
    "RQ_ESRP_045": {
        "requirement_text": 'Thus, the first ESRP in the path MUST add a Call-Info header field, if one is not already present, with a purpose parameter of "emergency-IncidentId" and a new Incident Tracking Identifier per Section 2.1.7.',
        "document_section": "4.2.2.2",
        "description": "Thus, the first ESRP in the path MUST add a Call-Info header field, if one is not already present, with a purpose parameter of 'emergency-IncidentId' and a new Incident Tracking Identifier per Section 2.1.7",
        "test_id": "ESRP_006",
        "subtests": [
            "Incident Tracking Identifier URN",
            "Incident Tracking Identifier String ID",
            "Incident Tracking Identifier FQDN",
            "Incident Tracking Identifier 'purpose' parameter",
        ],
    },
    "RQ_ESRP_046": {
        "requirement_text": 'The ESRP MUST also create a new Call identifier (Section 2.1.6) and add a Call-Info header field with a purpose parameter of "emergency-CallId" if one is not already present.',
        "document_section": "4.2.2.2",
        "description": "The ESRP must also create a new Call identifier (Section 2.1.6) and add a Call-Info header field with a purpose parameter of 'emergency-CallId' if one is not already present.",
        "test_id": "ESRP_006",
        "subtests": [
            "Emergency Call Identifier URN",
            "Emergency Call Identifier String ID",
            "Emergency Call Identifier FQDN",
            "Emergency Call Identifier 'purpose' parameter",
        ],
    },
    "RQ_ESRP_047": {
        "requirement_text": "The downstream interface MUST implement TCP/TLS towards downstream elements but MUST be capable of fallback to UDP.",
        "document_section": "4.2.2.2",
        "description": "The downstream interface must implement TCP/TLS towards downstream elements but must be able to fallback to UDP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_048": {
        "requirement_text": "An ESRP MAY NOT remove header fields received in the upstream call interface; all header fields in the upstream message MUST be copied to the downstream interface except as required in the relevant RFCs.",
        "document_section": "4.2.2.2",
        "description": "An ESRP MAY NOT remove header fields received in the upstream call interface; all header fields in the upstream message MUST be copied to the downstream interface except as required in the relevant RFCs",
        "test_id": "ESRP_006",
        "subtests": ["Keeping original header fields"],
    },
    "RQ_ESRP_049": {
        "requirement_text": "The ESRP MUST implement a LoST interface towards a (provisioned) ECRF.",
        "document_section": "4.2.2.3",
        "description": "The ESRP must implement a LoST interface towards a (provisioned) ECRF",
        "test_id": "ESRP_006",
        "subtests": ["'findService' contains geolocations from received SIP INVITE"],
    },
    "RQ_ESRP_050": {
        "requirement_text": "The ESRP MUST use a TCP/TLS transport and MUST be provisioned with the credentials for the ECRF.",
        "document_section": "4.2.2.3",
        "description": "The ESRP must use a TCP/TLS transport and MUST be provisioned with the credentials for the ECRF",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_051": {
        "requirement_text": 'Any URN in the "urn.service.sos" (and its urn:service:test.sos equivalents) or "urn:emergency.service.sos" tree MUST be supported by all ESRPs.',
        "document_section": "4.2.2.3",
        "description": "Any URN in the 'urn.service.sos'",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_052": {
        "requirement_text": 'The ESRP MUST use the ECRF interface with the "urn:emergency:service:additionaldata" service URN when accessing Additional Data associated with a location in the evaluation of a rule set that contains an Additional Data condition, as described in Section 4.2.2.5 Additional Data Interfaces.',
        "document_section": "4.2.2.3",
        "description": "The ESRP must use the ECRF interface with the 'urn:emergency:service:additionaldata' service URN when accessing Additional Data associated with a location in the evaluation of a rule set that contains an Additional Data condition, as described in Section 4.2.2.5 Additional Data Interfaces",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_053": {
        "requirement_text": "The ESRP MUST implement both SIP Presence Event Package and HELD dereferencing interfaces.",
        "document_section": "4.2.2.4",
        "description": "The ESRP must implement both SIP Presence Event Package and HELD dereferencing interfaces",
        "test_id": "ESRP_002",
        "subtests": [],
    },
    "RQ_ESRP_054": {
        "requirement_text": "The ESRP MUST use TCP/TLS for the LIS Dereferencing interface, with fallback to TCP (without TLS) on failure to establish a TLS connection.",
        "document_section": "4.2.2.4",
        "description": "The ESRP must use TCP/TLS for the LIS Dereferencing interface, with fallback to TCP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_055": {
        "requirement_text": "The ESRP MUST implement mechanisms for retrieving Additional Data (RFC 7852) [107].",
        "document_section": "4.2.2.5",
        "description": "The ESRP must implement mechanisms for retrieving Additional Data",
        "test_id": "ESRP_008",
        "subtests": [],
    },
    "RQ_ESRP_056": {
        "requirement_text": "The ESRP MUST be able to accommodate multiple additional data services and structures for the same call.",
        "document_section": "4.2.2.5",
        "description": "The ESRP must be able to accommodate multiple additional data services and structures for the same call",
        "test_id": "ESRP_013",
        "subtests": [],
    },
    "RQ_ESRP_057": {
        "requirement_text": "The ESRP MUST implement the client side of the ElementState and ServiceState event notification packages.",
        "document_section": "4.2.2.6",
        "description": "The ESRP must implement the client side of the ElementState and ServiceState event notification packages",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_058": {
        "requirement_text": "The ESRP MUST maintain Subscriptions for these packages on every downstream element/service it serves.",
        "document_section": "4.2.2.6",
        "description": "The ESRP must maintain Subscriptions for these packages on every downstream element/service it serves",
        "test_id": "ESRP_012",
        "subtests": [],
    },
    "RQ_ESRP_059": {
        "requirement_text": "The ESRP MUST implement the server-side of the ElementState event notification package and accept Subscriptions for all upstream ESRPs from which it expects to receive calls.",
        "document_section": "4.2.2.6",
        "description": "The ESRP must implement the server-side of the ElementState event notification package and accept Subscriptions for all upstream ESRPs from which it expects to receive calls",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_060": {
        "requirement_text": "The ESRP MUST promptly report changes in its state to its subscribed elements.",
        "document_section": "4.2.2.6",
        "description": "The ESRP must promptly report changes in its state to its subscribed elements",
        "test_id": "ESRP_012",
        "subtests": [],
    },
    "RQ_ESRP_061": {
        "requirement_text": "Any change in state that affects its ability to receive calls MUST be reported.",
        "document_section": "4.2.2.6",
        "description": "Any change in state that affects its ability to receive calls MUST be reported",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_062": {
        "requirement_text": "The set of ESRPs within an NGCS MUST implement the server-side of the ServiceState event notification package.",
        "document_section": "4.2.2.6",
        "description": "The set of ESRPs within an NGCS must implement the server-side of the ServiceState event notification package",
        "test_id": "ESRP_012",
        "subtests": [],
    },
    "RQ_ESRP_063": {
        "requirement_text": "The ESRP MUST maintain reliable time synchronization.",
        "document_section": "4.2.2.7",
        "description": "The ESRP must maintain reliable time synchronization",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_064": {
        "requirement_text": "The ESRP MUST implement a logging interface per Section 4.12.",
        "document_section": "4.2.2.8",
        "description": "The ESRP must implement a logging interface per Section 4.12",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_065": {
        "requirement_text": "The ESRP MUST be capable of logging every transaction and every message received and sent on its call interfaces, every query to the ECRF, and every state change it receives or sends.",
        "document_section": "4.2.2.8",
        "description": "The ESRP must log every transaction and message sent/received on its call interfaces, every query to the ECRF, and every state change it receives or sends.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_066": {
        "requirement_text": "It MUST be capable of logging the rule set it consulted, the rules found to be relevant to the route, and the route decision it made.",
        "document_section": "4.2.2.8",
        "description": "It must log the rule set it consulted, the rules found to be relevant to the route, and the final route decision.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_067": {
        "requirement_text": "They MUST send a NOTIFY downstream following the above process.",
        "document_section": "4.2.2.9",
        "description": "They MUST send a NOTIFY downstream following the above process",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_068": {
        "requirement_text": "Forking between elements MUST NOT be used.",
        "document_section": "4.2.2.9",
        "description": "Forking between elements is strictly forbidden",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_069": {
        "requirement_text": "The ESRP MUST invoke the STI-VS before applying the RoutePolicy ruleset for the queue the emergency calls arrives on.",
        "document_section": "4.2.2.10",
        "description": "The ESRP MUST invoke the STI-VS before applying the RoutePolicy ruleset for the queue the emergency calls arrives on",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_070": {
        "requirement_text": "The ESRP MUST have access to the appropriate RoutePolicy ruleset for every URI that the ECRF can return in response to a service query made by the ESRP (Normal-NextHop).",
        "document_section": "4.2.3",
        "description": "The ESRP MUST have access to the appropriate RoutePolicy ruleset for every URI that the ECRF can return in response to a service query made by the ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_071": {
        "requirement_text": "The ESRP MUST be provisioned with the policy store it uses. Use of an external Policy Store MUST be possible even if an implementation includes a Policy Store.",
        "document_section": "4.2.3",
        "description": "The ESRP MUST be provisioned with the policy store it uses. Use of an external Policy Store MUST be possible even if an implementation includes a Policy Store",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_072": {
        "requirement_text": "An ESRP may be operated by a State, Regional, or local 9 1 1 Authority. Downstream entities maintaining queues that upstream ESRPs queue calls on MUST supply a rule set for the upstream ESRP.",
        "document_section": "4.2.5",
        "description": "Downstream entities that maintain queues used by upstream ESRPs MUST supply a rule set for the upstream ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_073": {
        "requirement_text": "If a ruleset has no conditions that evaluate to 'true', the ESRP MUST treat this as a fatal error.",
        "document_section": "3.3.3.1",
        "description": "If a ruleset has no conditions that evaluate to 'true', the ESRP MUST treat this as a fatal error",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_074": {
        "requirement_text": 'The ESRP SHALL implement a Ring No Answer timer, which SHALL be set to the "rnaTimer" value if present, or the provisioned default if omitted.',
        "document_section": "3.3.3.2.1",
        "description": "The ESRP must implement a Ring No Answer timer, which must be set to the 'rnaTimer' value if present, or a provisioned default if omitted",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_075": {
        "requirement_text": 'A Route Action can fail for reasons other than Ring No Answer timeout (e.g., because the destination queue becomes unreachable, the next hop rejected the call with an error status, or the call times-out before it is answered). In such cases, the ESRP MUST set its queue state for the target queue to "Unreachable" and MUST reevaluate the ruleset for the call.',
        "document_section": "3.3.3.2.1",
        "description": "If a Route Action fails for reasons other than RNA timeout, the ESRP MUST set the target queue's state to 'Unreachable' and MUST reevaluate the ruleset for the call",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_076": {
        "requirement_text": "A routing element MUST verify the JWS signature before executing the rules.  If the JWS signature verification fails, the policy MUST NOT be executed.",
        "document_section": "3.3.3",
        "description": "A routing element MUST verify the JWS signature before executing the rules. If the JWS signature verification fails, the policy MUST NOT be executed",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_077": {
        "requirement_text": "The ECRF MUST be used within the ESInet to route calls to the correct PSAP, and by the PSAP to route calls to the correct responders.",
        "document_section": "4.3",
        "description": "The ECRF MUST be used within the ESInet to route calls to the correct PSAP, and by the PSAP to route calls to the correct responders",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_078": {
        "requirement_text": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order when a queue of calls is waiting for service at the proxy server and, when needed, preempt lower priority calls",
        "document_section": "3.1.7",
        "description": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order, preempting lower priority calls when needed",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_080": {
        "requirement_text": "These test calls MUST originate from within the ESInet and MUST come from an entity with credentials traceable to the PCA and trusted by the ESRP.",
        "document_section": "4.6.18",
        "description": "Test calls MUST originate from within the ESInet and MUST come from an entity with credentials traceable to the PCA and trusted by the ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_081": {
        "requirement_text": "These test calls MUST originate from within the ESInet and MUST come from an entity with credentials traceable to the PCA and trusted by the ESRP.",
        "document_section": "4.6.18",
        "description": "Test calls MUST originate from within the ESInet and MUST come from an entity with credentials traceable to the PCA and trusted by the ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_082": {
        "requirement_text": "The credentials used by the server MUST be traceable to the PCA and MUST occur in the ESRP policy.",
        "document_section": "4.6.18",
        "description": "The credentials used by the server MUST be traceable to the PCA and MUST occur in the ESRP policy",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_083": {
        "requirement_text": "The ESRP routes outbound calls based on an origination policy for a provisioned ESRP queue used for calls which would route to an OCIF.",
        "document_section": "4.2.1.1",
        "description": "The ESRP routes outbound calls based on an origination policy for a provisioned ESRP queue used for calls which would route to an OCIF",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_084": {
        "requirement_text": "The first time the ruleset is evaluated, the cause code SHALL be set to 1.",
        "document_section": "3.1.8",
        "description": "The first time the ruleset is evaluated, the cause code must be set to 1",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_085": {
        "requirement_text": "When cause codes 1-10 are used, the 'text' parameter MUST be present, and must start with the ruleId followed by a colon and any other clarifying text the implementation wishes to add.",
        "document_section": "3.1.8",
        "description": "When cause codes 1-10 are used, the 'text' parameter MUST be present, and must start with the ruleId followed by a colon and any other clarifying text",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_086": {
        "requirement_text": "If included in the call path, the ESRP SHALL route the outgoing call to the OCIF",
        "document_section": "4.20",
        "description": "If included in the call path, the ESRP must route the outgoing call to the OCIF",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_089": {
        "requirement_text": "History-Info  RFC 7044  MAY indicate the call has been retargeted, MUST include a Reason header field per section 3.1.8",
        "document_section": "3.1.5",
        "description": "History-Info MAY indicate the call has been retargeted, and MUST include a Reason header field per section 3.1.8",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_090": {
        "requirement_text": 'RFC 6442 [8] states "A SIP intermediary that adds a locationValue MUST position the new locationValue as the last locationValue within the Geolocation header field of the SIP request".',
        "document_section": "3.2",
        "description": "A SIP intermediary that adds a locationValue MUST position the new locationValue as the last locationValue within the Geolocation header field of the SIP request",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_091": {
        "requirement_text": "There are multiple references to the Geolocation header field in this document. These references MUST be interpreted to include the possibility of multiple location information.",
        "document_section": "3.2",
        "description": "References to the Geolocation header field MUST be interpreted to include the possibility of multiple location information",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_100": {
        "requirement_text": "NG9?1?1 elements that process 9?1?1 calls MUST accept calls that do not strictly follow the SIP standards. As long as the messages can be parsed, and the method discerned, at least the first SIP element (the BCF) MUST be able to accept the call and forward the call onward (see Section 4.1)  Support for the following SIP Methods is summarized and specified in the following table: (See underlying table)",
        "document_section": "3.1.1",
        "description": "NG9-1-1 elements that process 9-1-1 calls MUST accept calls that do not strictly follow the SIP standards, as long as the messages can be parsed and the method discerned",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_101": {
        "requirement_text": "Elements on an ESInet SHALL assume a SIP call entering the ESInet is an emergency call unless it can determine it is something else, such as a call to an administrative number. Even if the call does not have the emergency service URN in the Request-URI, the call SHOULD be assumed to be an emergency call and the Request-URI SHALL be rewritten to urn:service:sos by the BCF or originating ESRP.",
        "document_section": "3.1.7",
        "description": "Elements on an ESInet SHALL assume a SIP call entering the ESInet is an emergency call unless it can determine it is something else. If the emergency service URN is absent, the Request-URI SHALL be rewritten to urn:service:sos by the BCF or originating ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_102": {
        "requirement_text": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order when a queue of calls is waiting for service at the proxy server and, when needed, preempt lower priority calls",
        "document_section": "3.1.7",
        "description": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order, preempting lower priority calls when needed",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_103": {
        "requirement_text": "request (If the discrepancy concerns a dialog, the initial INVITE that initiated the dialog )",
        "document_section": "3.7.6",
        "description": "If the discrepancy concerns a dialog, the report must include the initial INVITE that initiated the dialog",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_104": {
        "requirement_text": "problem (One of the following tokens: InitialTrafficBlocked; MidTrafficBlocked; BadSDP; BadSIP; MediaLoss; TrafficNotBlockedBadActor; TrafficNotBlocked; QoS; BadCDR; TTY; Firewall; OtherBCF)",
        "document_section": "3.7.6",
        "description": "The discrepancy report must include a 'problem' token from the defined list (e.g., InitialTrafficBlocked, BadSIP, MediaLoss)",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_105": {
        "requirement_text": "sosSource (The emergency-source parameter of the dialog request (i.e., the initial INVITE))",
        "document_section": "3.7.6",
        "description": "The discrepancy report must include the 'sosSource' parameter from the initial INVITE of the dialog request",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_106": {
        "requirement_text": "EventTimestamp (Timestamp of event being reported)",
        "document_section": "3.7.6",
        "description": "The discrepancy report must include the EventTimestamp (Timestamp of event being reported)",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_107": {
        "requirement_text": "packetHeader (For InitialTrafficBlocked, MidTrafficBlocked, TrafficNotBlockedBadActor, TrafficNotBlocked, or Firewall, contains the packet's header, encoded using base64)",
        "document_section": "3.7.6",
        "description": "For traffic-related issues, the discrepancy report must include the packet's header, encoded using base64",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_108": {
        "requirement_text": "packetHeader (For InitialTrafficBlocked, MidTrafficBlocked, TrafficNotBlockedBadActor, TrafficNotBlocked, or Firewall, contains the packet's header, encoded using base64)",
        "document_section": "3.7.6",
        "description": "For traffic-related issues, the discrepancy report must include the packet's header, encoded using base64",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_109": {
        "requirement_text": "Elements on an ESInet SHALL assume a SIP call entering the ESInet is an emergency call unless it can determine it is something else, such as a call to an administrative number. Even if the call does not have the emergency service URN in the Request-URI, the call SHOULD be assumed to be an emergency call and the Request-URI SHALL be rewritten to urn:service:sos by the BCF or originating ESRP.",
        "document_section": "3.1.7",
        "description": "Elements on an ESInet SHALL assume a SIP call entering the ESInet is an emergency call unless it can determine it is something else. If the emergency service URN is absent, the Request-URI SHALL be rewritten to urn:service:sos by the BCF or originating ESRP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_110": {
        "requirement_text": "The credentials used by the server MUST be traceable to the PCA and MUST occur in the ESRP policy.",
        "document_section": "4.6.18",
        "description": "The credentials used by the server MUST be traceable to the PCA and MUST occur in the ESRP policy",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_111": {
        "requirement_text": "The ECRF MUST be used within the ESInet to route calls to the correct PSAP, and by the PSAP to route calls to the correct responders.",
        "document_section": "4.3",
        "description": "The ECRF MUST be used within the ESInet to route calls to the correct PSAP, and by the PSAP to route calls to the correct responders",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_112": {
        "requirement_text": "All elements that implement LoST MUST implement the Call and Incident ID extension.",
        "document_section": "3.4.10.4",
        "description": "All elements that implement LoST MUST implement the Call and Incident ID extension",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_113": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_114": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_115": {
        "requirement_text": "ElementStateChangeLogEvent: When an element sends a notification of state change as described in the Element State section of this document, it MUST log the ElementStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When an element sends a notification of state change, it MUST log the ElementStateChangeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_116": {
        "requirement_text": 'CallSignalingMessageLogEvent: An element MUST always log messages it receives (with "direction" set to "incoming").',
        "document_section": "4.12.3.7",
        "description": "An element MUST always log messages it receives (with 'direction' set to 'incoming') using CallSignalingMessageLogEvent",
        "test_id": "ESRP_010",
        "subtests": [
            "Verify Logging call status for SIP INVITE CallSignalingMessageLogEvent.",
            "Verify Logging call status for SIP BYE CallSignalingMessageLogEvent.",
        ],
    },
    "RQ_ESRP_117": {
        "requirement_text": "CallSignalingMessageLogEvent: An element MUST log outgoing messages it originates.",
        "document_section": "4.12.3.7",
        "description": "An element MUST log outgoing messages it originates using CallSignalingMessageLogEvent",
        "test_id": "ESRP_009",
        "subtests": [],
    },
    "RQ_ESRP_118": {
        "requirement_text": "CallSignalingMessageLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the CallSignalingMessageLogEvent",
        "test_id": "ESRP_009",
        "subtests": [],
    },
    "RQ_ESRP_119": {
        "requirement_text": "MalformedMessageLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the MalformedMessageLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_120": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services",
        "document_section": "4.12.1",
        "description": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_121": {
        "requirement_text": "ServiceStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ServiceStateChangeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_122": {
        "requirement_text": "ServiceStateChangeLogEvent: When a Service sends a notification of state change as described in the Service State section of this document, which includes Security Posture, it MUST log the ServiceStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When a Service sends a notification of state change, which includes Security Posture, it MUST log the ServiceStateChangeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_123": {
        "requirement_text": "All agencies and NG9 1 1 functional elements MUST have access to a conformant Logging Service and log all relevant events in that service.",
        "document_section": "4.12.4",
        "description": "All agencies and NG9-1-1 functional elements MUST have access to a conformant Logging Service and log all relevant events in that service",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_124": {
        "requirement_text": "Each element that is call stateful logs the beginning and end of its processing of a call, including non-interactive calls, with Start Call and End Call events. Elements that log CallStartLogEvent/CallEndLogEvent MUST also log the actual SIP message with CallSignalingMessageLogEvent for SIP parts of a call and GatewayCallLogEvent for TDM parts of a call. For CallStartLogEvent and CallEndLogEvent, the Timestamp MUST be the time the INVITE, MESSAGE, BYE or equivalents to these messages, or the final status code was received or sent by the element logging the event.",
        "document_section": "4.12.3.7",
        "description": "Each call-stateful element must log the beginning and end of its processing with CallStart/End events and also log the actual SIP message with CallSignalingMessageLogEvent for SIP parts of a call. The Timestamp MUST be the time the INVITE, MESSAGE, BYE or equivalents to these messages, or the final status code was received or sent",
        "test_id": "ESRP_010",
        "subtests": [],
    },
    "RQ_ESRP_125": {
        "requirement_text": "CallStartLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the CallStartLogEvent",
        "test_id": "ESRP_010",
        "subtests": ["Verify Logging call status for CallStartLogEvent."],
    },
    "RQ_ESRP_126": {
        "requirement_text": "CallEndLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the CallEndLogEvent",
        "test_id": "ESRP_010",
        "subtests": ["Verify Logging call status for CallEndLogEvent."],
    },
    "RQ_ESRP_127": {
        "requirement_text": "ElementStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ElementStateChangeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_128": {
        "requirement_text": "(common LogEvent prologue (base object/header) table)",
        "document_section": "4.12.3.1",
        "description": "Refers to the table describing the common prologue (base object/header) for all LogEvents",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_129": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "KeepAliveFailureLogEvent must log malformed, invalid, or missing responses in a 'responseStatus' member, including text and a status code from the Status Codes Registry, such as 'TimeOut'",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_130": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_131": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_132": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 or stronger",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_133": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 or stronger",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_134": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations MUST be privacy protected via TLS, preferably using AES-256 encryption or stronger. Shorter key lengths are strictly forbidden",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_135": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "KeepAliveFailureLogEvent must log malformed, invalid, or missing responses in a 'responseStatus' member, including text and a status code from the Status Codes Registry, such as 'TimeOut'",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_136": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_137": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 or stronger",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_138": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_139": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations MUST be privacy protected via TLS, preferably using AES-256 encryption or stronger. Shorter key lengths are strictly forbidden",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_140": {
        "requirement_text": "FEs that use a Logging Service MUST NOT depend on a Logging Service accepting an extension to provide services conformant to this document.",
        "document_section": "4.12.3.1",
        "description": "FEs that use a Logging Service MUST NOT depend on a Logging Service accepting an extension to provide conformant services",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_141": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services must be able to verify the signature of a signed LogEvent before responding. A failed signature is a warning, and the LogEvent MUST be recorded without the client retrying the request",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_142": {
        "requirement_text": "(LogEvents POST parameters)",
        "document_section": "4.12.3.1.2",
        "description": "Refers to the parameters required for a LogEvents POST request",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_143": {
        "requirement_text": 'QueueStateChangeLogEvent: Elements that receive changes in QueueState MAY log receipt of such changes and MUST log a state change to "unreachable".',
        "document_section": "4.12.3.7",
        "description": "Elements that receive QueueState changes MAY log the receipt, but they MUST log a state change to 'unreachable'",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_144": {
        "requirement_text": "QueueStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the QueueStateChangeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_145": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services must be able to verify the signature of a signed LogEvent before responding. A failed signature is a warning, and the LogEvent MUST be recorded without the client retrying the request",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_146": {
        "requirement_text": "MessageLogEvent states: Elements that log Message MUST also log the actual SIP message with CallSignalingMessageLogEvent.",
        "document_section": "",
        "description": "Elements that log a MessageLogEvent MUST also log the actual SIP message with a CallSignalingMessageLogEvent",
        "test_id": "ESRP_009",
        "subtests": [],
    },
    "RQ_ESRP_147": {
        "requirement_text": "MessageLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the MessageLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_148": {
        "requirement_text": 'LostQueryLogEvent:  A "queryId" member is used to relate the request to the response. The id is generated locally, MUST be globally unique',
        "document_section": "4.12.3.7",
        "description": "LostQueryLogEvent uses a locally-generated, globally unique 'queryId' member to relate the request to its response",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_149": {
        "requirement_text": "LostResponseLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the LostResponseLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_150": {
        "requirement_text": 'LostResponseLogEvent:  A "responseId" member is used to relate the request to the response, and MUST match the id used in the LostQueryLogEvent.',
        "document_section": "4.12.3.7",
        "description": "LostResponseLogEvent must use a 'responseId' member that matches the 'queryId' from the LostQueryLogEvent to relate the request and response",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_151": {
        "requirement_text": "SubscribeLogEvent: The id is generated locally, MUST be globally unique",
        "document_section": "4.12.3.7",
        "description": "SubscribeLogEvent must use a locally-generated, globally unique ID",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_152": {
        "requirement_text": "RouteLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the RouteLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_153": {
        "requirement_text": "RouteRuleMsgLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the RouteRuleMsgLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_154": {
        "requirement_text": "AdditionalDataResponseLogEvent: Any Additional Data that is retrieved by a client MUST be logged using the AdditionalDataResponseLogEvent.",
        "document_section": "4.12.3.7",
        "description": "Any Additional Data retrieved by a client MUST be logged using the AdditionalDataResponseLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_155": {
        "requirement_text": 'LocationQueryLogEvent: A "queryId" member is used to relate the request or subscription to the response or notifications. The id is generated locally, MUST be globally unique,',
        "document_section": "4.12.3.7",
        "description": "LocationQueryLogEvent uses a locally-generated, globally unique 'queryId' member to relate a request or subscription to its response or notifications",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_156": {
        "requirement_text": "LocationQueryLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the LocationQueryLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_157": {
        "requirement_text": "LocationResponseLogEvent: All clients and servers, if the server is located inside an ESInet, or is an LNG or LSRG operated by, or on behalf of, a 9-1-1 Authority, MUST log responses.",
        "document_section": "4.12.3.7",
        "description": "All clients and specified servers (e.g., in the ESInet, or 9-1-1 Authority-operated LNG/LSRG) MUST log LocationResponseLogEvent responses",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_158": {
        "requirement_text": 'LocationResponseLogEvent: A "responseId" member is used to relate the request or subscription to the response or notifications and MUST match the id used in the LocationQueryLogEvent.',
        "document_section": "4.12.3.7",
        "description": "LocationResponseLogEvent must use a 'responseId' member that matches the 'queryId' from the LocationQueryLogEvent to relate the request and response",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_159": {
        "requirement_text": "LocationResponseLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the LocationResponseLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_160": {
        "requirement_text": "EidoLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the EidoLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_161": {
        "requirement_text": "AdditionalDataQueryLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the AdditionalDataQueryLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_162": {
        "requirement_text": "SubscribeLogEvent: The Server MUST log this event",
        "document_section": "4.12.3.7",
        "description": "The Server MUST log the SubscribeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_163": {
        "requirement_text": "SubscribeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the SubscribeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_164": {
        "requirement_text": "SubscribeLogEvent: The Server MUST log this event",
        "document_section": "4.12.3.7",
        "description": "The Server MUST log the SubscribeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_165": {
        "requirement_text": "SubscribeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the SubscribeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_166": {
        "requirement_text": "A queue manager MUST log a change in the state of the queue with the QueueStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "A queue manager MUST log a change in the state of the queue with the QueueStateChangeLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_167": {
        "requirement_text": 'AdditionalDataQueryLogEvent: A "queryId" member is used to relate the request to the response. The id is generated locally, MUST be globally unique',
        "document_section": "4.12.3.7",
        "description": "AdditionalDataQueryLogEvent uses a locally-generated, globally unique 'queryId' member to relate the request to its response",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_168": {
        "requirement_text": 'AdditionalDataResponseLogEvent: A "responseId" member is used to relate the request to the response and MUST match the id used in the AdditionalDataQueryLogEvent.',
        "document_section": "4.12.3.7",
        "description": "AdditionalDataResponseLogEvent must use a 'responseId' member that matches the 'queryId' from the AdditionalDataQueryLogEvent to relate the request and response",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_169": {
        "requirement_text": "AdditionalDataResponseLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the AdditionalDataResponseLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_170": {
        "requirement_text": "EidoLogEvent: Any element that sends or receives an Emergency Incident Data Document [111] MUST log it with the EidoLogEvent.",
        "document_section": "4.12.3.7",
        "description": "Any element that sends or receives an Emergency Incident Data Document MUST log it with the EidoLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_171": {
        "requirement_text": 'EidoLogEvent: If an EIDO is sent or received by reference, the EIDO URI MUST be logged with a "reference" member.',
        "document_section": "4.12.3.7",
        "description": "If an EIDO is sent or received by reference, the EidoLogEvent MUST log the EIDO URI with a 'reference' member",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_172": {
        "requirement_text": 'EidoLogEvent: When the URI is dereferenced, another EIDOLogEvent MUST be created with the "reference" and "body" by both the client and server.',
        "document_section": "4.12.3.7",
        "description": "When the EIDO URI is dereferenced, both the client and server MUST create another EIDOLogEvent including both the 'reference' and 'body'",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_173": {
        "requirement_text": "LostQueryLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the LostQueryLogEvent",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_174": {
        "requirement_text": "Any element inside a PSAP that provides a call queue MUST deploy an ElementState notifier as described in Section 2.4.1.",
        "document_section": "4.6.6",
        "description": "Any element inside a PSAP that provides a call queue MUST deploy an ElementState notifier as described in Section 2.4.1",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_175": {
        "requirement_text": "The PSAP MUST implement an NTP client interface for time of day information.",
        "document_section": "4.6.16",
        "description": "The PSAP MUST implement an NTP client interface for time of day information",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_176": {
        "requirement_text": "All DRs MUST contain common data elements (a prolog) that include: [see list]",
        "document_section": "3.7",
        "description": "All DRs MUST contain common data elements (a prolog) that include: [see list]",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_177": {
        "requirement_text": 'Implementations MUST support (be capable of generating and using) algorithm "EdDSA" and MUST NOT use other algorithms except that implementations of the Logging Service and clients of the Logging Service MUST support (be capable of generating and using) unsigned (algorithm "none")',
        "document_section": "2.8.1",
        "description": "Implementations MUST support the 'EdDSA' algorithm, and only the Logging Service and its clients must also support the unsigned 'none' algorithm",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_178": {
        "requirement_text": "The services, unless specified otherwise, MUST support HTTP/1.1 (RFC 7230) [162] and SHOULD support HTTP/2.0 (RFC 7540) [197].",
        "document_section": "2.8.2",
        "description": "The services, unless specified otherwise, MUST support HTTP/1.1 and SHOULD support HTTP/2.0",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_179": {
        "requirement_text": "Clients MUST appropriately handle all status codes listed for each supported entry point, and MUST react appropriately to other status codes received, based on the first digit as per RFC 7231 [223] Section 6.",
        "document_section": "2.8.3",
        "description": "Clients MUST appropriately handle all listed status codes and react to other status codes based on the first digit as per RFC 7231, Section 6",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_180": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand",
        "document_section": "2.8.3",
        "description": "Implementations MUST ignore elements of data structures they do not understand",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_181": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand and MUST return 404 errors to entry points to the web interfaces they don't provide as a server.",
        "document_section": "2.8.3",
        "description": "Implementations MUST ignore unknown elements and MUST return 404 errors for unsupported web interfaces",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_182": {
        "requirement_text": 'Each Web Service MUST implement an entry point called "Versions".',
        "document_section": "2.9",
        "description": "Each Web Service MUST implement an entry point called 'Versions'",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_183": {
        "requirement_text": "Clients MUST retry transactions on redundant elements that that could not be completed on the initial element.",
        "document_section": "2.9",
        "description": "Clients MUST retry transactions on redundant elements that that could not be completed on the initial element",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_184": {
        "requirement_text": "Every implementation MUST be capable of using a DNS based implementation of redundant elements where more than one address may be returned for the URI provided.",
        "document_section": "2.9",
        "description": "Every implementation MUST be capable of using a DNS based implementation of redundant elements where more than one address may be returned for the URI provided",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_185": {
        "requirement_text": "Implementations MUST be capable of preferring the first returned address, and using the second, third and optionally additional addresses returned as representing redundant elements for the service.",
        "document_section": "2.9",
        "description": "Implementations MUST be capable of preferring the first returned address, and using subsequent addresses as redundant elements",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_186": {
        "requirement_text": "Other mechanisms to achieve redundancy MAY be provided, but the DNS based mechanism MUST be supported by all services and clients of those services.",
        "document_section": "3.1.12",
        "description": "Other redundancy mechanisms MAY be provided, but the DNS based mechanism MUST be supported by all services and clients",
        "test_id": "ESRP_007",
        "subtests": [],
    },
    "RQ_ESRP_187": {
        "requirement_text": "All SIP elements in an ESInet/NGCS MUST support multipart MIME as defined in RFC 2046 [90]",
        "document_section": "3.1.12",
        "description": "All SIP elements in an ESInet/NGCS MUST support multipart MIME as defined in RFC 2046",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_188": {
        "requirement_text": "All SIP elements in the NGCS MUST allow all mime types/body parts to pass to the PSAP",
        "document_section": "3.1.13",
        "description": "All SIP elements in the NGCS MUST allow all mime types/body parts to pass to the PSAP",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_189": {
        "requirement_text": "all SIP elements within the NGCS MUST support connection reuse, RFC 5923 [217].",
        "document_section": "3.1.14",
        "description": "All SIP elements within the NGCS MUST support connection reuse, RFC 5923",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_190": {
        "requirement_text": "All SIP elements MUST support routing of SIP messages per RFC 3261 [10] and RFC 3263 [13].",
        "document_section": "3.1.14",
        "description": "All SIP elements MUST support routing of SIP messages per RFC 3261 and RFC 3263",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_191": {
        "requirement_text": "DNS SRV records (RFC 2782) [75] MUST be consulted to determine the hostname of the SIP server for that domain.",
        "document_section": "3.1.17",
        "description": "DNS SRV records MUST be consulted to determine the hostname of the SIP server for that domain",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_192": {
        "requirement_text": "all SIP elements MUST implement the overload control mechanisms described in RFC 7339 [56].",
        "document_section": "3.1.18",
        "description": "All SIP elements MUST implement the overload control mechanisms described in RFC 7339",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_193": {
        "requirement_text": "All elements in an ESInet that implement SIP interfaces MUST comply with RFC 5626 [42] (Outbound) to maintain connections from User Agents.",
        "document_section": "3.1.2.4",
        "description": "All elements in an ESInet that implement SIP interfaces MUST comply with RFC 5626 (Outbound) to maintain connections from User Agents",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_194": {
        "requirement_text": "All endpoints in an ESInet/NGCS MUST use ACK.",
        "document_section": "3.1.2.5",
        "description": "All endpoints in an ESInet/NGCS MUST use ACK",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_195": {
        "requirement_text": "The PRACK method MUST be used within systems that need reliable provisional responses (non 100)",
        "document_section": "3.1.2.6",
        "description": "The PRACK method MUST be used within systems that need reliable provisional responses (non 100)",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_196": {
        "requirement_text": "ESInet elements MUST allow MESSAGE requests in the context of a dialog initiated by some other SIP request.",
        "document_section": "3.1.3.2",
        "description": "ESInet elements MUST allow MESSAGE requests in the context of a dialog initiated by some other SIP request",
        "test_id": "ESRP_011",
        "subtests": [],
    },
    "RQ_ESRP_197": {
        "requirement_text": "subscribers MUST refresh subscriptions on a periodic basis using a new SUBSCRIBE message on the same dialog.",
        "document_section": "3.1.3.2",
        "description": "Subscribers MUST refresh subscriptions on a periodic basis using a new SUBSCRIBE message on the same dialog",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_198": {
        "requirement_text": "Entities implementing a notifier MUST implement RFC 3857 [26].",
        "document_section": "3.1.7",
        "description": "Entities implementing a notifier MUST implement RFC 3857",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_199": {
        "requirement_text": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order when a queue of calls is waiting for service at the proxy server and, when needed, preempt lower priority calls",
        "document_section": "3.2",
        "description": "All SIP proxy servers in the ESInet/NGCS MUST implement Resource-Priority and process calls in priority order, preempting lower priority calls when needed",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_200": {
        "requirement_text": "Each element MUST do its own de-reference operation, supplying its credentials to the LIS.",
        "document_section": "3.2",
        "description": "Each element MUST do its own de-reference operation, supplying its credentials to the LIS",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_201": {
        "requirement_text": "When location is passed by value, processing elements along the path MUST NOT change the location record.",
        "document_section": "3.2",
        "description": "When location is passed by value, processing elements along the path MUST NOT change the location record",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_202": {
        "requirement_text": "NGCS that receive a location reference and forward location in SIP signaling to another element MUST pass the reference, and not any value that they determine by de- referencing (although the value should be logged).",
        "document_section": "3.2",
        "description": "NGCS that receive a location reference and forward location in SIP signaling MUST pass the reference, and not any value determined by de-referencing",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_203": {
        "requirement_text": "If additional location is acquired16, a new PIDF-LO with a different <provided-by> element MUST be created and passed in addition to the original location.",
        "document_section": "3.7",
        "description": "If additional location is acquired, a new PIDF-LO with a different <provided-by> element MUST be created and passed in addition to the original location",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_204": {
        "requirement_text": "The functional elements described in this document MUST support the discrepancy report (DR) function.",
        "document_section": "3.7",
        "description": "The functional elements described in this document MUST support the discrepancy report (DR) function",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_205": {
        "requirement_text": "Each database, service, and agency MUST provide a Discrepancy Reporting web service.",
        "document_section": "5.10",
        "description": "Each database, service, and agency MUST provide a Discrepancy Reporting web service",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_206": {
        "requirement_text": 'If a Web Service request receives an "Unacceptable Algorithm" error, the client MUST make a new request on the Versions entry point and retry the request with a JWS that uses a signing algorithm acceptable to the Web Service.',
        "document_section": "5.10",
        "description": "If a Web Service request receives an 'Unacceptable Algorithm' error, the client MUST query the Versions entry point and retry the request with an acceptable JWS signing algorithm",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_207": {
        "requirement_text": 'When this document indicates that a set of Web Service interface parameters is a JWS (e.g., for LogEvents), the set of parameters is conveyed in the web service request as a string consisting of a JWS. The JWS is formed by applying the JWS algorithm to the set of parameters per the JWS standard [171]. The JWS Protected Header MUST contain exactly one "alg" field. The "alg" field MUST have a value acceptable to the Web Service. An unsigned (unprotected) JWS is indicated by an "alg" field set to the value "none". For signed LogEvents, and all other uses of JWS requiring signatures (e.g., policy documents), the JWS Protected Header MUST have its "alg" field set to a value acceptable to the Web Service that MUST NOT be "none" and MUST specify the signing entity\'s X.509 certificate and all intermediate certificates up to one signed by the trusted root58. The certificate is provided either by reference or by value. A certificate provided by value is contained in an "x5c" field. A certificate is provided by reference using the "x5u" and "x5t#256" fields. When the "x5u" field is present, it MUST contain a URL that is stable (resolvable) for a minimum of 10 years. The JWS Protected Header MAY contain other fields. When the "x5u" field is used, the "x5t#256" field MUST also be used, to allow an entity to more easily detect when a certificate chain needs to be retrieved.',
        "document_section": "5.10",
        "description": "Web Service interface parameters are conveyed as a JWS string with an acceptable 'alg' field in the Protected Header. Signed JWS usage MUST use a non-'none' algorithm and include the signing entity's X.509 certificate (by value or reference)",
        "test_id": "",
        "subtests": [],
    },
    "RQ_ESRP_208": {
        "requirement_text": 'a JWS MUST use the Flat JSON serialization format (not JWS Compact Serialization and not General JWS JSON Serialization Syntax), and only the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448 (algorithm "EdDSA") [227] [228] signature method is used.',
        "document_section": "5.10",
        "description": "A JWS MUST use the Flat JSON serialization format and employ only the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448 ('EdDSA') as the signature method",
        "test_id": "",
        "subtests": [],
    },
    'If the ESRP is inside a PSAP, then answer "Y" or "N" for each requirement.  Otherwise, answer "N/A":': {
        "requirement_text": "",
        "document_section": "",
        "description": "Placeholder for conditional evaluation: If the ESRP is inside a PSAP, evaluate requirements as Y/N.",
        "test_id": "",
        "subtests": [],
    },
}
