REQUIREMENTS_SCHEMA = {
    "RQ_PS_001": {
        "requirement_text": "If the policy is needed for use after expiration, it MUST be retrieved again from the Policy Store",
        "document_section": "3.3",
        "description": "If a policy is needed after its policy expiration time, it MUST be retrieved again from the Policy Store.",
        "test_id": "PS_010",
        "subtests": [],
    },
    "RQ_PS_004": {
        "requirement_text": "Policies stored in the Policy Store MUST be signed by the owner of the Policy.",
        "document_section": "3.3",
        "description": "Policies stored in the Policy Store MUST be signed by the owner of the policy.",
        "test_id": "PS_001",
        "subtests": [],
    },
    "RQ_PS_006": {
        "requirement_text": "A policy document MUST be a JSON Web Signature (JWS) object per Section 5.10",
        "document_section": "3.3",
        "description": "A policy document MUST be a JSON Web Signature (JWS) object as defined in Section 5.10.",
        "test_id": "PS_001",
        "subtests": [],
    },
    "RQ_PS_008": {
        "requirement_text": "For agencies within an ESInet, a credential traceable to the PCA MUST be used.",
        "document_section": "3.3",
        "description": "Agencies within an ESInet MUST use a credential traceable to the PCA (PSAP Credentialing Agency).",
        "test_id": "PS_001",
        "subtests": [],
    },
    "RQ_PS_010": {
        "requirement_text": "During processing of a POST or PUT request to the Policies entrypoint, the PS MUST verify that the request contains a JWS with a Policy Object that conforms to the YAML for the Policy Object. (https://github.com/NENA911/)",
        "document_section": "3.3.1",
        "description": "When processing a POST or PUT request, the Policy Store (PS) MUST verify that the request contains a JWS with a Policy Object that conforms to the specified YAML structure.",
        "test_id": "PS_002",
        "subtests": [],
    },
    "RQ_PS_011": {
        "requirement_text": "(Policy Object contents table)",
        "document_section": "3.3.1 and 3.3.1.2.1",
        "description": "Refers to the table detailing the required contents of the Policy Object.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_013": {
        "requirement_text": "(Versions entry point result parameters)",
        "document_section": "3.3.1.1",
        "description": "Refers to the required parameters for the successful response of the Versions entry point.",
        "test_id": "PS_003",
        "subtests": [],
    },
    "RQ_PS_014": {
        "requirement_text": 'The Versions entry point of the Policy Store Web Service MUST include, in the "serviceInfo" parameter, the parameter "requiredAlgorithms" whose value is an array of JWS algorithms (as described in 5.10) acceptable to the policy store.',
        "document_section": "3.3.1.1",
        "description": "The Versions entry point MUST include the 'requiredAlgorithms' array within the 'serviceInfo' parameter, listing JWS algorithms acceptable to the Policy Store.",
        "test_id": "PS_003",
        "subtests": [
            "Verify if all 'versions' contain 'serviceInfo' with 'requiredAlgorithms' array of string values"
        ],
    },
    "RQ_PS_016": {
        "requirement_text": "(PolicyArray contents table)",
        "document_section": "3.3.1.2.1",
        "description": "Refers to the table detailing the required contents of the PolicyArray.",
        "test_id": "PS_004",
        "subtests": ["Validate response message for: {variation_name}"],
    },
    "RQ_PS_017": {
        "requirement_text": "(Retrieve Policies parameters)",
        "document_section": "3.3.1.2.1",
        "description": "Refers to the parameters required for retrieving policies.",
        "test_id": "PS_004",
        "subtests": ["Validate 4xx error response for: {variation_name}"],
    },
    "RQ_PS_019": {
        "requirement_text": "(Update Policy  parameters)",
        "document_section": "3.3.1.2.3",
        "description": "Refers to the parameters required for updating a policy.",
        "test_id": "PS_005",
        "subtests": [],
    },
    "RQ_PS_021": {
        "requirement_text": "(Delete Policy  parameters)",
        "document_section": "3.3.1.2.4",
        "description": "Refers to the parameters required for deleting a policy.",
        "test_id": "PS_006",
        "subtests": [],
    },
    "RQ_PS_023": {
        "requirement_text": "(Enumerate Policies  parameters)",
        "document_section": "3.3.1.3.1",
        "description": "Refers to the parameters required for enumerating all policies.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_025": {
        "requirement_text": "Following a POST, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each rule has a unique id and verify the signature of the JWS.",
        "document_section": "3.3.1.2.2",
        "description": "Following a POST, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm each rule has a unique ID and verify the JWS signature.",
        "test_id": "PS_002",
        "subtests": [],
    },
    "RQ_PS_026": {
        "requirement_text": "Following a POST, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each rule has a unique id and verify the signature of the JWS.",
        "document_section": "3.3.1.2.2",
        "description": "Following a POST, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm each rule has a unique ID and verify the JWS signature.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_027": {
        "requirement_text": "Following a POST, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each rule has a unique id and verify the signature of the JWS.",
        "document_section": "3.3.1.2.2",
        "description": "Following a POST, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm each rule has a unique ID and verify the JWS signature.",
        "test_id": "PS_007",
        "subtests": [],
    },
    "RQ_PS_028": {
        "requirement_text": "Following a POST, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each rule has a unique id and verify the signature of the JWS.",
        "document_section": "3.3.1.2.2",
        "description": "Following a POST, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm each rule has a unique ID and verify the JWS signature.",
        "test_id": "PS_001",
        "subtests": [],
    },
    "RQ_PS_029": {
        "requirement_text": "When processing an Update request, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each file has a unique ID and verify the signature of the JWS.",
        "document_section": "3.3.1.2.3",
        "description": "When processing an Update request, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm each file has a unique ID and verify the JWS signature.",
        "test_id": "PS_005",
        "subtests": ["Validate 4xx error response for invalid request"],
    },
    "RQ_PS_030": {
        "requirement_text": "When processing an Update request, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each file has a unique ID and verify the signature of the JWS.",
        "document_section": "3.3.1.2.3",
        "description": "When processing an Update request, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm each file has a unique ID and verify the JWS signature.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_031": {
        "requirement_text": "When processing an Update request, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each file [rule] has a unique ID and verify the signature of the JWS.",
        "document_section": "3.3.1.2.3",
        "description": "When processing an Update request, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm that each rule has a unique ID and verify the JWS signature.",
        "test_id": "PS_007",
        "subtests": [],
    },
    "RQ_PS_032": {
        "requirement_text": "When processing an Update request, the Policy Store MUST confirm that the policyExpirationTime is in the future and the structure and contents of the document is well-formed and conformant; for Policy Routing Rules, MUST confirm that each file [rule] has a unique ID and verify the signature of the JWS.",
        "document_section": "3.3.1.2.3",
        "description": "When processing an Update request, the Policy Store MUST confirm the policy expiration time is in the future and the document is well-formed. For Policy Routing Rules, it MUST confirm that each rule has a unique ID and verify the JWS signature.",
        "test_id": "PS_005",
        "subtests": ["Validate 4xx error response for invalid request"],
    },
    "RQ_PS_033": {
        "requirement_text": "(PolicyEnumArray members)",
        "document_section": "3.3.1.2.6",
        "description": "Refers to the required members for the PolicyEnumArray.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_034": {
        "requirement_text": "A Route Policy document MUST be a JWS [171] as per Section 5.10 and MUST have a payload conforming to Appendix E.10.",
        "document_section": "3.3.3",
        "description": "A Route Policy document MUST be a JWS (Section 5.10) and MUST have a payload conforming to Appendix E.10.",
        "test_id": "PS_007",
        "subtests": [],
    },
    "RQ_PS_036": {
        "requirement_text": "A Route Policy document MUST be a JWS [171] as per Section 5.10 and MUST have a payload conforming to Appendix E.10. A condition object contains the following members:   'conditionType': a string which MUST exist and be set to the specific condition type.   'negation': an OPTIONAL Boolean that when set to 'true' inverts the condition sense. When \"negation\" exists and is set to 'true', it reverses the evaluation of the \"Conditions\" object; when set to 'false' or omitted it has no effect.   'description': an OPTIONAL string containing a description of the condition.",
        "document_section": "3.3.3",
        "description": "A Route Policy document MUST be a JWS and conform to Appendix E.10. The condition object within it MUST contain a 'conditionType', MAY contain a 'negation' Boolean to invert the condition, and MAY include a 'description'.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_039": {
        "requirement_text": "The Policy Store is REQUIRED to store and retrieve Route Policy documents byte-for-byte unaltered",
        "document_section": "3.3.3",
        "description": "The Policy Store is REQUIRED to store and retrieve Route Policy documents byte-for-byte unaltered.",
        "test_id": "PS_008",
        "subtests": [],
    },
    "RQ_PS_041": {
        "requirement_text": "(Time Period Condition members)",
        "document_section": "3.3.3.1.1",
        "description": "Refers to the required members for the Time Period Condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_044": {
        "requirement_text": "An ESRP or other entity executing a policy MUST ignore an invalid value in a member (e.g., a timeStart or timeEnd with an hour greater than 24, or minutes or seconds greater than 60, or hour set to 24 with minutes or seconds greater than 0) but SHOULD generate a Discrepancy Report against the policy owner (Section 3.7.13) and MAY file a DR against the Policy Store (Section 3.7.4). A Policy Store MUST reject as an error an attempt to store or update a policy containing an invalid value.",
        "document_section": "3.3.3.1.1",
        "description": "An ESRP executing a policy MUST ignore invalid values (e.g., in timeStart/timeEnd) but SHOULD generate a Discrepancy Report (DR). The Policy Store MUST reject with an error any attempt to store or update a policy containing an invalid value.",
        "test_id": "PS_007",
        "subtests": [],
    },
    "RQ_PS_046": {
        "requirement_text": "(SIP Header condition members)",
        "document_section": "3.3.3.1.2",
        "description": "Refers to the required members for the SIP Header condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_048": {
        "requirement_text": "(Additional Data condition condition members)",
        "document_section": "3.3.3.1.3",
        "description": "Refers to the required members for the Additional Data condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_050": {
        "requirement_text": "(MIME Body List condition condition member)",
        "document_section": "3.3.3.1.4",
        "description": "Refers to the required members for the MIME Body List condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_052": {
        "requirement_text": "(Location condition condition members)",
        "document_section": "3.3.3.1.5",
        "description": "Refers to the required members for the Location condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_054": {
        "requirement_text": "(Call Suspicion condition condition members)",
        "document_section": "3.3.3.1.6",
        "description": "Refers to the required members for the Call Suspicion condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_056": {
        "requirement_text": "(Security Posture condition members)",
        "document_section": "3.3.3.1.7",
        "description": "Refers to the required members for the Security Posture condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_058": {
        "requirement_text": "(Queue State condition members)",
        "document_section": "3.3.3.1.8",
        "description": "Refers to the required members for the Queue State condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_060": {
        "requirement_text": "(LoST Service URN condition members)",
        "document_section": "3.3.3.1.9",
        "description": "Refers to the required members for the LoST Service URN condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_062": {
        "requirement_text": "(Service State condition members)",
        "document_section": "3.3.3.1.10",
        "description": "Refers to the required members for the Service State condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_064": {
        "requirement_text": "(Call Source condition members)",
        "document_section": "3.3.3.1.11",
        "description": "Refers to the required members for the Call Source condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_066": {
        "requirement_text": "(Body Part condition members)",
        "document_section": "3.3.3.1.12",
        "description": "Refers to the required members for the Body Part condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_068": {
        "requirement_text": "(Request URI condition members)",
        "document_section": "3.3.3.1.13",
        "description": "Refers to the required members for the Request URI condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_070": {
        "requirement_text": "(Normal-NextHop condition members)",
        "document_section": "3.3.3.1.14",
        "description": "Refers to the required members for the Normal-NextHop condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_072": {
        "requirement_text": "(Incoming Queue condition members)",
        "document_section": "3.3.3.1.15",
        "description": "Refers to the required members for the Incoming Queue condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_074": {
        "requirement_text": "(SDP Offer condition members)",
        "document_section": "3.3.3.1.16",
        "description": "Refers to the required members for the SDP Offer condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_076": {
        "requirement_text": "(CAP condition members)",
        "document_section": "3.3.3.1.17",
        "description": "Refers to the required members for the CAP condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_078": {
        "requirement_text": "(Calling Number Verification Status condition members)",
        "document_section": "3.3.3.1.18",
        "description": "Refers to the required members for the Calling Number Verification Status condition.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_080": {
        "requirement_text": "A Route Policy document MUST be a JWS [171] as per Section 5.10 and MUST have a payload conforming to Appendix E.10. An 'Actions' object contains the following members:    actionType: a string which MUST exist and be set to the specific action type.    \"description\": an OPTIONAL string containing a description of the action.    Other action-specific members as described in the below subsections.",
        "document_section": "3.3.3.2",
        "description": "A Route Policy document MUST be a JWS and conform to Appendix E.10. An 'Actions' object within it MUST contain an 'actionType', and MAY contain a 'description' or other action-specific members.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_082": {
        "requirement_text": "Rules MUST NOT contain more than one Route, Busy or Invoke Policy action, or a combination of Route, Busy or Invoke Policy actions.",
        "document_section": "3.3.3.2",
        "description": "Rules MUST NOT contain more than one Route, Busy, or Invoke Policy action, or any combination of those three actions.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_084": {
        "requirement_text": "(Route action members)",
        "document_section": "3.3.3.2.1",
        "description": "Refers to the required members for the Route action.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_086": {
        "requirement_text": 'The "NotifyAction" object has the following members:     "recipient", which is OPTIONAL. When present, it MUST be either a URI or a service URN. This member is used to notify a single entity registered for the "eventCode". If "recipient" is a URI, notification is generated for that specific recipient. If "recipient" is a service URN, the ECRF is used to map the service URN to a URI, and a notification is generated for that URI. Recipients MUST have subscribed for the "eventCode" to get the notification. If "recipient" is omitted, notification is generated for all subscribers to the "eventCode". In all cases, notifications are subject to per-recipient throttling.    "eventCode", which MUST exist and be set to a value contained in the EsrpNotifyEventCodes registry (Section 10.19).    "urgency", which MUST exist and be set to an integer value from 0 and 100 where 0 is no urgency and 100 is the highest possible urgency.    "comment", which is OPTIONAL. If present, it is a text string that is included in the "Comment" field of the NOTIFY message.',
        "document_section": "3.3.3.2.3",
        "description": "The 'NotifyAction' object includes optional 'recipient' (URI or service URN) and optional 'comment'; it MUST include 'eventCode' (from EsrpNotifyEventCodes registry) and 'urgency' (integer 0-100).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_089": {
        "requirement_text": "(Log Message action members)",
        "document_section": "3.3.3.2.4",
        "description": "Refers to the required members for the Log Message action.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_091": {
        "requirement_text": "(Invoke Policy action members)",
        "document_section": "3.3.3.2.5",
        "description": "Refers to the required members for the Invoke Policy action.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_093": {
        "requirement_text": 'Each "timeStart" and "timeEnd" member MUST contain a single value',
        "document_section": "3.3.3.1.1.1",
        "description": "Each 'timeStart' and 'timeEnd' member MUST contain a single value.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_095": {
        "requirement_text": "if specified MUST be greater than the value of timeStart",
        "document_section": "3.3.3.1.1",
        "description": "The timeEnd value, if specified, MUST be greater than the value of timeStart.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_096": {
        "requirement_text": 'a policy store MUST NOT include "none"',
        "document_section": "5.10",
        "description": "A Policy Store MUST NOT include the 'none' algorithm in its list of acceptable JWS algorithms.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_097": {
        "requirement_text": 'Each Web Service that has entrypoints in which a JWS is used MUST include the "requiredAlgorithms" parameter in the "serviceInfo" parameter of the object returned by its Versions entrypoint.',
        "document_section": "5.10",
        "description": "Each Web Service using a JWS MUST include the 'requiredAlgorithms' parameter within the 'serviceInfo' object returned by its Versions entry point.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_098": {
        "requirement_text": 'The rule that has the LostServiceUrnCondition MUST contain an action "InvokePolicyAction" which uses the NormalNexthopRoutePolicy for <policyType>, and results in executing the rule set associated with the policy identified by the Normal-NextHop URI.',
        "document_section": "4.2.1.5",
        "description": "The rule with the LostServiceUrnCondition MUST contain an 'InvokePolicyAction' that uses the NormalNexthopRoutePolicy type and executes the rule set of the Normal-NextHop URI.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_099": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_100": {
        "requirement_text": "DiscrepancyReportLogEvent members.",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the DiscrepancyReportLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_101": {
        "requirement_text": "ElementStateChangeLogEvent: When an element sends a notification of state change as described in the Element State section of this document, it MUST log the ElementStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When an element sends a notification of a state change, it MUST log the ElementStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_102": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services",
        "document_section": "4.12.1",
        "description": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_103": {
        "requirement_text": "ServiceStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ServiceStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_104": {
        "requirement_text": "ServiceStateChangeLogEvent: When a Service sends a notification of state change as described in the Service State section of this document, which includes Security Posture, it MUST log the ServiceStateChangeLogEvent.",
        "document_section": "4.12.3.7",
        "description": "When a Service sends a state change notification, which includes Security Posture, it MUST log the ServiceStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_105": {
        "requirement_text": "All agencies and NG9 1 1 functional elements MUST have access to a conformant Logging Service and log all relevant events in that service.",
        "document_section": "4.12.4",
        "description": "All agencies and NG9-1-1 functional elements MUST have access to a conformant Logging Service and log all relevant events.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_106": {
        "requirement_text": "ElementStateChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the ElementStateChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_107": {
        "requirement_text": "(common LogEvent prologue (base object/header) table)",
        "document_section": "4.12.3.1",
        "description": "Refers to the table detailing the common LogEvent prologue (base object/header).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_108": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "Malformed, invalid, or missing responses to keep-alive checks MUST be logged in the 'responseStatus' member of the KeepAliveFailureLogEvent, including text and a status code like TimeOut.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_109": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_110": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_111": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations MUST be integrity-protected using TLS with a minimum of SHA-256 or stronger.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_112": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations MUST be integrity-protected using TLS with a minimum of SHA-256 or stronger.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_113": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations MUST be privacy protected via TLS using a minimum of AES-256 encryption; shorter key lengths are forbidden, and legacy systems must be upgraded.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_114": {
        "requirement_text": 'KeepAliveFailureLogEvent: Malformed, invalid, or responses not received from the other element MUST be logged in a "responseStatus" member that contains text and a status code from the Status Codes Registry (Section 10.29). There is a TimeOut status in that registry that is used for a timeout failure of OPTIONS.',
        "document_section": "4.12.3.7",
        "description": "Malformed, invalid, or missing responses to keep-alive checks MUST be logged in the 'responseStatus' member of the KeepAliveFailureLogEvent, including text and a status code like TimeOut.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_115": {
        "requirement_text": "KeepAliveFailureLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the KeepAliveFailureLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_116": {
        "requirement_text": "All protocol operations MUST be integrity-protected with TLS, using SHA-256 [62] or stronger. SHA-256 MUST be supported by all implementations.",
        "document_section": "5.7",
        "description": "All protocol operations MUST be integrity-protected using TLS with a minimum of SHA-256 or stronger.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_117": {
        "requirement_text": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes",
        "document_section": "4.12.1",
        "description": "Clients to the Logging Service MUST support logging to at least two Logging Services for redundancy purposes.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_118": {
        "requirement_text": "All protocol operations MUST be privacy protected via TLS, preferably using Advanced Encryption Standard (AES) [63] with a minimum key length of 256 bits (AES-256). Shorter key length MUST NOT be used. Systems currently using Data Encryption Standard (DES) or triple-DES MUST be upgraded to at least AES-256. Alternate encryption algorithms are acceptable as long as they are at least as strong as AES.",
        "document_section": "5.8",
        "description": "All protocol operations MUST be privacy protected via TLS using a minimum of AES-256 encryption; shorter key lengths are forbidden, and legacy systems must be upgraded.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_119": {
        "requirement_text": "FEs that use a Logging Service MUST NOT depend on a Logging Service accepting an extension to provide services conformant to this document.",
        "document_section": "4.12.3.1",
        "description": "Functional Elements (FEs) using a Logging Service MUST NOT rely on that service accepting an extension to provide conformant services.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_120": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services MUST verify the LogEvent signature before responding. A failed signature returns a warning, the LogEvent MUST be recorded, and the client MUST NOT retry the request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_121": {
        "requirement_text": "(LogEvents POST parameters)",
        "document_section": "4.12.3.1.2",
        "description": "Refers to the parameters required for a LogEvents POST request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_122": {
        "requirement_text": 'Logging Services MUST be capable of verifying the signature of a signed LogEvent during the processing of the LogEvent request (i.e., before returning the response). The currently in force policy of the agency operating the Logging Service determines if the Logging Service does so. If the signature verification fails, it MUST return a "Signature Verification Failed" status code as a warning and SHOULD generate (subject to throttling) a Signature/Certificate Discrepancy Report (Section 3.7.22) to the logging entity. This is a warning, not an error; the LogEvent MUST be recorded, and the client MUST NOT retry the request.',
        "document_section": "4.12.3.1",
        "description": "Logging Services MUST verify the LogEvent signature before responding. A failed signature returns a warning, the LogEvent MUST be recorded, and the client MUST NOT retry the request.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_123": {
        "requirement_text": "VersionsLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the VersionsLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_124": {
        "requirement_text": "VersionsLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the VersionsLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_125": {
        "requirement_text": "PolicyChangeLogEvent members",
        "document_section": "4.12.3.7",
        "description": "Describes the required members for the PolicyChangeLogEvent.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_126": {
        "requirement_text": "Any element inside a PSAP that provides a call queue MUST deploy an ElementState notifier as described in Section 2.4.1.",
        "document_section": "4.6.6",
        "description": "Any element inside a PSAP providing a call queue MUST deploy an ElementState notifier (Section 2.4.1).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_127": {
        "requirement_text": "The PSAP MUST implement an NTP client interface for time of day information.",
        "document_section": "4.6.16",
        "description": "The PSAP MUST implement an NTP client interface for time of day synchronization.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_128": {
        "requirement_text": "The PSAP MAY provide a Policy Store as described in Section 3.3.1, in which case it MUST implement the server-side of the policy retrieval functions, and MAY provide the server-side of the policy storage function.",
        "document_section": "4.6.14",
        "description": "The PSAP MAY deploy a Policy Store (PS); if so, it MUST implement the server-side retrieval functions, and MAY implement the server-side storage function.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_129": {
        "requirement_text": "All DRs MUST contain common data elements (a prolog) that include: [see list]",
        "document_section": "3.7",
        "description": "All Discrepancy Reports (DRs) MUST contain a common set of data elements (a prolog).",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_130": {
        "requirement_text": "The services, unless specified otherwise, MUST support HTTP/1.1 (RFC 7230) [162] and SHOULD support HTTP/2.0 (RFC 7540) [197].",
        "document_section": "2.8.1",
        "description": "The services, unless specified otherwise, MUST support HTTP/1.1 and SHOULD support HTTP/2.0.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_131": {
        "requirement_text": "Clients MUST appropriately handle all status codes listed for each supported entry point, and MUST react appropriately to other status codes received, based on the first digit as per RFC 7231 [223] Section 6.",
        "document_section": "2.8.2",
        "description": "Clients MUST handle all listed status codes and react to other status codes based on the first digit as per RFC 7231, Section 6.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_132": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand",
        "document_section": "2.8.3",
        "description": "Implementations MUST ignore elements of data structures they do not understand.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_133": {
        "requirement_text": "Implementations MUST ignore elements of data structures they do not understand and MUST return 404 errors to entry points to the web interfaces they don't provide as a server.",
        "document_section": "2.8.3",
        "description": "Implementations MUST ignore unknown elements and MUST return 404 errors for unsupported web interfaces.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_134": {
        "requirement_text": 'Each Web Service MUST implement an entry point called "Versions".',
        "document_section": "2.8.3",
        "description": "Each Web Service MUST implement a mandatory entry point called 'Versions'.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_135": {
        "requirement_text": "Clients MUST retry transactions on redundant elements that that could not be completed on the initial element.",
        "document_section": "2.9",
        "description": "Clients MUST retry transactions on redundant elements if they could not be completed on the initial element.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_136": {
        "requirement_text": "Every implementation MUST be capable of using a DNS based implementation of redundant elements where more than one address may be returned for the URI provided.",
        "document_section": "2.9",
        "description": "Every implementation MUST be capable of using a DNS-based implementation for redundant elements when multiple addresses are returned for a URI.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_137": {
        "requirement_text": "Implementations MUST be capable of preferring the first returned address, and using the second, third and optionally additional addresses returned as representing redundant elements for the service.",
        "document_section": "2.9",
        "description": "Implementations MUST prefer the first returned address and use subsequent addresses as redundant elements for the service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_138": {
        "requirement_text": "Other mechanisms to achieve redundancy MAY be provided, but the DNS based mechanism MUST be supported by all services and clients of those services.",
        "document_section": "2.9",
        "description": "The DNS-based redundancy mechanism MUST be supported by all services and clients, although other mechanisms MAY be provided.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_139": {
        "requirement_text": "Entities implementing a notifier MUST implement RFC 3857 [26].",
        "document_section": "3.1.3.2",
        "description": "Entities implementing a notifier MUST implement RFC 3857.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_140": {
        "requirement_text": "The functional elements described in this document MUST support the discrepancy report (DR) function.",
        "document_section": "3.7",
        "description": "All functional elements described MUST support the discrepancy report (DR) function.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_141": {
        "requirement_text": "Each database, service, and agency MUST provide a Discrepancy Reporting web service.",
        "document_section": "3.7",
        "description": "Each database, service, and agency MUST provide a Discrepancy Reporting web service.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_142": {
        "requirement_text": 'Implementations MUST support (be capable of generating and using) algorithm "EdDSA" and MUST NOT use other algorithms except that implementations of the Logging Service and clients of the Logging Service MUST support (be capable of generating and using) unsigned (algorithm "none")',
        "document_section": "5.10",
        "description": "Implementations MUST support the 'EdDSA' algorithm and no others, except the Logging Service and its clients, which MUST also support the unsigned 'none' algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_143": {
        "requirement_text": 'If a Web Service request receives an "Unacceptable Algorithm" error, the client MUST make a new request on the Versions entry point and retry the request with a JWS that uses a signing algorithm acceptable to the Web Service.',
        "document_section": "5.10",
        "description": "If an 'Unacceptable Algorithm' error is received, the client MUST query the Versions entry point and retry the request using an acceptable JWS signing algorithm.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_144": {
        "requirement_text": 'When this document indicates that a set of Web Service interface parameters is a JWS (e.g., for LogEvents), the set of parameters is conveyed in the web service request as a string consisting of a JWS. The JWS is formed by applying the JWS algorithm to the set of parameters per the JWS standard [171]. The JWS Protected Header MUST contain exactly one "alg" field. The "alg" field MUST have a value acceptable to the Web Service. An unsigned (unprotected) JWS is indicated by an "alg" field set to the value "none". For signed LogEvents, and all other uses of JWS requiring signatures (e.g., policy documents), the JWS Protected Header MUST have its "alg" field set to a value acceptable to the Web Service that MUST NOT be "none" and MUST specify the signing entity\'s X.509 certificate and all intermediate certificates up to one signed by the trusted root58. The certificate is provided either by reference or by value. A certificate provided by value is contained in an "x5c" field. A certificate is provided by reference using the "x5u" and "x5t#256" fields. When the "x5u" field is present, it MUST contain a URL that is stable (resolvable) for a minimum of 10 years. The JWS Protected Header MAY contain other fields. When the "x5u" field is used, the "x5t#256" field MUST also be used, to allow an entity to more easily detect when a certificate chain needs to be retrieved.',
        "document_section": "5.10",
        "description": "Web Service parameters are conveyed as a JWS with one 'alg' field in the Protected Header. Signed JWS MUST use a non-'none' algorithm and include the X.509 certificate (by value: 'x5c' or reference: 'x5u'/'x5t#256').",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_145": {
        "requirement_text": "Implementations that access JWSs MUST support certificates (and chains) both by reference and by value; implementations that generate JWSs MAY use either.",
        "document_section": "5.10",
        "description": "Implementations accessing JWSs MUST support certificates by both reference and value; implementations generating JWSs MAY use either method.",
        "test_id": "",
        "subtests": [],
    },
    "RQ_PS_146": {
        "requirement_text": 'a JWS MUST use the Flat JSON serialization format (not JWS Compact Serialization and not General JWS JSON Serialization Syntax), and only the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448 (algorithm "EdDSA") [227] [228] signature method is used.',
        "document_section": "5.10",
        "description": "A JWS MUST use the Flat JSON serialization format. The only acceptable signature method is the Edwards-curve Digital Signature Algorithm (ECDSA) with Curve448 ('EdDSA').",
        "test_id": "",
        "subtests": [],
    },
}
