test_config:
  test_case_name: "TC_PS_004"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_PS_004_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_PS_004_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_004/TC_PS_004_pass.pcap"
      tests:
        - name: "PS_004_pass variation 1"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_no_parameters"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 2"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_policyType_with_policyId"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 3"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_policyType_TestCalls_and_policyQueueName"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 4"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_with_string_limit_and_start"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 5"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyOwner"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 6"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyType"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 7"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyQueueName"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 8"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyId"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_pass variation 9"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_correct"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" # If 200 OK then verify JSON body
    - name: "TC_PS_004_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_004/TC_PS_004_fail.pcap"
      tests:
        - name: "PS_004_fail variation 1"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_no_parameters"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 2"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_policyType_with_policyId"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 3"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_policyType_TestCalls_and_policyQueueName"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 4"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_with_string_limit_and_start"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 5"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyOwner"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 6"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyType"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 7"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyQueueName"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 8"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_incorrect_policyId"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
        - name: "PS_004_fail variation 9"
          test_id: "PS_004"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "../Test_files/HTTP_messages/HTTP_GET_policies/Retrieve_policy_JSON_correct"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" # If 200 OK then verify JSON body
