test_config:
  conformance:
    tests:
      - name: "CHE_004"
        variations:
          - name: "SIP_INVITE_for_callbacks"
            description: "Validate SIP INVITE sent by CHE for callbacks"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path:
                      "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml",
                    kwargs: {},
                    save_response_as: "CHE_004_var1_SEND_response.log",
                    save_log_as: "CHE_004_var1_SEND.log"
                  }
                  run_in_background: "False"
                - action: "receive"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "CHE_004_var1_RECEIVE_response.log",
                    save_log_as: "CHE_004_var1_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "manual"
                  type: ""
                  method: ""
                  instead: ""
                  prompt: "MANUAL ACTION REQUIRED - please trigger callback on CHE and press any key to continue..."
                  next_action: ""
          - name: "SIP_INVITE_for_outbound_calls"
            description: "Validate SIP INVITE sent by CHE for outbound calls"
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "CHE_004_var2_RECEIVE_response.log",
                    save_log_as: "CHE_004_var2_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "manual"
                  type: ""
                  method: ""
                  instead: ""
                  prompt: "MANUAL ACTION REQUIRED - please trigger outbound call to Test System on CHE \
                          and press any key to continue..."
                  next_action: ""
        requirements:
          - name: "RQ_CHE_003"
            variations: ["all"]
          - name: "RQ_CHE_004"
            variations: ["SIP_INVITE_for_callbacks"]
          - name: "RQ_CHE_005"
            variations: ["all"]