launch_config:
  output_folder: "/tmp/lab_tests/"        # Base folder where run artifacts will be saved
  global_config:
    lab_info: "templates/ALL_TESTS/lab_info.yaml"
    type: "conformance"
    log:
      level: "DEBUG"
      output_file: "ECRF-LVF_DEBUG.log"
    report_files:
      prefix: "ECRF-LVF"
      suffix: "ECRF-LVF_ALL_TESTS" # optional
      output_folder_path: "" # empty if you want to have reports in TS root dir or absolute path to the FOLDER
      detailed_view: true
      types:
        - "docx"
        - "pdf"
    id_summary:
      eng_name: "ENTER NAME"
      supplier:
        name: "ENTER SUPPLIER NAME"
        addr_line_1: "ENTER ADDRESS"
        addr_line_2: ""
        city: "ENTER CITY"
        state: "ENTER STATE"
        country: "ENTER COUNTRY"
        zip: "ENTER ZIP CODE"
        url: "ENTER URL"
      test_env:
        ts_version: "4.0.2"
        ixit_id: "11111"
        test_period_start: "ENTER CURRENT DATE" # ?
        test_period_end: "ENTER CURRENT DATE" # ?
        log_ref: "00001" # ?
        log_ret_date: "ENTER CURRENT DATE" # ?
    comments:
      - author: "ENTER AUTHOR NAME"
        comment: "THIS IS A TEST RUN ONLY, RESULTS ARE NOT VALID!"
  tests:
    - iut:
       type: "ECRF-LVF"
       name: "IF_ECRF-LVF_OSP"
       version: "0.0.0.1"
       test_period: "ENTER CURRENT DATE"
       date_of_receipt: "ENTER CURRENT DATE"
       location: "ENTER LOCATION"
       cs_id: "CS00001"
      lab_config: "templates/ALL_TESTS/ECRF-LVF/lab_config_ecrf_lvf.yaml"  # Path to lab_config for this test
      requirements: ["RQ_ECRF-LVF_009", "RQ_ECRF-LVF_022", "RQ_ECRF-LVF_046", "RQ_ECRF-LVF_053",
                     "RQ_ECRF-LVF_011", "RQ_ECRF-LVF_051", "RQ_ECRF-LVF_052", "RQ_ECRF-LVF_054",
                     "RQ_ECRF-LVF_043", "RQ_ECRF-LVF_050", "RQ_ECRF-LVF_003", "RQ_ECRF-LVF_004",
                     "RQ_ECRF-LVF_015"]