test_config: "test_files/configs/BCF_001_Sebastian/test_config.yaml"
lab_config: "test_files/configs/BCF_001_Sebastian/lab_config.yaml"
run_config: "test_files/configs/BCF_001_Sebastian/run_config.yaml"