lab_config:
  # SW: add following fields:
  pca_certificate_file: ""
  pca_certificate_key: ""
  ip: "192.168.1.13"
  entities:
    - name: "OSP"
      mode: "STUB_SERVER"
      function: "OSP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_OSP_O-BCF-1"
          fqdn: ""
          ip: "192.168.1.133"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP" # ["TCP", "UDP"]
    - name: "O-BCF-1"
      mode: "REAL_DEVICE"
      function: "BCF"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_O-BCF-1_OSP"
          fqdn: ""
          ip: "192.168.1.14"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP" # ["mTLSv1.3", "mTLSv1.2", "TCP", "UDP"]
        - name: "IF_O-BCF-1_ESRP-1"
          fqdn: ""
          ip: "192.168.1.14"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP" # ["mTLSv1.3", "mTLSv1.2", "TCP", "UDP"]
    - name: "ESRP-1"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP-1_O-BCF-1"
          fqdn: ""  # optional
          ip: "192.168.1.134"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.1.1"  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP" # ["TCP", "UDP"]