launch_config:
  output_folder: "/tmp/lab_tests/"
  global_config:
    lab_info: "templates/ALL_TESTS/lab_info.yaml"
    type: "conformance"
    log:
      level: "DEBUG"
      output_file: "BRIDGE_DEBUG.log"
    report_files:
      prefix: "BRIDGE"
      suffix: "BRIDGE_ALL_TESTS" # optional
      output_folder_path: "" # empty if you want to have reports in TS root dir or absolute path to the FOLDER
      detailed_view: true
      types:
        - "docx"
        - "pdf"
    id_summary:
      eng_name: "ENTER NAME"
      supplier:
        name: "ENTER SUPPLIER NAME"
        addr_line_1: "ENTER ADDRESS"
        addr_line_2: ""
        city: "ENTER CITY"
        state: "ENTER STATE"
        country: "ENTER COUNTRY"
        zip: "ENTER ZIP CODE"
        url: "ENTER URL"
      test_env:
        ixit_id: "11111"
        test_method: "test_method"
        test_period_start: "ENTER CURRENT DATE" # ?
        test_period_end: "ENTER CURRENT DATE" # ?
        log_ref: "00001" # ?
        log_ret_date: "ENTER CURRENT DATE" # ?
    comments:
      - author: "ENTER AUTHOR NAME"
        comment: "THIS IS A TEST RUN ONLY, RESULTS ARE NOT VALID!"
  tests:
   - iut:
       type: "BRIDGE"
       name: "IF_BRIDGE_OSP"
       version: "0.0.0.1"
       date_of_receipt: "ENTER CURRENT DATE"
       location: "ENTER LOCATION"
       cs_id: "CS00001"
     lab_config: "templates/ALL_TESTS/BRIDGE/lab_config_bridge.yaml"
     requirements: ['RQ_BRG_001', 'RQ_BRG_012', 'RQ_BRG_053', 'RQ_BRG_042', 'RQ_BRG_092', 'RQ_BRG_100', 'RQ_BRG_101', 'RQ_BRG_102']
