"run_config":
  "global":
    "type": "conformance"
    "id_summary":
      "lab":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
        "eng_name": ""
        "accred_status": ""
        "accred_ref": ""
        "accred_auth": ""
      "supplier":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
      "iut":
        "type": ""
        "name": ""
        "version": ""
        "test_period": ""
        "date_of_receipt": ""
        "location": ""
        "cs_id": ""
        "test_env": ""
      "test_env":
        "ixit_id": ""
        "spec_name": ""
        "spec_version": ""
        "ts_version": ""
        "test_period_start": ""
        "test_period_end": ""
        "log_ref": ""
        "log_ret_date": ""
    "comments":
    - "author": ""
      "comment": ""
    "report_files":
      "output_folder_path": ""
      "filename": "test_report"
      detailed_view: true
      "types":
      - "pdf"
      - "docx"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
    "response_timeout": 30
  "tests":
  - "name": "ESRP_006"
    "requirements":
    - "name": "RQ_ESRP_042"
      "variations":
      - "all"
    - "name": "RQ_ESRP_043"
      "variations":
      - "all"
    - "name": "RQ_ESRP_045"
      "variations":
      - "all"
    - "name": "RQ_ESRP_046"
      "variations":
      - "all"
    - "name": "RQ_ESRP_048"
      "variations":
      - "all"
    - "name": "RQ_ESRP_049"
      "variations":
      - "all"
    "variations":
    - "name": "SIP_INVITE_exiting_ESRP"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "receive"
          "prep_steps": []
          "type": "HTTP"
          "method": "GET"
          "response_code": "200"
          "http_url": "/lost"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/findServiceResponse"
          "sipp_scenario": {}
          "run_in_background": "True"
        - "action": "receive"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml"
            "kwargs": {}
            "save_response_as": "ESRP_006_RECEIVE_response.log"
            "save_log_as": "ESRP_006_RECEIVE.log"
          "run_in_background": "True"
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_location_PIDF-LO_Boundary1_without_identifiers.xml"
            "kwargs": {}
            "save_response_as": "ESRP_006_SEND_response.log"
            "save_log_as": "ESRP_006_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS1_ESRP"
        "dst_interface": "IF_ESRP_TS1"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": "IF_ESRP_TS-ECRF"
        "dst_interface": "IF_TS-ECRF_ESRP"
        "http_request_method": "GET"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
        "sip_method": "INVITE"
