test_config:
  conformance:
    tests:
      - name: "ESRP_006"
        variations:
          - name: "SIP_INVITE_exiting_ESRP"
            description: "Verify SIP INVITE exiting ESRP"
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: "/lost"  # part after f.e. http://IP:PORT
                  body: "file.test_files/HTTP_messages/HTTP_LoST/findServiceResponse"
                  sipp_scenario: {}
                  run_in_background: "True"
                - action: "receive"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "ESRP_006_RECEIVE_response.log",
                    save_log_as: "ESRP_006_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/\
                                        SIP_INVITE_location_PIDF-LO_Boundary1_without_identifiers.xml",
                    kwargs: {},
                    save_response_as: "ESRP_006_SEND_response.log",
                    save_log_as: "ESRP_006_SEND.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_ESRP_042"
            variations: ["all"]
          - name: "RQ_ESRP_043"
            variations: ["all"]
          - name: "RQ_ESRP_045"
            variations: ["all"]
          - name: "RQ_ESRP_046"
            variations: ["all"]
          - name: "RQ_ESRP_048"
            variations: ["all"]
          - name: "RQ_ESRP_049"
            variations: ["all"]