lab_config:
  entities:
    - name: "FE_OBCF-1"
      type: "BCF"
      fqdn: ""
      certificate_file: "test_files/test_certs/esrp-1.test.example.com.crt"
      certificate_key: "test_files/test_certs/esrp-1.test.example.com.crt"
      interfaces:
        - name: "IF_O-BCF-1_OSP"
          fqdn: "obcf1.test.example.com"
          ip: "192.168.200.200"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.200.1"  #  Leave empty if not required
          dns: ["192.168.200.1"]  #  Leave empty if not required
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_O-BCF-1_ESRP-1"
          fqdn: "obcf1.test.example.com"
          ip: "192.168.1.10"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_O-BCF-1_LS"
          fqdn: "obcf1.test.example.com"
          ip: "192.168.1.10"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_O-BCF-1_PS"
          fqdn: "obcf1.test.example.com"
          ip: "192.168.1.10"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
    - name: "ESRP-XYZ-1"
      type: "ESRP"
      fqdn: "esrp1.test.example.com"
      certificate_file: "test_files/test_certs/esrp-1.test.example.com.crt"
      certificate_key: "test_files/test_certs/esrp-1.test.example.com.crt"
      interfaces:
        - name: "IF_ESRP-1_O-BCF-1"
          fqdn: ""  # optional
          ip: "192.168.1.11"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_ESRP-1_LIS"
          fqdn: ""
          ip: "192.168.1.11"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_ESRP-1_ECRF-LVF"
          fqdn: ""
          ip: "192.168.1.11"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_ESRP-1_LS"
          fqdn: ""
          ip: "192.168.1.11"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_ESRP-1_PS"
          fqdn: ""
          ip: "192.168.1.10"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060
        - name: "IF_ESRP-1_T-BCF-1"
          fqdn: ""
          ip: "192.168.1.11"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.200.1"  # Optional
          dns: ["192.168.200.1"]  # Optional
          port_mapping:
            - protocol: "TLSv1.3"
              port: 5061
            - protocol: "HTTP"
              port: 8080
            - protocol: "SIP"
              port: 5060