run_config:
  global:
    response_timeout: 30
    type: "conformance"
    report_files:
      - type: "pdf"
        path: "CTR.pdf"
    log:
      level: "DEBUG"
      output_file: "test_files/logs/logger.log"
  tests:
    - name: "Test of BCF element"
      requirements:
        - name: "RQ_BCF_001"
          variations: ["Name of the variation 1", ]
        - name: "RQ_BCF_002"
          variations: ["Name of the variation 1", "Name of the variation 2"]
      variations:
        - name: "Name of the variation 1"
          mode: "" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_O-BCF-1_ESRP_1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed

