# mypy.ini
[mypy]
explicit_package_bases = True
ignore_missing_imports = True
pretty = True
show_error_codes = True

# Requests, etc.
[mypy-requests.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-dateutil.*]
ignore_missing_imports = True


# Ignore dynamic test logic
[mypy-test_suite.tests.*]
ignore_errors = True

[mypy-test_suite.services.config.config_service_old]
ignore_errors = True


# Relax parsing helpers (SDP etc.)
[mypy-test_suite.services.aux_services.*]
ignore_errors = True

[mypy-test_suite.services.stub_server.sip_service.*]
ignore_errors = True

[mypy-test_suite.services.stub_server.http.*]
ignore_errors = True

[mypy-test_suite.services.stub_server.sip_service.extra_logic.*]
disable_error_code = assignment,attr-defined,union-attr

[mypy-test_suite.services.config.extra_checks.*]
disable_error_code = assignment,attr-defined,union-attr