test_config:
  conformance:
    tests:
      - name: "ESRP_007"
        variations:
          - name: "Send_DR_on_malformed_SIP_from_BCF"
            description: "Validate Discrepancy Report function support"
            interfaces:
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_SAL_ESRP"
                port_names: []
              - name: "IF_DR_ESRP"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_DR_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "True"
                - action: "receive"
                  if_name: "IF_SAL_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "lab_config['lab_config']['entities']"
                        "where_field": "name"
                        "where_value": "DR"
                        "extract_field": "interfaces"
                      "save_result_as": "var.ts_dr_interfaces"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_dr_interfaces"
                        "where_field": "name"
                        "where_value": "IF_DR_ESRP"
                        "extract_field": "fqdn"
                      "save_result_as": "var.ts_dr_fqdn"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_dr_interfaces"
                        "where_field": "name"
                        "where_value": "IF_DR_ESRP"
                        "extract_field": "ip"
                      "save_result_as": "var.ts_dr_ip"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_dr_interfaces"
                        "where_field": "name"
                        "where_value": "IF_DR_ESRP"
                        "extract_field": "port_mapping"
                      "save_result_as": "var.ts_dr_port_mapping"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_dr_port_mapping"
                        "where_field": "name"
                        "where_value": "IF_DR_ESRP_HTTP_8080_TCP"
                        "extract_field": "port"
                      "save_result_as": "var.ts_dr_port"
                    - method_name: "generate_url"
                      kwargs:
                        protocol: "http"
                        address: "list.[var.ts_dr_fqdn, var.ts_dr_ip]"
                        port: "var.ts_dr_port"
                        path: "/dr"
                      save_result_as: "var.ts_dr_url"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                          "input_file": "file.test_suite/test_files/JSON/service_agency_locator/SAL_response_DR_server_v010.3f.4.0.2.json"
                          "param_name": "TEST_SYSTEM_DR_URI"
                          "value": "var.ts_dr_url"
                          "output_file": "file./tmp/ESRP_007/SAL_response_DR_server_v010.3f.4.0.2.json"
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: "file./tmp/ESRP_007/SAL_response_DR_server_v010.3f.4.0.2.json"
                  sipp_scenario: {}
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_BCF_incorrect.xml",
                    kwargs: {},
                    save_response_as: "ESRP_007_RECEIVE_response.log",
                    save_log_as: "ESRP_007_RECEIVE.log"
                  }
                  run_in_background: "False"
            filtering_options: # optional
                - message_type: "stimulus" # stimulus/output/other
                  src_interface: "IF_BCF_ESRP"
                  dst_interface: "IF_ESRP_BCF"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "output" # stimulus/output/other
                  src_interface: "IF_ESRP_DR"
                  dst_interface: "IF_DR_ESRP"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "POST" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_ESRP_SAL"
                  dst_interface: "IF_SAL_ESRP"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "GET" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
        requirements:
          - name: "RQ_ESRP_186"
            variations: ["all"]