test_config:
  conformance:
    tests:
      - name: "ECRF_LVF_001"
        variations:
          - name: "Self-signed_certificate"
            description: "Validate rejecting certificates not signed by PCA"
            interfaces:
              - name: "IF_ESRP_ECRF-LVF"
                port_names: ["IF_ESRP_ECRF-LVF_HTTP_4443_TLSv1.2"]
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_BCF"
                  if_port_name: "IF_ESRP_ECRF-LVF_HTTP_4443_TLSv1.2"  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ECRF-LVF"
                        extract_field: "api"
                      "save_result_as": "var.ecrf_lvf_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.ecrf_lvf_api"
                        extract_field: "http_url_suffix_lost"
                      "save_result_as": "var.http_url"
                    - "method_name": "generate_random_certificate"
                      "kwargs":
                        "output_certificate_file": "file./tmp/temp.crt"
                        "output_key_file": "file./tmp/temp.key"
                  type: "HTTP"
                  method: "POST"
                  response_code: ""
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/listServices_urn-service-sos"
                  sipp_scenario: {}
                  certificate_file: "file./tmp/temp.crt"
                  certificate_key: "file./tmp/temp.key"
                  run_in_background: "False"
          - name: "PCA-signed_certificate"
            description: "Validate accepting PCA-signed certificates"
            interfaces:
              - name: "IF_ESRP_ECRF-LVF"
                port_names: ["IF_ESRP_ECRF-LVF_HTTP_4443_TLSv1.2"]
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_BCF"
                  if_port_name: "IF_ESRP_ECRF-LVF_HTTP_4443_TLSv1.2"  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ECRF-LVF"
                        extract_field: "api"
                      "save_result_as": "var.ecrf_lvf_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.ecrf_lvf_api"
                        extract_field: "http_url_suffix_lost"
                      "save_result_as": "var.http_url"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "TS",
                             extract_field: 'certificate_file'
                      }
                      save_result_as: "var.cert"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "TS",
                             extract_field: 'certificate_key'
                      }
                      save_result_as: "var.key"
                  type: "HTTP"
                  method: "POST"
                  response_code: ""
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/listServices_urn-service-sos"
                  sipp_scenario: {}
                  certificate_file: "var.cert"
                  certificate_key: "var.key"
                  run_in_background: "False"
        requirements:
          - name: "RQ_ECRF_009"
            variations: ["all"]