test_config:
  conformance:
    tests:
      - name: "BCF_005"
        variations:
          - name: "SIP_INVITE_log_event"
            description: "Test BCF logging for incoming SIP INVITE (CallSignalingMessageLogEvent only)."
            interfaces:
              - name: "IF_OSP_BCF"
                port_names: []
              - name: "IF_BCF_LOG"
                port_names: []
              - name: "IF_ESRP_BCF"
                port_names: []
              - name: "IF_LOG_BCF"
                port_names: []
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_OSP_BCF"
                dst_interface: "IF_BCF_OSP"
                sip_method: "INVITE"
                http_request_method: ""
                response_status_code: ""
                header_contains: ""
                body_contains: ""
              - message_type: "other"
                src_interface: "IF_BCF_LOG"
                dst_interface: "IF_LOG_BCF"
                sip_method: ""
                http_request_method: "POST"
                response_status_code: "201"
                header_contains: "/LogEvents"
                body_contains: ""
              - message_type: "output"
                src_interface: "IF_BCF_ESRP"
                dst_interface: "IF_ESRP_BCF"
                sip_method: "INVITE"
                http_request_method: ""
                response_status_code: ""
                header_contains: ""
                body_contains: ""
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  if_name: "IF_ESRP_BCF"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                    },
                    save_response_as: "BCF_005_V1_ESRP_INVITE_response.log",
                    save_log_as: "BCF_005_V1_ESRP_INVITE.log"
                  }
                  run_in_background: "True"
                - action: "receive"
                  if_name: "IF_LOG_BCF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "LOG",
                             extract_field: 'interfaces'
                      }
                      save_result_as: "var.log_interfaces"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "var.log_interfaces",
                             where_field: "name",
                             where_value: "IF_LOG_BCF",
                             extract_field: 'fqdn'
                      }
                      save_result_as: "var.log_fqdn"
                    - method_name: "generate_identifier"
                      kwargs: {
                             identifier_type: "logid",
                             fqdn: "var.log_fqdn"
                      }
                      save_result_as: "var.logid"
                    - method_name: "save_to_file"
                      kwargs:
                        input_str: '{"logEventId": "test"}'
                        filename: "/tmp/bcf_005/logeventid.json"
                    - method_name: "modify_json_file"
                      kwargs:
                        json_input_file: "file./tmp/bcf_005/logeventid.json"
                        param_name: "logEventId"
                        value: "var.logid"
                        output_file: "file./tmp/bcf_005/logeventid.json"
                  type: "HTTP"
                  method: ["POST", "GET"]
                  response_code: ["201", "200"]
                  http_url: ["/LogEvents", "/Versions"] # part after f.e. http://IP:PORT
                  sipp_scenario: {}
                  run_in_background: "True"
                  body: ["file./tmp/bcf_005/logeventid.json", "file.test_suite/test_files/JSON/versions/Logging_Service_Versions_object_example_v010.3f.5.0.0.json"]
                - action: "send"
                  prep_steps: []
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                    kwargs: {},
                    save_response_as: "BCF_005_V1_OSP_INVITE_response.log",
                    save_log_as: "BCF_005_V1_OSP_INVITE.log"
                  }
                  run_in_background: "False"
          - name: "SIP_MESSAGE_log_event"
            description: "Test BCF logging for incoming SIP MESSAGE (MessageLogEvent and CallSignalingMessageLogEvent)."
            interfaces:
              - name: "IF_OSP_BCF"
                port_names: []
              - name: "IF_BCF_LOG"
                port_names: []
              - name: "IF_ESRP_BCF"
                port_names: []
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_OSP_BCF"
                dst_interface: "IF_BCF_OSP"
                sip_method: "MESSAGE"
                http_request_method: ""
                response_status_code: ""
                header_contains: ""
                body_contains: ""
              - message_type: "output"
                src_interface: "IF_BCF_ESRP"
                dst_interface: "IF_ESRP_BCF"
                sip_method: "MESSAGE"
                http_request_method: ""
                response_status_code: ""
                header_contains: ""
                body_contains: ""
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  if_name: "IF_ESRP_BCF"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_MESSAGE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_005_V2_ESRP_MESSAGE_response.log",
                    save_log_as: "BCF_005_V2_ESRP_MESSAGE.log"
                  }
                  run_in_background: "True"
                - action: "receive"
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                        config_part: "lab_config['lab_config']['entities']",
                        where_field: "name",
                        where_value: "LOG",
                        extract_field: 'interfaces'
                      }
                      save_result_as: "var.log_interfaces"
                    - method_name: "extract_from_config"
                      kwargs: {
                        config_part: "var.log_interfaces",
                        where_field: "name",
                        where_value: "IF_LOG_BCF",
                        extract_field: 'fqdn'
                      }
                      save_result_as: "var.log_fqdn"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "logid",
                        fqdn: "var.log_fqdn"
                      }
                      save_result_as: "var.logid"
                    - method_name: "generate_str"
                      kwargs:
                        string_to_modify: '{"logEventId": "{0}"}'
                        variables: "list.[var.logid]"
                      save_result_as: "file./tmp/bcf_005/logeventid.json"
                  if_name: "IF_LOG_BCF"
                  if_port_name: ""  # Optional
                  type: "HTTP"
                  method: ["POST", "GET"]
                  response_code: ["201", "200"]
                  http_url: ["/LogEvents", "/Versions"] # part after f.e. http://IP:PORT
                  sipp_scenario: {}
                  run_in_background: "True"
                  body: ["file./tmp/bcf_005/logeventid.json", "file.test_suite/test_files/JSON/versions/Logging_Service_Versions_object_example_v010.3f.5.0.0.json"]
                - action: "send"
                  prep_steps: []
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_MESSAGE/SIP_MESSAGE_from_OSP.xml",
                    kwargs: {},
                    save_response_as: "BCF_005_V2_OSP_MESSAGE_response.log",
                    save_log_as: "BCF_005_V2_OSP_MESSAGE.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_BCF_080"
            variations: ["all"]
          - name: "RQ_BCF_081"
            variations: ["all"]
          - name: "RQ_BCF_129"
            variations: ["all"]
          - name: "RQ_BCF_130"
            variations: ["all"]
          - name: "RQ_BCF_160"
            variations: ["all"]
          - name: "RQ_BCF_161"
            variations: ["all"]
          - name: "RQ_BCF_162"
            variations: ["all"]
