test_config:
  conformance:
    tests:
      - name: "BCF_006"
        variations:
          - name: "SIP_INVITE_Initial_Dialog_ACK"
            description: "TD Variation 1: Standard INVITE flow. BCF must ACK the 200 OK from ESRP."
            interfaces:
              - name: "IF_OSP_BCF"
                port_names: []
              - name: "IF_ESRP_BCF"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_ESRP_BCF"
                  if_port_name: ""
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE_RESPONSE_ACK.xml",
                    kwargs: {},
                    save_response_as: "BCF_006_var1_ESRP_response.log",
                    save_log_as: "BCF_006_var1_ESRP.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                    kwargs: {},
                    save_response_as: "BCF_006_var1_OSP_response.log",
                    save_log_as: "BCF_006_var1_OSP.log"
                  }
                  run_in_background: "False"
            filtering_options: # optional
                - message_type: "stimulus" # stimulus/output/other
                  src_interface: "IF_OSP_BCF"
                  dst_interface: "IF_BCF_OSP"
                  sip_method: "ACK" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "output" # stimulus/output/other
                  src_interface: "IF_BCF_ESRP"
                  dst_interface: "IF_ESRP_BCF"
                  sip_method: "ACK" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
          - name: "SIP_Re_INVITE_with_BYE_Termination"
            description: "TD Variation 2: Standard BYE flow. Verify BCF completes transaction without ACK."
            interfaces:
              - name: "IF_OSP_BCF"
                port_names: []
              - name: "IF_ESRP_BCF"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_ESRP_BCF"
                  if_port_name: ""
                  prep_steps: []
                  type: "SIP"
                  method: "BYE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_ReINVITE_BYE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_006_var2_ESRP_response.log",
                    save_log_as: "BCF_006_var2_ESRP.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""
                  prep_steps: []
                  type: "SIP"
                  method: "BYE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_ReINVITE_BYE.xml",
                    kwargs: {},
                    save_response_as: "BCF_006_var2_OSP_response.log",
                    save_log_as: "BCF_006_var2_OSP.log"
                  }
                  run_in_background: "False"
            filtering_options: # optional
                - message_type: "stimulus" # stimulus/output/other
                  src_interface: "IF_OSP_BCF"
                  dst_interface: "IF_BCF_OSP"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "output" # stimulus/output/other
                  src_interface: "IF_BCF_ESRP"
                  dst_interface: "IF_ESRP_BCF"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
        requirements:
          - name: "RQ_BCF_194"
            variations: ["all"]