test_config:
  conformance:
    tests:
      - name: "LOG_009"
        "preamble_list": [
          {
            "method_name": "run_stub_service",
            "kwargs": {
                        "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/sip_service/CALLS/Text_call_recording_session.xml",
                        "sip_service_kwargs": {
                                               "set": {
                                                        "LOG_SRS_username": "recorder",
                                                        "SIP_call_id": "recording_a56e556d871@bcf.state.pa.us",
                                                        "Call_ID": "urn:emergency:uid:callid:a56e556d871:bcf.state.pa.us",
                                                        "Incident_ID": "urn:emergency:uid:incidentid:a56e556d871:bcf.state.pa.us",
                                                        "Text_host1": "Host1_test_message",
                                                        "Text_host2": "Host2_test_message"
                                               }
                        },
                        "if_name": "IF_ESRP_LOG-rec"
            }
          },
          {
            "method_name": "prepare_rtt_conversation",
            "required_for": [ "RQ_LOG_037", "RQ_LOG_038" ],
            "kwargs": {
              "list_of_procedures": [
                "CallStartLogEvent_object_example_v010.3f.3.0.1.json",
                "CallSignalingMessageLogEvent_example_v010.3f.3.0.1.json",
                "CallEndLogEvent_object_example_v010.3f.3.0.1.json"
              ],
              "config_vars": {
                "callId": "urn:emergency:uid:callid:a56e556d871:bcf.state.pa.us",
                "incidentId": "urn:emergency:uid:incidentid:a56e556d871:bcf.state.pa.us"
              },
              "url": "/LogEvents",
              "expected_response_code": "201",
              "conversation_url": "/Conversations?callId={callId}",
              "expected_get_response_code": "200",
              "if_name": "IF_ESRP_LOG-write"
            }
          },
          {
            "method_name": "prepare_rtt_conversation",
            "required_for": [ "RQ_LOG_037", "RQ_LOG_038" ],
            "kwargs": {
              "list_of_procedures": [
                "CallStartLogEvent_object_example_v010.3f.3.0.1.json",
                "CallSignalingMessageLogEvent_example_v010.3f.3.0.1.json",
                "CallEndLogEvent_object_example_v010.3f.3.0.1.json"
              ],
              "config_vars": {
                "callId": "urn:emergency:uid:callid:a56e556d871notext:bcf.state.pa.us",
                "incidentId": "urn:emergency:uid:incidentid:a56e556d871notext:bcf.state.pa.us"
              },
              "url": "/LogEvents",
              "expected_response_code": "201",
              "conversation_url": "/Conversations?callId={callId}",
              "expected_get_response_code": "200",
              "if_name": "IF_ESRP_LOG-write"
            }
          }
        ]
        variations:
          - name: "Correct_CallIdentifier"
            description: "Validate 2xx response for existing CallIdentifier -> Expect 200 OK + JSON string"
            interfaces:
              - name: "IF_ESRP_LOG-read"
                port_names: [ ]
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LOG-read"
                  if_port_name: ""
                  prep_steps: [ ]
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: "/Conversations?callId=urn:emergency:uid:callid:a56e556d871:bcf.state.pa.us"
                  body: ""
                  sipp_scenario: { }
                  run_in_background: "False"
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_ESRP_LOG-read"
                dst_interface: "IF_LOG-read_ESRP"
                http_request_method: "GET"
                response_status_code: "200"
                header_contains: ""
                body_contains: ""

          - name: "Unknown_CallID"
            description: "Validate 4xx error response for Unknown correct CallID"
            interfaces:
              - name: "IF_ESRP_LOG-read"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LOG-read"
                  if_port_name: ""
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "4xx"
                  http_url: "/Conversations?callId=urn:emergency:uid:callid:unknownid99:bcf.state.pa.us"
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "False"
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_ESRP_LOG-read"
                dst_interface: "IF_LOG-read_ESRP"
                http_request_method: "GET"
                response_status_code: "4xx"

          - name: "CallID_with_incorrect_urn_ID"
            description: "Validate 4xx error response for Call ID with incorrect urn ID"
            interfaces:
              - name: "IF_ESRP_LOG-read"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LOG-read"
                  if_port_name: ""
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "4xx"
                  http_url: "/Conversations?callId=urn:emergency:uid:callincorrectid:9f3a2k7m1c:bcf.state.pa.us"
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "False"
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_ESRP_LOG-read"
                dst_interface: "IF_LOG-read_ESRP"
                http_request_method: "GET"
                response_status_code: "4xx"

          - name: "CallID_with_incorrect_string_ID"
            description: "Validate 4xx error response for Call ID with incorrect string ID"
            interfaces:
              - name: "IF_ESRP_LOG-read"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LOG-read"
                  if_port_name: ""
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "4xx"
                  http_url: "/Conversations?callId=urn:emergency:uid:callid:1.bcf.state.pa.us"
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "False"
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_ESRP_LOG-read"
                dst_interface: "IF_LOG-read_ESRP"
                http_request_method: "GET"
                response_status_code: "4xx"

          - name: "CallID_with_incorrect_FQDN"
            description: "Validate 4xx error response for Call ID with incorrect FQDN"
            interfaces:
              - name: "IF_ESRP_LOG-read"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LOG-read"
                  if_port_name: ""
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "4xx"
                  http_url: "/Conversations?callId=urn:emergency:uid:callid:a56e556d871:bcf"
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "False"
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_ESRP_LOG-read"
                dst_interface: "IF_LOG-read_ESRP"
                http_request_method: "GET"
                response_status_code: "4xx"

          - name: "Call_without_text"
            description: "Validate 464 'No Text In This Call' error response for Call ID of call without text messages"
            interfaces:
              - name: "IF_ESRP_LOG-read"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LOG-read"
                  if_port_name: ""
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "464"
                  http_url: "/Conversations?callId=urn:emergency:uid:callid:a56e556d871notext:bcf.state.pa.us"
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "False"
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_ESRP_LOG-read"
                dst_interface: "IF_LOG-read_ESRP"
                http_request_method: "GET"
                response_status_code: "464"
        requirements:
          - name: "RQ_LOG_037"
            variations: [
              "Unknown_CallID",
              "CallID_with_incorrect_urn_ID",
              "CallID_with_incorrect_string_ID",
              "CallID_with_incorrect_FQDN",
              "Call_without_text"
            ]
          - name: "RQ_LOG_038"
            variations: [ "Correct_CallIdentifier" ]