test_config:
  conformance:
    tests:
      - name: "BRIDGE_003"
        variations:
          - name: "Handling_multi-party_aware_and_unaware_endpoints_in_the_same_session"
            description: "Validate if Bridge is capable of handling multi-party aware and multi-party unaware endpoints 
                          in the same session"
            interfaces:
              - name: "IF_OSP_BCF"
                port_names: []
              - name: "IF_OSP_CHFE"
                port_names: []
              - name: "IF_OSP_BRIDGE"
                port_names: []
              - name: "IF_BCF_OSP"
                port_names: []
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_ESRP_BCF"
                port_names: []
              - name: "IF_ESRP_CHFE"
                port_names: []
              - name: "IF_BRIDGE_CHFE"
                port_names: []
              - name: "IF_BRIDGE_OSP"
                port_names: []
              - name: "IF_CHFE_OSP"
                port_names: []
              - name: "IF_CHFE_ESRP"
                port_names: []
              - name: "IF_CHFE_BRIDGE"
                port_names: []
              - name: "IF_CHFE_TS-CA"
                port_names: []
              - name: "IF_TS-CA_CHFE"
                port_names: []
            params:
              messages:
                  # Test System BCF
                - action: "receive"
                  if_name: "IF_BCF_OSP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_OSP_BCF"
                      "save_result_as": "var.IF_OSP_BCF"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_OSP"
                      "save_result_as": "var.IF_BCF_OSP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_ESRP_BCF"
                      "save_result_as": "var.IF_ESRP_BCF"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/sip_service/FEs/BCF_simple_call.xml",
                    kwargs: {
                      set: {
                        IF_OSP_BCF: "var.IF_OSP_BCF",
                        IF_BCF_OSP: "var.IF_BCF_OSP",
                        IF_BCF_ESRP: "var.IF_BCF_ESRP",
                        IF_ESRP_BCF: "var.IF_ESRP_BCF",
                      }
                    },
                    save_response_as: "BCF_BRIDGE_003_response.log",
                    save_log_as: "BCF_BRIDGE_003.log"
                  }
                  run_in_background: "True"

                  # Test System ESRP
                - action: "receive"
                  if_name: "IF_ESRP_BCF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_OSP_BCF"
                      "save_result_as": "var.IF_OSP_BCF"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_CHFE_ESRP"
                      "save_result_as": "var.IF_CHFE_ESRP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_ESRP_CHFE"
                      "save_result_as": "var.IF_ESRP_CHFE"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ESRP"
                        extract_field: "api"
                      "save_result_as": "var.api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.api"
                        extract_field: "conference_id"
                      "save_result_as": "var.conference_id"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHFE"
                        extract_field: "api"
                      "save_result_as": "var.api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.api"
                        extract_field: "tel_number"
                      "save_result_as": "var.CHFE_tel"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "OSP"
                        extract_field: "api"
                      "save_result_as": "var.api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.api"
                        extract_field: "tel_number"
                      "save_result_as": "var.OSP_tel"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/sip_service/FEs/ESRP_simple_call.xml",
                    kwargs: {
                      set: {
                        IF_OSP_BCF: "var.IF_OSP_BCF",
                        IF_BCF_ESRP: "var.IF_BCF_ESRP",
                        IF_CHFE_ESRP: "var.IF_CHFE_ESRP",
                        IF_ESRP_CHFE: "var.IF_ESRP_CHFE",
                        conference_id: "var.conference_id",
                        CHFE_tel: "var.CHFE_tel",
                        OSP_tel: "var.OSP_tel"
                      }
                    },
                    save_response_as: "ESRP_BRIDGE_003_response.log",
                    save_log_as: "ESRP_BRIDGE_003.log"
                  }
                  run_in_background: "True"

                # Test System CHFE (Transfer-to)
                - action: "receive"
                  if_name: "IF_CHFE_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_OSP_BCF"
                      "save_result_as": "var.IF_OSP_BCF"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BRIDGE_CHFE"
                      "save_result_as": "var.IF_BRIDGE_CHFE"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_CHFE_BRIDGE"
                      "save_result_as": "var.IF_CHFE_BRIDGE"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_CHFE"
                      "save_result_as": "var.IF_BCF_CHFE"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_CHFE_BCF"
                      "save_result_as": "var.IF_CHFE_BCF"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "TS-CA"
                        extract_field: "api"
                      "save_result_as": "var.api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.api"
                        extract_field: "conference_id"
                      "save_result_as": "var.conference_id"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHFE"
                        extract_field: "api"
                      "save_result_as": "var.api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.api"
                        extract_field: "tel_number"
                      "save_result_as": "var.CHFE_tel"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/sip_service/BRIDGE_003/CHFE_BRIDGE_003.xml",
                    kwargs: {
                      set: {
                        conference_id: "var.conference_id",
                        IF_OSP_BCF: "var.IF_OSP_BCF",
                        IF_BRIDGE_CHFE: "var.IF_BRIDGE_CHFE",
                        IF_CHFE_BRIDGE: "var.IF_CHFE_BRIDGE",
                        TS-CHFE_tel: "var.CHFE_tel",
                        IF_BCF_CHFE: "var.IF_BCF_CHFE",
                        IF_CHFE_BCF: "var.IF_CHFE_BCF"
                      }
                    },
                    save_response_as: "CHFE_BRIDGE_003_response.log",
                    save_log_as: "CHFE_BRIDGE_003.log"
                  }
                  run_in_background: "True"

                  # Test System OSP
                - action: "send"
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_OSP_CHFE"
                      "save_result_as": "var.IF_OSP_CHFE"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_CHFE_OSP"
                      "save_result_as": "var.IF_CHFE_OSP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_OSP_BRIDGE"
                      "save_result_as": "var.IF_OSP_BRIDGE"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BRIDGE_OSP"
                      "save_result_as": "var.IF_BRIDGE_OSP"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "OSP"
                        extract_field: "api"
                      "save_result_as": "var.api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.api"
                        extract_field: "tel_number"
                      "save_result_as": "var.OSP_tel"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHFE"
                        extract_field: "api"
                      "save_result_as": "var.api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.api"
                        extract_field: "tel_number"
                      "save_result_as": "var.CHFE_tel"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/sip_service/BRIDGE_003/OSP_BRIDGE_003.xml",
                    kwargs: {
                      set: {
                             OSP_tel: "var.OSP_tel",
                             CHFE_tel: "var.CHFE_tel",
                             IF_OSP_CHFE: "var.IF_OSP_CHFE",
                             IF_CHFE_OSP: "var.IF_CHFE_OSP",
                             IF_OSP_BRIDGE: "var.IF_OSP_BRIDGE",
                             IF_BRIDGE_OSP: "var.IF_BRIDGE_OSP",
                      }
                    },
                    save_response_as: "OSP_BRIDGE_003_response.log",
                    save_log_as: "OSP_BRIDGE_003.log"
                  }
                  run_in_background: "False"
            filtering_options: # optional
                - message_type: "stimulus" # stimulus/output/other
                  src_interface: "IF_CHFE_BRIDGE"
                  dst_interface: "IF_BRIDGE_CHFE"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "200" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_BRIDGE_OSP"
                  dst_interface: "IF_OSP_BRIDGE"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "200" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_BRIDGE_OSP"
                  dst_interface: "IF_OSP_BRIDGE"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: "CHFE test"
                  packet_type: "RTP_stream"
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_CHFE_BRIDGE"
                  dst_interface: "IF_BRIDGE_CHFE"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: "OSP test"
                  packet_type: "RTP_stream"
        requirements:
          - name: "RQ_BRG_042"
            variations: ["all"]