test_config:
  conformance:
    tests:
      - name: "PS_003"
        variations:
          - name: "HTTP_GET_to_Versions_entrypoint"
            description: "Validate JSON body of 200 OK response for HTTP GET to /Versions"
            interfaces:
              - name: "IF_ESRP_PS"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_PS"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: "/Versions"  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "False"
        requirements:
          - name: "RQ_PS_013"
            variations: ["all"]
          - name: "RQ_PS_014"
            variations: ["all"]