test_config:
  conformance:
    tests:
      - name: "CHFE_007"
        variations:
          - name: "Logging_the_call_status"
            description: "Test CHFE logging of CallStartLogEvent, CallEndLogEvent and CallSignallingMessageLogEvent"
            interfaces:
              - name: "IF_ESRP_CHFE"
                port_names: []
              - name: "IF_LOG_CHFE"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_LOG_CHFE"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "LOG",
                             extract_field: 'interfaces'
                      }
                      save_result_as: "var.log_interfaces"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "var.log_interfaces",
                             where_field: "name",
                             where_value: "IF_LOG_CHFE",
                             extract_field: 'fqdn'
                      }
                      save_result_as: "var.log_fqdn"
                    - method_name: "generate_identifier"
                      kwargs: {
                             identifier_type: "logid",
                             fqdn: "var.log_fqdn"
                      }
                      save_result_as: "var.logid"
                    - method_name: "save_to_file"
                      kwargs:
                        input_str: '{"logEventId": "test"}'
                        filename: "/tmp/chfe_007/logeventid.json"
                    - method_name: "modify_json_file"
                      kwargs:
                        json_input_file: "file./tmp/chfe_007/logeventid.json"
                        param_name: "logEventId"
                        value: "var.logid"
                        output_file: "file./tmp/chfe_007/logeventid.json"
                  type: "HTTP"
                  method: ["POST", "GET"]
                  response_code: ["201", "200"]
                  http_url: ["/LogEvents", "/Versions"] # part after f.e. http://IP:PORT
                  body: ["file./tmp/chfe_007/logeventid.json", "file.test_suite/test_files/JSON/versions/Logging_Service_Versions_object_example_v010.3f.5.0.0.json"]
                  sipp_scenario: {
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  if_name: "IF_ESRP_CHFE"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/CALLS/SIP_basic_call.xml",
                    dependencies: ["file.test_suite/test_files/SIPp_scenarios/CALLS/g711ulaw_rtp_stream.pcap"],
                    kwargs: {},
                    save_response_as: "CHFE_007_ESRP_response.log",
                    save_log_as: "CHFE_007_ESRP.log"
                  }
                  run_in_background: "False"
                - action: "manual"
                  if_name: ""
                  type: "SIP"
                  method: ""
                  instead: ""
                  prompt: "MANUAL ACTION REQUIRED - please answer incoming call on CHFE (if auto answering is not configured). Press any key to continue when ready..."
                  next_action: ""
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_ESRP_CHFE"
                dst_interface: "IF_CHFE_ESRP"
                sip_method: "INVITE"
                http_request_method: ""
                response_status_code: "200"
                header_contains: ""
                body_contains: ""
              - message_type: "output"
                src_interface: "IF_CHFE_LOG"
                dst_interface: "IF_LOG_CHFE"
                sip_method: ""
                http_request_method: "POST"
                response_status_code: "201"
                header_contains: "/LogEvents"
                body_contains: ""
              - message_type: "other"
                src_interface: "IF_ESRP_CHFE"
                dst_interface: "IF_CHFE_ESRP"
                sip_method: "BYE"
                http_request_method: ""
                response_status_code: "200"
                header_contains: ""
                body_contains: ""
        requirements:
          - name: "RQ_CHFE_312"
            variations: ["all"]
          - name: "RQ_CHFE_318"
            variations: ["all"]
          - name: "RQ_CHFE_319"
            variations: ["all"]
          - name: "RQ_CHFE_320"
            variations: ["all"]