test_config:
  conformance:
    tests:
      - name: "ESRP_003"
        variations:
          - name: "SIP_INVITE_from_OSP.xml"
            description: "SIP INVITE without 'Geolocation' header fields and PIDF-LO body"
            interfaces:
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_T-BCF_ESRP"
                port_names: [ ]
            params:
              messages:
                - action: "receive"
                  if_name: "IF_T-BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "ESRP_003_var1_RECEIVE_response.log",
                    save_log_as: "ESRP_003_var1_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                    kwargs: {},
                    save_response_as: "ESRP_003_var1_SEND_response.log",
                    save_log_as: "ESRP_003_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_location_garbled_PIDF-LO_body.xml"
            description: "SIP INVITE with garbled PIDF-LO body"
            interfaces:
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_T-BCF_ESRP"
                port_names: [ ]
            params:
              messages:
                - action: "receive"
                  if_name: "IF_T-BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "ESRP_003_var2_RECEIVE_response.log",
                    save_log_as: "ESRP_003_var2_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_location_garbled_PIDF-LO_body.xml",
                    kwargs: {},
                    save_response_as: "ESRP_003_var2_SEND_response.log",
                    save_log_as: "ESRP_003_var2_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_incorrect_geolocation_for_dereference.xml"
            description: "SIP INVITE with incorrect URL in 'Geolocation' header field"
            interfaces:
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_T-BCF_ESRP"
                port_names: [ ]
            params:
              messages:
                - action: "receive"
                  if_name: "IF_T-BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "ESRP_003_var3_RECEIVE_response.log",
                    save_log_as: "ESRP_003_var3_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_incorrect_geolocation_for_dereference.xml",
                    kwargs: {},
                    save_response_as: "ESRP_003_var3_SEND_response.log",
                    save_log_as: "ESRP_003_var3_SEND.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_ESRP_019"
            variations: ["all"]
          - name: "RQ_ESRP_022"
            variations: [
              "SIP_INVITE_location_garbled_PIDF-LO_body.xml",
              "SIP_INVITE_incorrect_geolocation_for_dereference.xml"
            ]
          - name: "RQ_ESRP_024"
            variations: ["SIP_INVITE_from_OSP.xml"]
          - name: "RQ_ESRP_025"
            variations: ["SIP_INVITE_incorrect_geolocation_for_dereference.xml"]
          - name: "RQ_ESRP_026"
            variations: ["SIP_INVITE_location_garbled_PIDF-LO_body.xml"]
          - name: "RQ_ESRP_027"
            variations: ["SIP_INVITE_incorrect_geolocation_for_dereference.xml"]
