test_config:
  conformance:
    tests:
      - name: "CHE_003"
        variations:
          - name: "SIP_INVITE_SDP_with_g711alaw_audio.xml"
            description: "Validate SDP answer from CHE on 'SIP INVITE + SDP' without language tags"
            interfaces:
              - name: "IF_BCF_CHE"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_BCF_CHE"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHE"
                        extract_field: "api"
                      "save_result_as": "var.che_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.che_api"
                        extract_field: "sender_tel_number"
                      "save_result_as": "var.sender_tel_number"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/\
                                      SIP_INVITE_SDP_with_g711alaw_audio.xml"
                        "param_name": "+12025551212"
                        "value": "var.sender_tel_number"
                        "output_file": "file./tmp/CHE_003/SIP_INVITE_SDP_with_g711alaw_audio.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/CHE_003/SIP_INVITE_SDP_with_g711alaw_audio.xml",
                    kwargs: {},
                    save_response_as: "CHE_003_var1_SEND_response.log",
                    save_log_as: "CHE_003_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_with_language_tags.xml"
            description: "Validate SDP answer from CHE on 'SIP INVITE + SDP' with language tags"
            interfaces:
              - name: "IF_BCF_CHE"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_BCF_CHE"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHE"
                        extract_field: "api"
                      "save_result_as": "var.che_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.che_api"
                        extract_field: "sender_tel_number"
                      "save_result_as": "var.sender_tel_number"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/\
                                      SIP_INVITE_with_language_tags.xml"
                        "param_name": "+12025551212"
                        "value": "var.sender_tel_number"
                        "output_file": "file./tmp/CHE_003/SIP_INVITE_with_language_tags.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/CHE_003/SIP_INVITE_with_language_tags.xml",
                    kwargs: {},
                    save_response_as: "CHE_003_var2_SEND_response.log",
                    save_log_as: "CHE_003_var2_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE for outgoing calls"
            description: "Validate SDP offer from CHE for outgoing calls"
            interfaces:
              - name: "IF_BCF_CHE"
                port_names: []
              - name: "IF_BCF-RECEIVER_CHE"
                port_names: []
            params:
              messages:
                - action: "manual"
                  id: "show_initial_prompt"
                  if_name: ""
                  instead: ""
                  type: ""
                  method: ""
                  prompt: "MANUAL STEP: The test suite must validate an outbound call from the CHE. When ready
                           to place the call, press any key to proceed and follow the instructions."
                  next_action: "receive_invite"
                - action: "receive"
                  id: "receive_invite"
                  if_name: "IF_BCF-RECEIVER_CHE"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "CHE_003_var3_RECEIVE_response.log",
                    save_log_as: "CHE_003_var3_RECEIVE.log"
                  }
                  run_in_background: "True"
                  next_action: "show_final_prompt"
                - action: "manual"
                  id: "show_final_prompt"
                  if_name: ""
                  instead: ""
                  type: ""
                  method: ""
                  prompt: "Place the outbound call via the provided test suite upstream IP. After 5 seconds, hangup
                           and press any key to proceed.."
                  next_action: ""
        requirements:
          - name: "RQ_CHE_008"
            variations: ["all"]
          - name: "RQ_CHE_009"
            variations: ["SIP_INVITE_with_language_tags.xml"]
