test_config:
  conformance:
    tests:
      - name: "ESRP_010"
        variations:
          - name: "Logging_the_call_status"
            description: "Test ESRP logging of CallStartLogEvent, CallEndLogEvent and CallSignallingMessageLogEvent"
            interfaces:
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_ESRP_LOG"
                port_names: []
              - name: "IF_LOG_ESRP"
                port_names: []
              - name: "IF_CHFE_ESRP"
                port_names: []
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  if_name: "IF_CHFE_ESRP"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/CALLS/SIP_RECEIVE_basic_call_and_answer.xml",
                    kwargs: {
                    },
                    save_response_as: "ESRP_010_CHFE_response.log",
                    save_log_as: "ESRP_010_CHFE.log"
                  }
                  run_in_background: "True"
                - action: "receive"
                  if_name: "IF_LOG_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "LOG",
                             extract_field: 'interfaces'
                      }
                      save_result_as: "var.log_interfaces"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "var.log_interfaces",
                             where_field: "name",
                             where_value: "IF_LOG_ESRP",
                             extract_field: 'fqdn'
                      }
                      save_result_as: "var.log_fqdn"
                    - method_name: "generate_identifier"
                      kwargs: {
                             identifier_type: "logid",
                             fqdn: "var.log_fqdn"
                      }
                      save_result_as: "var.logid"
                    - method_name: "save_to_file"
                      kwargs:
                        input_str: '{"logEventId": "test"}'
                        filename: "/tmp/esrp_010/logeventid.json"
                    - method_name: "modify_json_file"
                      kwargs:
                        json_input_file: "file./tmp/esrp_010/logeventid.json"
                        param_name: "logEventId"
                        value: "var.logid"
                        output_file: "file./tmp/esrp_010/logeventid.json"
                  type: "HTTP"
                  method: ["POST", "GET"]
                  response_code: ["201", "200"]
                  http_url: ["/LogEvents", "/Versions"] # part after f.e. http://IP:PORT
                  body: ["file./tmp/esrp_010/logeventid.json", "file.test_suite/test_files/JSON/versions/Logging_Service_Versions_object_example_v010.3f.5.0.0.json"]
                  sipp_scenario: {
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "callid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.callid"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "incidentid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.incidentid"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/CALLS/SIP_basic_call.xml"
                        "param_name": "urn:emergency:uid:callid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.callid"
                        "output_file": "file./tmp/ESRP_010/SIP_basic_call.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/ESRP_010/SIP_basic_call.xml"
                        "param_name": "urn:emergency:uid:incidentid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.incidentid"
                        "output_file": "file./tmp/ESRP_010/SIP_basic_call.xml"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/ESRP_010/SIP_basic_call.xml",
                    dependencies: ["file.test_suite/test_files/SIPp_scenarios/CALLS/g711ulaw_rtp_stream.pcap"],
                    kwargs: {},
                    save_response_as: "ESRP_010_BCF_response.log",
                    save_log_as: "ESRP_010_BCF.log"
                  }
                  run_in_background: "False"
                  next_action: "timeout"
                - action: "manual"
                  id: "timeout"
                  if_name: ""
                  instead: ""
                  type: "SIP"
                  method: ""
                  timeout: 10  # timeout in seconds
                  prompt: "Waiting 10 seconds for IUT..."
                  next_action: ""
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_BCF_ESRP"
                dst_interface: "IF_ESRP_BCF"
                sip_method: "INVITE"
                http_request_method: ""
                response_status_code: "200"
                header_contains: ""
                body_contains: ""
              - message_type: "output"
                src_interface: "IF_ESRP_LOG"
                dst_interface: "IF_LOG_ESRP"
                sip_method: ""
                http_request_method: "POST"
                response_status_code: "201"
                header_contains: "/LogEvents"
                body_contains: ""
              - message_type: "other"
                src_interface: "IF_ESRP_CHFE"
                dst_interface: "IF_CHFE_ESRP"
                sip_method: "INVITE"
                http_request_method: ""
                response_status_code: "200"
                header_contains: ""
                body_contains: ""
              - message_type: "other"
                src_interface: "IF_BCF_ESRP"
                dst_interface: "IF_ESRP_BCF"
                sip_method: "BYE"
                http_request_method: ""
                response_status_code: "200"
                header_contains: ""
                body_contains: ""
              - message_type: "other"
                src_interface: "IF_ESRP_CHFE"
                dst_interface: "IF_CHFE_ESRP"
                sip_method: "BYE"
                http_request_method: ""
                response_status_code: "200"
                header_contains: ""
                body_contains: ""
        requirements:
          - name: "RQ_ESRP_116"
            variations: ["all"]
          - name: "RQ_ESRP_124"
            variations: ["all"]
          - name: "RQ_ESRP_125"
            variations: ["all"]
          - name: "RQ_ESRP_126"
            variations: ["all"]