test_config:
  conformance:
    tests:
      - name: "ESRP_013"
        variations:
          - name: "Accommodating_multiple_additional_data_structures"
            description: "Validate ESRP dereferencing of multiple additional data structures"
            interfaces:
              - name: "IF_PS_ESRP"
                port_names: []
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_ADR_ESRP"
                port_names: []
              - name: "IF_ADR-2_ESRP"
                port_names: []
              - name: "IF_ADR-3_ESRP"
                port_names: []
              - name: "IF_CHFE_ESRP"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_PS_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHFE"
                        extract_field: "interfaces"
                      "save_result_as": "var.chfe_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.chfe_interfaces"
                        where_field: "name"
                        where_value: "IF_CHFE_ESRP"
                        extract_field: "port_mapping"
                      save_result_as: "var.chfe_port_mapping"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.chfe_port_mapping"
                        where_field: "protocol"
                        where_value: "SIP"
                        extract_field: "port"
                      save_result_as: "var.chfe_port"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_CHFE_ESRP"
                      "save_result_as": "var.IF_CHFE_ESRP"
                    - method_name: "generate_str"
                      kwargs:
                        string_to_modify: "sip:chfe@{0}:{1}"
                        variables: "list.[var.IF_CHFE_ESRP, var.chfe_port]"
                      save_result_as: "var.chfe_uri"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/JSON/policy_object/Policy_object_force_ESRP_to_dereference_ADR_v010.3f.5.0.0.json"
                        "param_name": "CHFE_SIP_URI"
                        "value": "var.chfe_uri"
                        "output_file": "file./tmp/ESRP_013/policy.json"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ESRP"
                        extract_field: "certificate_file"
                      save_result_as: "var.esrp_certificate_file"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ESRP"
                        extract_field: "certificate_key"
                      "save_result_as": "var.esrp_certificate_key"
                    - method_name: "generate_jws"
                      kwargs:
                        json_source: "file./tmp/ESRP_013/policy.json"
                        cert_path: "var.esrp_certificate_file"
                        key_path: "var.esrp_certificate_key"
                        output_file: "file./tmp/jws_body"
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: "/Policies"  # part after f.e. http://IP:PORT
                  body: "file./tmp/jws_body"
                  sipp_scenario: {}
                  run_in_background: "True"
                  next_action: "receive_adr_1"
                - action: "receive"
                  id: "receive_adr_1"
                  if_name: "IF_ADR_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: "/ADR"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_ADR/EmergencyCallData.DeviceInfo"
                  sipp_scenario: {}
                  run_in_background: "True"
                  next_action: "receive_adr_2"
                - action: "receive"
                  id: "receive_adr_2"
                  if_name: "IF_ADR-2_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: "/ADR"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_ADR/EmergencyCallData.ProviderInfo"
                  sipp_scenario: {}
                  run_in_background: "True"
                  next_action: "receive_adr_3"
                - action: "receive"
                  id: "receive_adr_3"
                  if_name: "IF_ADR-3_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "HTTP"
                  method: "GET"
                  response_code: "200"
                  http_url: "/ADR"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_ADR/EmergencyCallData.ServiceInfo"
                  sipp_scenario: {}
                  run_in_background: "True"
                  next_action: "receive_chfe"
                - action: "receive"
                  id: "receive_chfe"
                  if_name: "IF_CHFE_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path:
                      "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "ESRP_013_RECEIVE_CHFE_response.log",
                    save_log_as: "ESRP_013_RECEIVE_CHFE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "callid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.callid"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "incidentid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.incidentid"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                        "param_name": "urn:emergency:uid:callid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.callid"
                        "output_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                        "param_name": "urn:emergency:uid:incidentid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.incidentid"
                        "output_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ADR"
                        extract_field: 'api_http_url_prefix'
                      save_result_as: "var.adr_url_prefix"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ADR"
                        extract_field: "interfaces"
                      "save_result_as": "var.adr_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.adr_interfaces"
                        where_field: "name"
                        where_value: "IF_ADR_ESRP"
                        extract_field: "port_mapping"
                      save_result_as: "var.adr_port_mapping"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.adr_port_mapping"
                        where_field: "protocol"
                        where_value: "HTTP"
                        extract_field: "port"
                      save_result_as: "var.adr_port"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_ADR_ESRP"
                      "save_result_as": "var.IF_ADR_ESRP"
                    - method_name: "generate_url"
                      kwargs:
                        protocol: "http"
                        address: "list.[var.IF_ADR_ESRP]"
                        port: "var.adr_port"
                        url_prefix: "var.adr_url_prefix"
                        path: "/ADR"
                      save_result_as: "var.adr_url"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                        "param_name": "[$URL1]"
                        "value": "var.adr_url"
                        "output_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ADR-2"
                        extract_field: 'api_http_url_prefix'
                      save_result_as: "var.adr-2_url_prefix"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ADR-2"
                        extract_field: "interfaces"
                      "save_result_as": "var.adr-2_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.adr-2_interfaces"
                        where_field: "name"
                        where_value: "IF_ADR-2_ESRP"
                        extract_field: "port_mapping"
                      save_result_as: "var.adr-2_port_mapping"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.adr-2_port_mapping"
                        where_field: "protocol"
                        where_value: "HTTP"
                        extract_field: "port"
                      save_result_as: "var.adr-2_port"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_ADR-2_ESRP"
                      "save_result_as": "var.IF_ADR-2_ESRP"
                    - method_name: "generate_url"
                      kwargs:
                        protocol: "http"
                        address: "list.[var.IF_ADR-2_ESRP]"
                        port: "var.adr-2_port"
                        url_prefix: "var.adr-2_url_prefix"
                        path: "/ADR"
                      save_result_as: "var.adr-2_url"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                        "param_name": "[$URL2]"
                        "value": "var.adr-2_url"
                        "output_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ADR-3"
                        extract_field: 'api_http_url_prefix'
                      save_result_as: "var.adr-3_url_prefix"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ADR-3"
                        extract_field: "interfaces"
                      "save_result_as": "var.adr-3_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.adr-3_interfaces"
                        where_field: "name"
                        where_value: "IF_ADR-3_ESRP"
                        extract_field: "port_mapping"
                      save_result_as: "var.adr-3_port_mapping"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.adr-3_port_mapping"
                        where_field: "protocol"
                        where_value: "HTTP"
                        extract_field: "port"
                      save_result_as: "var.adr-3_port"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_ADR-3_ESRP"
                      "save_result_as": "var.IF_ADR-3_ESRP"
                    - method_name: "generate_url"
                      kwargs:
                        protocol: "http"
                        address: "list.[var.IF_ADR-3_ESRP]"
                        port: "var.adr-3_port"
                        url_prefix: "var.adr-3_url_prefix"
                        path: "/ADR"
                      save_result_as: "var.adr-3_url"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                        "param_name": "[$URL3]"
                        "value": "var.adr-3_url"
                        "output_file": "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/ESRP_013/SIP_INVITE_from_BCF_3x_ADR_references.xml",
                    kwargs: {},
                    save_response_as: "ESRP_013_SEND_response.log",
                    save_log_as: "ESRP_013_SEND.log"
                  }
                  run_in_background: "False"
            filtering_options: # optional
                - message_type: "stimulus" # stimulus/output/other
                  src_interface: "IF_BCF_ESRP"
                  dst_interface: "IF_ESRP_BCF"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_ESRP_ADR"
                  dst_interface: "IF_ADR_ESRP"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "GET" #  leave empty if not needed
                  response_status_code: "200" #  leave empty if not needed
                  header_contains: "EmergencyCallData.DeviceInfo"
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_ESRP_ADR-2"
                  dst_interface: "IF_ADR-2_ESRP"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "GET" #  leave empty if not needed
                  response_status_code: "200" #  leave empty if not needed
                  header_contains: "EmergencyCallData.ProviderInfo"
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_ESRP_ADR-3"
                  dst_interface: "IF_ADR-3_ESRP"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "GET" #  leave empty if not needed
                  response_status_code: "200" #  leave empty if not needed
                  header_contains: "EmergencyCallData.ServiceInfo"
                  body_contains: ""
                - message_type: "output" # stimulus/output/other
                  src_interface: "IF_ESRP_CHFE"
                  dst_interface: "IF_CHFE_ESRP"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
        requirements:
          - name: "RQ_ESRP_056"
            variations: ["all"]