test_config:
  conformance:
    tests:
      - name: "BCF_009"
        variations:
          - name: "Adding_replaces_support_as_B2BUA"
            description: "Verify BCF B2BUA sends the ʼSupported: replaceʼ header field to an outgoing INVITE sent 
            inside the ESInet."
            interfaces:
              - name: "IF_OSP_BCF"
                port_names: []
              - name: "IF_ESRP_BCF"
                port_names: []
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  if_name: "IF_ESRP_BCF"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                    },
                    save_response_as: "BCF_009_var1_ESRP_response.log",
                    save_log_as: "BCF_009_var1_ESRP.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""  # Optional
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                    kwargs: {},
                    save_response_as: "BCF_009_var1_OSP_response.log",
                    save_log_as: "BCF_009_var1_OSP.log"
                  }
                  run_in_background: "False"
                  next_action: "manual_delay"
                - action: "manual"
                  id: "manual_delay"
                  if_name: ""
                  instead: ""
                  type: "SIP"
                  method: ""
                  timeout: 5  # timeout in seconds
                  prompt: "Waiting 5 seconds until all SIP INVITE messages will be sent..."
            filtering_options:
              - message_type: "stimulus"
                src_interface: "IF_OSP_BCF"
                dst_interface: "IF_BCF_OSP"
                sip_method: "INVITE"
                http_request_method: ""
                response_status_code: ""
                header_contains: ""
                body_contains: ""
              - message_type: "output"
                src_interface: "IF_BCF_ESRP"
                dst_interface: "IF_ESRP_BCF"
                sip_method: "INVITE"
                http_request_method: ""
                response_status_code: ""
                header_contains: ""
                body_contains: ""
        requirements:
          - name: "RQ_BCF_111"
            variations: ["all"]
