test_config:
  conformance:
    tests:
      - name: "LIS_002"
        variations:
          - name: "Getting_locationURI_from_LIS"
            description: "Validate getting locationURI from LIS"
            interfaces:
              - name: "IF_ESRP_LIS"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LIS"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "LIS"
                        extract_field: "api"
                      "save_result_as": "var.lis_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.lis_api"
                        extract_field: "http_url_suffix_held"
                      "save_result_as": "var.http_url"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.lis_api"
                        extract_field: "device_uri"
                      "save_result_as": "var.device_uri"
                    - method_name: "replace_string_in_file"
                      kwargs:
                        input_file: "file.test_suite/test_files/HTTP_messages/HTTP_HELD/Location_request_for_locationURI"
                        param_name: "DEVICE_URI"
                        value: "var.device_uri"
                        output_file: "file./tmp/LIS_002/LIS_002_Location_request_for_locationURI"
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file./tmp/LIS_002/LIS_002_Location_request_for_locationURI"
                  sipp_scenario: {}
                  run_in_background: "False"
        requirements:
          - name: "RQ_LIS_006"
            variations: ["all"]