test_config:
  conformance:
    tests:
      - name: "ESRP_009"
        variations:
        - name: "SIP_INVITE_log_event"
          description: "Test ESRP logging for outgoing SIP INVITE (CallSignalingMessageLogEvent) forwarded to CHFE."
          interfaces:
            - name: "IF_OSP_BCF"
              port_names: []
            - name: "IF_BCF_OSP"
              port_names: []
            - name: "IF_BCF_ESRP"
              port_names: []
            - name: "IF_ESRP_BCF"
              port_names: []
            - name: "IF_ESRP_LOG"
              port_names: []
            - name: "IF_LOG_ESRP"
              port_names: []
            - name: "IF_ESRP_CHFE"
              port_names: []
            - name: "IF_CHFE_ESRP"
              port_names: []
          filtering_options:
            - message_type: "stimulus"
              src_interface: "IF_OSP_BCF"
              dst_interface: "IF_BCF_OSP"
              sip_method: "INVITE"
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output"
              src_interface: "IF_ESRP_LOG"
              dst_interface: "IF_LOG_ESRP"
              sip_method: ""
              http_request_method: "POST" #  leave empty if not needed
              response_status_code: "201" #  leave empty if not needed
              header_contains: "/LogEvents"
              body_contains: ""
            - message_type: "other"
              src_interface: "IF_ESRP_CHFE"
              dst_interface: "IF_CHFE_ESRP"
              sip_method: "INVITE"
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
          params:
            messages:
                - action: "receive"
                  if_name: "IF_LOG_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "LOG"
                        extract_field: "interfaces"
                      save_result_as: "var.log_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.log_interfaces"
                        where_field: "name"
                        where_value: "IF_LOG_ESRP"
                        extract_field: "fqdn"
                      save_result_as: "var.log_fqdn"
                    - method_name: "generate_identifier"
                      kwargs:
                        identifier_type: "logid"
                        fqdn: "var.log_fqdn"
                        set_default: "True"
                      save_result_as: "var.logid"
                    - method_name: "save_to_file"
                      kwargs:
                        input_str: '{"logEventId": "test"}'
                        filename: "/tmp/esrp_009/logeventid.json"
                    - method_name: "modify_json_file"
                      kwargs:
                        json_input_file: "file./tmp/esrp_009/logeventid.json"
                        param_name: "logEventId"
                        value: "var.logid"
                        output_file: "file./tmp/esrp_009/logeventid.json"
                  type: "HTTP"
                  method: ["POST", "GET"]
                  response_code: ["201", "200"]
                  http_url: ["/LogEvents", "/Versions"]
                  body: ["file./tmp/esrp_009/logeventid.json", "file.test_suite/test_files/JSON/versions/Logging_Service_Versions_object_example_v010.3f.5.0.0.json"]
                  run_in_background: "True"
                - action: "receive"
                  if_name: "IF_CHFE_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/CALLS/SIP_RECEIVE_basic_call_and_answer.xml",
                    kwargs: {},
                    save_response_as: "ESRP_009_V1_OSP_INVITE_response.log",
                    save_log_as: "ESRP_009_V1_OSP_INVITE.log"
                  }
                  run_in_background: "True"
                - action: "receive"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_OSP_BCF"
                      "save_result_as": "var.IF_OSP_BCF"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_OSP"
                      "save_result_as": "var.IF_BCF_OSP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_ESRP_BCF"
                      "save_result_as": "var.IF_ESRP_BCF"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "BCF"
                        extract_field: "interfaces"
                      "save_result_as": "var.bcf_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.bcf_interfaces"
                        where_field: "name"
                        where_value: "IF_BCF_OSP"
                        extract_field: "fqdn"
                      "save_result_as": "var.BCF_FQDN"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ESRP"
                        extract_field: "interfaces"
                      "save_result_as": "var.esrp_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.esrp_interfaces"
                        where_field: "name"
                        where_value: "IF_ESRP_BCF"
                        extract_field: "fqdn"
                      "save_result_as": "var.ESRP_FQDN"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/sip_service/FEs/BCF_simple_call.xml",
                    kwargs: {
                      set: {
                        BCF_FQDN: "var.BCF_FQDN",
                        ESRP_FQDN: "var.ESRP_FQDN",
                        IF_OSP_BCF: "var.IF_OSP_BCF",
                        IF_BCF_OSP: "var.IF_BCF_OSP",
                        IF_BCF_ESRP: "var.IF_BCF_ESRP",
                        IF_ESRP_BCF: "var.IF_ESRP_BCF"
                      }
                    },
                    save_response_as: "ESRP_008_BCF_response.log",
                    save_log_as: "ESRP_008_BCF.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""  # Optional
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                      scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                      dependencies: [ "file.test_suite/test_files/SIPp_scenarios/CALLS/g711ulaw_rtp_stream.pcap" ],
                      kwargs: {},
                      save_response_as: "ESRP_009_V1_OSP_response.log",
                      save_log_as: "ESRP_009_V1_OSP.log"
                  }
                  run_in_background: "False"
                  next_action: "manual_timeout"
                - action: "manual"
                  id: "manual_timeout"
                  if_name: ""
                  instead: ""
                  type: "SIP"
                  method: ""
                  timeout: 10  # timeout in seconds
                  prompt: "Waiting 10 seconds for IUT..."
                  next_action: ""
                
        - name: "SIP_MESSAGE_log_event"
          description: "Test ESRP logging for outgoing SIP MESSAGE (MessageLogEvent) forwarded to CHFE."
          interfaces:
            - name: "IF_OSP_BCF"
              port_names: []
            - name: "IF_BCF_OSP"
              port_names: []
            - name: "IF_BCF_ESRP"
              port_names: []
            - name: "IF_ESRP_BCF"
              port_names: []
            - name: "IF_ESRP_LOG"
              port_names: []
            - name: "IF_LOG_ESRP"
              port_names: []
            - name: "IF_ESRP_CHFE"
              port_names: []
            - name: "IF_CHFE_ESRP"
              port_names: []
          filtering_options:
            - message_type: "stimulus"
              src_interface: "IF_OSP_BCF"
              dst_interface: "IF_BCF_OSP"
              sip_method: "MESSAGE"
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output"
              src_interface: "IF_ESRP_LOG"
              dst_interface: "IF_LOG_ESRP"
              sip_method: ""
              http_request_method: "POST" #  leave empty if not needed
              response_status_code: "201" #  leave empty if not needed
              header_contains: "/LogEvents"
              body_contains: ""
            - message_type: "other"
              src_interface: "IF_ESRP_CHFE"
              dst_interface: "IF_CHFE_ESRP"
              sip_method: "MESSAGE"
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
          params:
            messages:
                - action: "receive"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_OSP_BCF"
                      "save_result_as": "var.IF_OSP_BCF"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_OSP"
                      "save_result_as": "var.IF_BCF_OSP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_ESRP_BCF"
                      "save_result_as": "var.IF_ESRP_BCF"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "BCF"
                        extract_field: "interfaces"
                      "save_result_as": "var.bcf_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.bcf_interfaces"
                        where_field: "name"
                        where_value: "IF_BCF_OSP"
                        extract_field: "fqdn"
                      "save_result_as": "var.BCF_FQDN"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ESRP"
                        extract_field: "interfaces"
                      "save_result_as": "var.esrp_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.esrp_interfaces"
                        where_field: "name"
                        where_value: "IF_ESRP_BCF"
                        extract_field: "fqdn"
                      "save_result_as": "var.ESRP_FQDN"
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/sip_service/FEs/BCF_simple_SIP_MESSAGE.xml",
                    kwargs: {
                      set: {
                        BCF_FQDN: "var.BCF_FQDN",
                        ESRP_FQDN: "var.ESRP_FQDN",
                        IF_OSP_BCF: "var.IF_OSP_BCF",
                        IF_BCF_OSP: "var.IF_BCF_OSP",
                        IF_BCF_ESRP: "var.IF_BCF_ESRP",
                        IF_ESRP_BCF: "var.IF_ESRP_BCF"
                      }
                    },
                    save_response_as: "ESRP_008_BCF_response.log",
                    save_log_as: "ESRP_008_BCF.log"
                  }
                  run_in_background: "True"
                - action: "receive"
                  if_name: "IF_CHFE_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                      scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_MESSAGE/SIP_MESSAGE_receive_and_answer.xml",
                      kwargs: {},
                      save_response_as: "ESRP_009_V2_OSP_MESSAGE_response.log",
                      save_log_as: "ESRP_009_V2_OSP_MESSAGE.log"
                  }
                  run_in_background: "True"
                - action: "receive"
                  if_name: "IF_LOG_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "LOG"
                        extract_field: "interfaces"
                      save_result_as: "var.log_interfaces"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.log_interfaces"
                        where_field: "name"
                        where_value: "IF_LOG_ESRP"
                        extract_field: "fqdn"
                      save_result_as: "var.log_fqdn"
                    - method_name: "generate_identifier"
                      kwargs:
                        identifier_type: "logid"
                        fqdn: "var.log_fqdn"
                        set_default: "True"
                      save_result_as: "var.logid"
                    - method_name: "save_to_file"
                      kwargs:
                        input_str: '{"logEventId": "test"}'
                        filename: "/tmp/esrp_009/logeventid.json"
                    - method_name: "modify_json_file"
                      kwargs:
                        json_input_file: "file./tmp/esrp_009/logeventid.json"
                        param_name: "logEventId"
                        value: "var.logid"
                        output_file: "file./tmp/esrp_009/logeventid.json"
                  type: "HTTP"
                  method: [ "POST", "GET" ]
                  response_code: [ "201", "200" ]
                  http_url: [ "/LogEvents", "/Versions" ]
                  body: [ "file./tmp/esrp_009/logeventid.json", "file.test_suite/test_files/JSON/versions/Logging_Service_Versions_object_example_v010.3f.5.0.0.json" ]
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_OSP_BCF"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                      scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_MESSAGE/SIP_MESSAGE_from_OSP.xml",
                      kwargs: {},
                      save_response_as: "ESRP_009_V2_OSP_response.log",
                      save_log_as: "ESRP_009_V2_OSP.log",
                  }
                  run_in_background: "False"
                  next_action: "manual_timeout"
                - action: "manual"
                  id: "manual_timeout"
                  if_name: ""
                  instead: ""
                  type: "SIP"
                  method: ""
                  timeout: 10  # timeout in seconds
                  prompt: "Waiting 10 seconds for IUT..."
                  next_action: ""
        requirements:
          - name: "RQ_ESRP_117"
            variations: ["all"]
          - name: "RQ_ESRP_118"
            variations: ["all"]
          - name: "RQ_ESRP_146"
            variations: ["all"]
