test_config:
  conformance:
    tests:
      - name: "ECRF_LVF_003"
        variations:
          - name: "findService_polygon_covering_fully_one_and_partially_another_boundary"
            description: "Validate HTTP 200 OK response on findService request with polygon covering partially\
                          one of the boundaries and fully another one"
            interfaces:
              - name: "IF_ESRP_ECRF-LVF"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_ECRF-LVF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ECRF-LVF"
                        extract_field: "api"
                      "save_result_as": "var.ecrf_lvf_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.ecrf_lvf_api"
                        extract_field: "http_url_suffix_lost"
                      "save_result_as": "var.http_url"
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/\
                        findService_polygon_covering_fully_one_and_partially_another_boundary"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "findService_polygon_covering_fully_two_boundaries"
            description: "Validate HTTP 200 OK response on findService request with polygon covering fully 2 boundaries"
            interfaces:
              - name: "IF_ESRP_ECRF-LVF"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_ECRF-LVF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ECRF-LVF"
                        extract_field: "api"
                      "save_result_as": "var.ecrf_lvf_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.ecrf_lvf_api"
                        extract_field: "http_url_suffix_lost"
                      "save_result_as": "var.http_url"
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/\
                        findService_polygon_covering_fully_two_boundaries"
                  sipp_scenario: {}
                  run_in_background: "False"
        requirements:
          - name: "RQ_ECRF_011"
            variations: ["findService_polygon_covering_fully_one_and_partially_another_boundary"]