test_config:
  conformance:
    tests:
      - name: "ECRF_LVF_005"
        variations:
          - name: "findService_recursive_mode_polygon_not_covering_boundaries"
            description: "Validate ECRF-LVF sending LoST request for services out of it's local boundaries"
            interfaces:
              - name: "IF_ESRP_ECRF-LVF"
                port_names: []
              - name: "IF_TS-ECRF-LVF_ECRF-LVF"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_TS-ECRF-LVF_ECRF-LVF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "lab_config['lab_config']['entities']"
                        "where_field": "name"
                        "where_value": "TS2"
                        "extract_field": "interfaces"
                      "save_result_as": "var.ts2_interfaces"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts2_interfaces"
                        "where_field": "name"
                        "where_value": "IF_TS2_ECRF-LVF"
                        "extract_field": "ip"
                      "save_result_as": "var.ts2_ip"
                  type: "HTTP"
                  method: "GET"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {}
                  run_in_background: "True"
                  run_on_ip: "var.ts2_ip"
                - action: "send"
                  if_name: "IF_ESRP_ECRF-LVF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ECRF-LVF"
                        extract_field: "api"
                      "save_result_as": "var.ecrf_lvf_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.ecrf_lvf_api"
                        extract_field: "http_url_suffix_lost"
                      "save_result_as": "var.http_url"
                  type: "HTTP"
                  method: "GET"
                  response_code: ""
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/\
                    findService_recursive_mode_polygon_not_covering_boundaries"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "findService_iterative_mode_polygon_not_covering_boundaries"
            description: "Validate ECRF-LVF responding with 3XX message containing URL of another ECRF-LVF"
            interfaces:
              - name: "IF_ESRP_ECRF-LVF"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_ECRF-LVF"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "ECRF-LVF"
                        extract_field: "api"
                      "save_result_as": "var.ecrf_lvf_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.ecrf_lvf_api"
                        extract_field: "http_url_suffix_lost"
                      "save_result_as": "var.http_url"
                  type: "HTTP"
                  method: "GET"
                  response_code: "3XX"
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/\
                    findService_iterative_mode_polygon_not_covering_boundaries"
                  sipp_scenario: {}
                  run_in_background: "False"
        requirements:
          - name: "RQ_ECRF-LVF_043"
            variations: [ "all" ]
          - name: "RQ_ECRF-LVF_050"
            variations: ["all"]