test_config:
  conformance:
    tests:
      - name: "CHE_001"
        variations:
          - name: "HELD_location_dereferencing"
            description: "Validate HTTP POST sent to LIS after receiving SIP INVITE (HELD)"
            interfaces:
              - name: "IF_BCF_CHE"
                port_names: []
              - name: "IF_LIS_CHE"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_LIS_CHE"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "/location"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_HELD/Location_response"
                  sipp_scenario: {}
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_BCF_CHE"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHE"
                        extract_field: "api"
                      "save_result_as": "var.che_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.che_api"
                        extract_field: "sender_tel_number"
                      "save_result_as": "var.sender_tel_number"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "lab_config['lab_config']['entities']"
                        "where_field": "name"
                        "where_value": "LIS"
                        "extract_field": "interfaces"
                      "save_result_as": "var.ts_lis_interfaces"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_interfaces"
                        "where_field": "name"
                        "where_value": "IF_LIS_CHE"
                        "extract_field": "ip"
                      "save_result_as": "var.ts_lis_ip"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_interfaces"
                        "where_field": "name"
                        "where_value": "IF_LIS_CHE"
                        "extract_field": "port_mapping"
                      "save_result_as": "var.ts_lis_port_mapping"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_port_mapping"
                        "where_field": "protocol"
                        "where_value": "HTTP"
                        "extract_field": "port"
                      "save_result_as": "var.ts_lis_http_port"
                    - method_name: "generate_str"
                      kwargs:
                        string_to_modify: "http://{0}:{1}/location"
                        variables: "list.[var.ts_lis_ip, var.ts_lis_http_port]"
                      save_result_as: "var.http_url"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_geolocation_HELD.xml"
                        "param_name": "LIS_LOCATION_REFERENCE_URL"
                        "value": "var.http_url"
                        "output_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_HELD.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_HELD.xml"
                        "param_name": "+12025551212"
                        "value": "var.sender_tel_number"
                        "output_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_HELD.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/CHE_001/SIP_INVITE_geolocation_HELD.xml",
                    kwargs: {},
                    save_response_as: "CHE_001_var1_SEND_response.log",
                    save_log_as: "CHE_001_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_presence_event_package_location_dereferencing"
            description: "Validate SIP SUBSCRIBE sent to LIS after receiving SIP INVITE (SIP Presence Event Package)"
            interfaces:
              - name: "IF_BCF_CHE"
                port_names: []
              - name: "IF_LIS_CHE"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_LIS_CHE"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "lab_config['lab_config']['entities']"
                        "where_field": "name"
                        "where_value": "LIS"
                        "extract_field": "interfaces"
                      "save_result_as": "var.ts_lis_interfaces"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_interfaces"
                        "where_field": "name"
                        "where_value": "IF_LIS_CHE"
                        "extract_field": "ip"
                      "save_result_as": "var.ts_lis_ip"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_interfaces"
                        "where_field": "name"
                        "where_value": "IF_LIS_CHE"
                        "extract_field": "port_mapping"
                      "save_result_as": "var.ts_lis_port_mapping"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_port_mapping"
                        "where_field": "protocol"
                        "where_value": "SIP"
                        "extract_field": "port"
                      "save_result_as": "var.ts_lis_sip_port"
                    - method_name: "generate_str"
                      kwargs:
                        string_to_modify: "sip:location@{0}:{1}"
                        variables: "list.[var.ts_lis_ip, var.ts_lis_sip_port]"
                      save_result_as: "var.sip_uri"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_LIS.xml"
                        "param_name": "LOCATION_SIP_URI"
                        "value": "var.sip_uri"
                        "output_file": "file./tmp/CHE_001/SIP_SUBSCRIBE_LIS.xml"
                  type: "SIP"
                  method: "SUBSCRIBE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path:
                      "file./tmp/CHE_001/SIP_SUBSCRIBE_LIS.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var2_SEND_response.log",
                    save_log_as: "CHE_002_var2_SEND.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  if_name: "IF_BCF_CHE"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "CHE"
                        extract_field: "api"
                      "save_result_as": "var.che_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.che_api"
                        extract_field: "sender_tel_number"
                      "save_result_as": "var.sender_tel_number"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "lab_config['lab_config']['entities']"
                        "where_field": "name"
                        "where_value": "LIS"
                        "extract_field": "interfaces"
                      "save_result_as": "var.ts_lis_interfaces"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_interfaces"
                        "where_field": "name"
                        "where_value": "IF_LIS_CHE"
                        "extract_field": "ip"
                      "save_result_as": "var.ts_lis_ip"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_interfaces"
                        "where_field": "name"
                        "where_value": "IF_LIS_CHE"
                        "extract_field": "port_mapping"
                      "save_result_as": "var.ts_lis_port_mapping"
                    - "method_name": "extract_from_config"
                      "kwargs":
                        "config_part": "var.ts_lis_port_mapping"
                        "where_field": "protocol"
                        "where_value": "SIP"
                        "extract_field": "port"
                      "save_result_as": "var.ts_lis_sip_port"
                    - method_name: "generate_str"
                      kwargs:
                        string_to_modify: "sip:location@{0}:{1}"
                        variables: "list.[var.ts_lis_ip, var.ts_lis_sip_port]"
                      save_result_as: "var.sip_uri"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_geolocation_SIP.xml"
                        "param_name": "LOCATION_SIP_URI"
                        "value": "var.sip_uri"
                        "output_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_SIP.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_SIP.xml"
                        "param_name": "+12025551212"
                        "value": "var.sender_tel_number"
                        "output_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_SIP.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/CHE_001/SIP_INVITE_geolocation_SIP.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var2_SEND_response.log",
                    save_log_as: "CHE_002_var2_SEND.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_CHE_011"
            variations: ["all"]