test_config:
  conformance:
    tests:
      - name: "LIS_001"
        variations:
          - name: "Location_URI_dereference_using_HTTP_HELD"
            description: "Validate location URI dereferencing using HTTP HELD"
            interfaces:
              - name: "IF_ESRP_LIS"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LIS"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "LIS"
                        extract_field: "api"
                      "save_result_as": "var.lis_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.lis_api"
                        extract_field: "http_url_suffix_held"
                      "save_result_as": "var.http_url"
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "var.http_url"  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_HELD/Location_request"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "Location_URI_dereference_using_SIP_Presence_Event_Package"
            description: "Validate location URI dereferencing using SIP Presence Event Package"
            interfaces:
              - name: "IF_ESRP_LIS"
                port_names: []
            params:
              messages:
                - action: "send"
                  if_name: "IF_ESRP_LIS"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "lab_config['lab_config']['entities']"
                        where_field: "name"
                        where_value: "LIS"
                        extract_field: "api"
                      "save_result_as": "var.lis_api"
                    - method_name: "extract_from_config"
                      kwargs:
                        config_part: "var.lis_api"
                        extract_field: "sip_uri_user"
                      "save_result_as": "var.sip_uri_user"
                  type: "SIP"
                  method: "SUBSCRIBE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_suite/test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_FROM_LIS.xml",
                    kwargs: {
                              "-s": "var.sip_uri_user"
                    },
                    save_response_as: "LIS_001_var2_SEND_response.log",
                    save_log_as: "LIS_001_var2_SEND.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_LIS_001"
            variations: ["all"]
          - name: "RQ_LIS_002"
            variations: ["all"]
          - name: "RQ_LIS_007"
            variations: ["all"]
          - name: "RQ_LIS_010"
            variations: ["all"]
