test_config:
  conformance:
    tests:
      - name: "ESRP_016"
        variations:
          - name: "LoST_request_over_TCP"
            description: "Verify ESRP supports HTTP LoST request over TCP transport"
            interfaces:
              - name: "IF_BCF_ESRP"
                port_names: []
              - name: "IF_ECRF-LVF_ESRP"
                port_names: []
            params:
              messages:
                - action: "receive"
                  if_name: "IF_ECRF-LVF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/findServiceResponse.xml"
                  sipp_scenario: {}
                  run_in_background: "True"
                  next_action: "manual_esrp_config_tcp"
                - action: "manual"
                  id: "manual_esrp_config_tcp"
                  if_name: ""
                  instead: ""
                  type: "SIP"
                  method: ""
                  prompt: "Please configure ESRP to send LoST requests to the ECRF-LVF using TCP transport and press any key to continue when ready..."
                  next_action: "send_invite"
                - action: "send"
                  id: "send_invite"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: ""  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "callid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.callid"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "incidentid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.incidentid"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                        "param_name": "urn:emergency:uid:callid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.callid"
                        "output_file": "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                        "param_name": "urn:emergency:uid:incidentid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.incidentid"
                        "output_file": "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml",
                    kwargs: {},
                    save_response_as: "ESRP_016_SEND_response.log",
                    save_log_as: "ESRP_016_SEND.log"
                  }
                  run_in_background: "False"
            filtering_options: # optional
                - message_type: "stimulus" # stimulus/output/other
                  src_interface: "IF_BCF_ESRP"
                  dst_interface: "IF_ESRP_BCF"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_ESRP_ECRF-LVF"
                  dst_interface: "IF_ECRF-LVF_ESRP"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "POST" #  leave empty if not needed
                  response_status_code: "200" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
          - name: "LoST_request_over_TLS"
            description: "Verify ESRP supports HTTPS LoST request over TLS transport"
            interfaces:
              - name: "IF_BCF_ESRP"
                port_names: ["IF_BCF_ESRP_SIP_5061_TLSv1.2"]
              - name: "IF_ECRF-LVF_ESRP"
                port_names: ["IF_ECRF-LVF_ESRP_HTTPS_443_TLSv1.2"]
            params:
              messages:
                - action: "receive"
                  if_name: "IF_ECRF-LVF_ESRP"
                  if_port_name: "IF_ECRF-LVF_ESRP_HTTPS_443_TLSv1.2"  # Optional
                  prep_steps: []
                  type: "HTTPS"
                  method: "POST"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: "file.test_suite/test_files/HTTP_messages/HTTP_LoST/findServiceResponse.xml"
                  sipp_scenario: {}
                  run_in_background: "True"
                  next_action: "manual_esrp_config_tls"
                - action: "manual"
                  id: "manual_esrp_config_tls"
                  if_name: ""
                  instead: ""
                  type: "SIP"
                  method: ""
                  prompt: "Please configure ESRP to send LoST requests to the ECRF-LVF using TLS transport and press any key to continue when ready..."
                  next_action: "send_invite"
                - action: "send"
                  id: "send_invite"
                  if_name: "IF_BCF_ESRP"
                  if_port_name: "IF_BCF_ESRP_SIP_5061_TLSv1.2"  # Optional
                  prep_steps:
                    - method_name: "get_interface_address"
                      kwargs:
                        interface_name: "IF_BCF_ESRP"
                      "save_result_as": "var.IF_BCF_ESRP"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "callid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.callid"
                    - method_name: "generate_identifier"
                      kwargs: {
                        identifier_type: "incidentid",
                        fqdn: "var.IF_BCF_ESRP",
                        set_default: "True"
                      }
                      save_result_as: "var.incidentid"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                        "param_name": "urn:emergency:uid:callid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.callid"
                        "output_file": "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                        "param_name": "urn:emergency:uid:incidentid:123ABCdefg123ABCdefg123ABCdefg12:test.com"
                        "value": "var.incidentid"
                        "output_file": "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/ESRP_016/SIP_INVITE_location_PIDF-LO_Boundary1.xml",
                    kwargs: {},
                    save_response_as: "ESRP_016_SEND_response.log",
                    save_log_as: "ESRP_016_SEND.log"
                  }
                  run_in_background: "False"
            filtering_options: # optional
                - message_type: "stimulus" # stimulus/output/other
                  src_interface: "IF_BCF_ESRP"
                  dst_interface: "IF_ESRP_BCF"
                  sip_method: "INVITE" #  leave empty if not needed
                  http_request_method: "" #  leave empty if not needed
                  response_status_code: "" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
                - message_type: "other" # stimulus/output/other
                  src_interface: "IF_ESRP_ECRF-LVF"
                  dst_interface: "IF_ECRF-LVF_ESRP"
                  sip_method: "" #  leave empty if not needed
                  http_request_method: "POST" #  leave empty if not needed
                  response_status_code: "2xx" #  leave empty if not needed
                  header_contains: ""
                  body_contains: ""
        requirements:
          - name: "RQ_ESRP_050"
            variations: ["all"]
