"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "logan/LOG_002/CTR.pdf"
    "log":
      "level": "DEBUG"
      "output_file": "logan/LOG_002/LOG_002.log"
  "tests":
  - "name": "LOG_002"
    "requirements":
    - "name": "RQ_LOG_028"
      "variations":
      - "all"
    "variations":
    - "name": "Request_with_incorrect_limit_send_string"
      "mode": "pcap"
      "pcap_file": "/Users/Sebastian/Downloads/LOG_002/Request_with_incorrect_limit_send_string_capture_41d7615c-f65e-4282-b007-557268d61122.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "GET"
          "response_code": "4xx"
          "http_url": "/Logging/v1/LogEvents?limit=test"
          "body": ""
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_LOG"
        "dst_interface": "IF_LOG_TS"
        "http_request_method": "GET"
        "response_status_code": "400"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
        "sip_method": ""
        "http_request_method": ""
        "header_contains": ""
        "body_contains": ""
    - "name": "successful_basic_request_to_prove_affirmative_operation"
      "mode": "pcap"
      "pcap_file": "/Users/Sebastian/Downloads/LOG_002/successful_basic_request_to_prove_affirmative_operation_capture_362702c2-8a58-46bd-bc5c-36395afa38dc.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "GET"
          "response_code": "2xx"
          "http_url": "/Logging/v1/LogEvents?limit=1000&start=1&startTime=1776-07-04T00%3A00%3A00&endTime=2276-07-04T00%3A00%3A00"
          "body": ""
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_LOG"
        "dst_interface": "IF_LOG_TS"
        "http_request_method": "GET"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
        "sip_method": ""
        "http_request_method": ""
        "header_contains": ""
        "body_contains": ""

