test_config:
  conformance:
    tests:
      - name: "ESRP_001"
        variations:
          - name: "QueueState update after changing ServiceState"
            description: "Verify QueueState update after changing ServiceState"
            params:
              messages:
                - action: "send"
                  execution_order: 1
                  prep_steps: [ ]
                  type: "SIP"
                  method: "SUBSCRIBE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_ServiceState.xml",
                    kwargs: {},
                    save_response_as: "ESRP_001_ServiceState_response.log",
                    save_log_as: "ESRP_001_ServiceState.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  execution_order: 2
                  prep_steps: [ ]
                  type: "SIP"
                  method: "SUBSCRIBE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_QueueState.xml",
                    kwargs: {},
                    save_response_as: "ESRP_001_QueueState_response.log",
                    save_log_as: "ESRP_001_QueueState.log"
                  }
                  run_in_background: "True"
                - action: "manual"
                  instead: ""
                  prompt: "MANUAL ACTION REQUIRED - please simulate change of ServiceState to 'Down' 
                                    and press any key to continue..."
                  next_action: "send"
        requirements:
          - name: "RQ_ESRP_005"
            variations: ["all"]
          #- name: "RQ_ESRP_006"
          #  variations: ["all"]
          - name: "RQ_ESRP_007"
            variations: ["all"]
          - name: "RQ_ESRP_008"
            variations: ["all"]