ixit_ecrf_lvf:
  name: "ECRF-LVF-1"
  type: "ECRF-LVF"
  vendor: "XYZ Software"
  sw_version: "v0.1.1"
  hw_version: "v0.1"
  mac_address: "dd:70:89:93:de:bd"
  login: "admin"
  password: "admin1"
  configuration_file: "xyz_vendor/ecrf_lvf.conf"
  sw_file: "xyz_vendor/ecrf_lvf_v0.1.1.bin"
  provisioning:
    acceptable_lost_query_sources:
      - domain: "test.example.com"
      - domain: "example.com"
    service_boundaries:
      - name: "Laurel Police Department"
        service_number: 911
        uri:
          - name: "police"
            service_uris:
              - uri: "urn:service:sos.police"
              - uri: "urn:emergency:service:sos.police"
            sip_uri: "sip:laurelpd@example.com"
          - name: "ambulance"
            service_uris:
              - uri: "urn:service:sos.ambulance"
              - uri: "urn:emergency:service:sos.ambulance"
            sip_uri: "sip:laurelambulance@example.com"
        boundary_location:
            type: "Polygon"
            points:
              - [34.15677, 112.13413412]
              - [34.15677, 112.134134111112]
              - [34.15677, 112.13112111112]
              - [34.15677, 113.13413412]
            radius: 0  # For Circle
            semi_major_axis: 0  # Circle, Ellipsoid
            semi_minor_axis: 0  # Circle, Ellipsoid
            orientation: 0  # Circle, Ellipsoid
            vertical_axis: 0  # Ellipsoid
            inner_radius: 0  # Arc-Band
            outer_radius: 0  # Arc-Band
            start_angle: 0  # Arc-Band
            opening_angle: 0  # Arc-Band
            height: 0  # Prism
      - name: "Maryland City Police Department"
        service_number: 911
        uri:
          - name: "police"
            service_uris:
              - uri: "urn:service:sos.police"
              - uri: "urn:emergency:service:sos.police"
            sip_uri: "sip:marylandcitypd@example.com"
        boundary_location:
            type: "Circle"
            points:
              - [34.15677, 122.13413412]
            radius: 500  # For Circle
            semi_major_axis: 0  # Circle, Ellipsoid
            semi_minor_axis: 0  # Circle, Ellipsoid
            orientation: 0  # Circle, Ellipsoid
            vertical_axis: 0  # Ellipsoid
            inner_radius: 0  # Arc-Band
            outer_radius: 0  # Arc-Band
            start_angle: 0  # Arc-Band
            opening_angle: 0  # Arc-Band
            height: 0  # Prism
