test_config:
  global:
    response_timeout: 30
  report_files:
    conformance: "CTR.pdf"
    interoperability: "ITR.pdf"
  log:
    level: "DEBUG"
    output_file: "/logs/testsuite.log"
  scenarios:
    - name: "Basic tests scenario"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/BCF_001/artem.success.pcap"
      tests:
        - name: "BCF_001 - some description"
          test_id: "BCF_001"
          ixit_file_path: ""
          src_interface: "IF_O-BCF-1_ESRP-1"
          dst_interface: "IF_ESRP-1_O-BCF-1"
          sip_method: "INVITE" #  leave empty if not needed
          http_request_method: "" #  leave empty if not needed
          response_status_code: "" #  leave empty if not needed
