test_config:
  test_case_name: "TC_LOG_001"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_LOG_001_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_LOG_001_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/LOG_001/TC_LOG_001_pass.pcap"
      tests:
        - name: "LOG_001 pass"
          test_id: "LOG_001"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/Versions"
            response_status_code: "4xx" #  leave empty if not needed
          output_message:
            src_interface: "IF_LOG_TS"
            dst_interface: "IF_TS_LOG"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
    - name: "TC_LOG_001_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/LOG_001/TC_LOG_001_fail.pcap"
      tests:
        - name: "LOG_001 fail"
          test_id: "LOG_001"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/Versions"
            response_status_code: "4xx" #  leave empty if not needed
          output_message:
            src_interface: "IF_LOG_TS"
            dst_interface: "IF_TS_LOG"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
    - name: "TC_LOG_001_fail2"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/LOG_001/TC_LOG_001_fail2.pcap"
      tests:
        - name: "LOG_001 fail2"
          test_id: "LOG_001"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/Versions"
            response_status_code: "4xx" #  leave empty if not needed
          output_message:
            src_interface: "IF_LOG_TS"
            dst_interface: "IF_TS_LOG"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
    - name: "TC_LOG_001_fail3"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/LOG_001/TC_LOG_001_fail3.pcap"
      tests:
        - name: "LOG_001 fail3"
          test_id: "LOG_001"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/Versions"
            response_status_code: "4xx" #  leave empty if not needed
          output_message:
            src_interface: "IF_LOG_TS"
            dst_interface: "IF_TS_LOG"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
