lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  entities:
    - name: "Test System"
      type: "TEST_ENTITY"
      function: "BCF"
      mode: ["SENDER", "RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS_CHE"
          fqdn: ""
          ip: "192.168.64.11"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
    - name: "CHE"
      type: "IUT"
      function: "CHE"
      mode: ""
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_CHE_TS"
          fqdn: ""
          ip: "192.168.64.19"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
        - name: "IF_CHE_TS2"
          fqdn: ""
          ip: "192.168.64.19"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
    - name: "Test System 2"
      type: "TEST_ENTITY"
      function: "BCF"
      mode: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS2_CHE"
          fqdn: ""
          ip: "192.168.64.21"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060