"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    - "type": "docx"
      "path": "CTR.docx"
    - "type": "xml"
      "path": "CTR.xml"
    - "type": "csv"
      "path": "CTR.csv"
    - "type": "json"
      "path": "CTR.json"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "ECRF_LVF_004"
    "requirements":
    - "name": "RQ_ECRF-LVF_051"
      "variations":
      - "listServices_urn-service-sos"
      - "listServicesByLocation_urn-service-sos"
    - "name": "RQ_ECRF-LVF_052"
      "variations":
      - "all"
    - "name": "RQ_ECRF-LVF_054"
      "variations":
      - "all"
    "variations":
    - "name": "listServices_urn-service-sos"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "# to be manually filled in run_config"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/listServices_urn-service-sos"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "listServices_urn-emergency-service-sos"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "# to be manually filled in run_config"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/listServices_urn-emergency-service-sos"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "listServicesByLocation_urn-service-sos"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "# to be manually filled in run_config"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/listServicesByLocation_urn-service-sos"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "listServicesByLocation_urn-emergency-service-sos"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "# to be manually filled in run_config"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/listServicesByLocation_urn-emergency-service-sos"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
