lab_config:
  global:
    response_timeout: 30
    type: "conformance"
    report_files:
      - type: "pdf"
        path: "CTR.pdf"
      - type: "docx"
        path: "CTR.docx"
    log:
      level: "DEBUG"
      output_file: "test_files/logs/logger.log"
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: "192.168.50.228" # 50.228"
  entities:
    - name: "Test System"
      mode: "STUB_SERVER"
      function: "OSP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS_ESRP"
          fqdn: ""  # Optional
          ip: "192.168.50.133" # 50.133"
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: [ ]  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "ESRP"
      mode: "REAL_DEVICE"
      function: "ESRP"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP_TS"
          fqdn: ""  # Optional
          ip: "192.168.50.218" # 50.218"  # Home - 50.218 VT - 68.128
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
