test_config:
  conformance:
    tests:
      - name: "CHE_002"
        variations:
          - name: "CHE_002_variation_1"
            description: "Validate SIP 200 OK response for SIP INVITE with g711alaw audio media"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_SDP_with_g711alaw_audio.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_SDP_with_g711alaw_audio.log"
                  }
          - name: "CHE_002_variation_2"
            description: "Validate SIP 200 OK response for SIP INVITE with g711ulaw audio media"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_SDP_with_g711ulaw_audio.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_SDP_with_g711ulaw_audio.log"
                  }
          - name: "CHE_002_variation_3"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 1b"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_SDP_with_H.264_video_level_1b.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_SDP_with_H.264_video_level_1b.log"
                  }
          - name: "CHE_002_variation_4"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 1.1"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_SDP_with_H.264_video_level_1.1.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_SDP_with_H.264_video_level_1.1.log"
                  }
          - name: "CHE_002_variation_5"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 2.0"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_SDP_with_H.264_video_level_2.0.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_SDP_with_H.264_video_level_2.0.log"
                  }
          - name: "CHE_002_variation_6"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 3.0"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_SDP_with_H.264_video_level_3.0.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_SDP_with_H.264_video_level_3.0.log"
                  }
          - name: "CHE_002_variation_7"
            description: "Validate SIP 200 OK response for SIP INVITE with t140 text media"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_SDP_with_text.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_SDP_with_text.log"
                  }
        requirements:
          - name: "RQ_CHE_006"
            variations: [
              "CHE_002_variation_1",
              "CHE_002_variation_2",
              "CHE_002_variation_3",
              "CHE_002_variation_4",
              "CHE_002_variation_5",
              "CHE_002_variation_6",
              "CHE_002_variation_7"
            ]