test_config:
  test_case_name: "TC_PS_003"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_PS_003_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_PS_003_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_003/TC_PS_003_pass.pcap"
      tests:
        - name: "PS_003 pass"
          test_id: "PS_003"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
    - name: "TC_PS_003_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_003/TC_PS_003_fail.pcap"
      tests:
        - name: "PS_003 fail"
          test_id: "PS_003"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" # If 200 OK then JSON body need to be verified
