"run_config":
  "global":
    "type": "conformance"
    "id_summary":
      "lab":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
        "eng_name": ""
        "accred_status": ""
        "accred_ref": ""
        "accred_auth": ""
      "supplier":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
      "iut":
        "type": ""
        "name": ""
        "version": ""
        "test_period": ""
        "date_of_receipt": ""
        "location": ""
        "cs_id": ""
        "test_env": ""
      "test_env":
        "ixit_id": ""
        "spec_name": ""
        "spec_version": ""
        "ts_version": ""
        "test_period_start": ""
        "test_period_end": ""
        "log_ref": ""
        "log_ret_date": ""
    "comments":
    - "author": ""
      "comment": ""
    "report_files":
      "output_folder_path": ""
      "filename": "test_report"
      "detailed_view": true
      "types":
      - "pdf"
      - "docx"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
    "response_timeout": 30
  "tests":
  - "name": "CHE_001"
    "requirements":
    - "name": "RQ_CHE_011"
      "variations":
      - "all"
    "variations":
    - "name": "HELD_location_dereferencing"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "receive"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/location"
          "body": "file.test_files/HTTP_messages/HTTP_HELD/Location_response"
          "sipp_scenario": {}
          "run_in_background": "True"
        - "action": "send"
          "prep_steps":
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "lab_config['lab_config']['entities']"
              "where_field": "name"
              "where_value": "TSLIS"
              "extract_field": "interfaces"
            "save_result_as": "var.ts_lis_interfaces"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_interfaces"
              "where_field": "name"
              "where_value": "IF_TSLIS_CHE"
              "extract_field": "ip"
            "save_result_as": "var.ts_lis_ip"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_interfaces"
              "where_field": "name"
              "where_value": "IF_TSLIS_CHE"
              "extract_field": "port_mapping"
            "save_result_as": "var.ts_lis_port_mapping"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_port_mapping"
              "where_field": "protocol"
              "where_value": "HTTP"
              "extract_field": "port"
            "save_result_as": "var.ts_lis_http_port"
          - "method_name": "generate_str"
            "kwargs":
              "string_to_modify": "http://{0}:{1}/location"
              "variables": "list.[var.ts_lis_ip, var.ts_lis_http_port]"
            "save_result_as": "var.http_url"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_geolocation_HELD.xml"
              "param_name": "LIS_LOCATION_REFERENCE_URL"
              "value": "var.http_url"
              "output_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_HELD.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/CHE_001/SIP_INVITE_geolocation_HELD.xml"
            "kwargs": {}
            "save_response_as": "CHE_001_var1_SEND_response.log"
            "save_log_as": "CHE_001_var1_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TSSIP_CHE"
        "dst_interface": "IF_CHE_TSSIP"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": "IF_CHE_TSLIS"
        "dst_interface": "IF_TSLIS_CHE"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_presence_event_package_location_dereferencing"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "receive"
          "prep_steps":
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "lab_config['lab_config']['entities']"
              "where_field": "name"
              "where_value": "TSLIS"
              "extract_field": "interfaces"
            "save_result_as": "var.ts_lis_interfaces"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_interfaces"
              "where_field": "name"
              "where_value": "IF_TSLIS_CHE"
              "extract_field": "ip"
            "save_result_as": "var.ts_lis_ip"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_interfaces"
              "where_field": "name"
              "where_value": "IF_TSLIS_CHE"
              "extract_field": "port_mapping"
            "save_result_as": "var.ts_lis_port_mapping"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_port_mapping"
              "where_field": "protocol"
              "where_value": "SIP"
              "extract_field": "port"
            "save_result_as": "var.ts_lis_sip_port"
          - "method_name": "generate_str"
            "kwargs":
              "string_to_modify": "sip:location@{0}:{1}"
              "variables": "list.[var.ts_lis_ip, var.ts_lis_http_port]"
            "save_result_as": "var.sip_uri"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_LIS.xml"
              "param_name": "LOCATION_SIP_URI"
              "value": "var.sip_uri"
              "output_file": "file./tmp/CHE_001/SIP_SUBSCRIBE_LIS.xml"
          "type": "SIP"
          "method": "SUBSCRIBE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/CHE_001/SIP_SUBSCRIBE_LIS.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var2_SEND_response.log"
            "save_log_as": "CHE_002_var2_SEND.log"
          "run_in_background": "True"
        - "action": "send"
          "prep_steps":
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "lab_config['lab_config']['entities']"
              "where_field": "name"
              "where_value": "TSLIS"
              "extract_field": "interfaces"
            "save_result_as": "var.ts_lis_interfaces"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_interfaces"
              "where_field": "name"
              "where_value": "IF_TSLIS_CHE"
              "extract_field": "ip"
            "save_result_as": "var.ts_lis_ip"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_interfaces"
              "where_field": "name"
              "where_value": "IF_TSLIS_CHE"
              "extract_field": "port_mapping"
            "save_result_as": "var.ts_lis_port_mapping"
          - "method_name": "extract_from_config"
            "kwargs":
              "config_part": "var.ts_lis_port_mapping"
              "where_field": "protocol"
              "where_value": "SIP"
              "extract_field": "port"
            "save_result_as": "var.ts_lis_sip_port"
          - "method_name": "generate_str"
            "kwargs":
              "string_to_modify": "sip:location@{0}:{1}"
              "variables": "list.[var.ts_lis_ip, var.ts_lis_http_port]"
            "save_result_as": "var.sip_uri"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_geolocation_SIP.xml"
              "param_name": "LOCATION_SIP_URI"
              "value": "var.sip_uri"
              "output_file": "file./tmp/CHE_001/SIP_INVITE_geolocation_SIP.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/CHE_001/SIP_INVITE_geolocation_SIP.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var2_SEND_response.log"
            "save_log_as": "CHE_002_var2_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TSSIP_CHE"
        "dst_interface": "IF_CHE_TSSIP"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": "IF_CHE_TSLIS"
        "dst_interface": "IF_TSLIS_CHE"
        "sip_method": "SUBSCRIBE"
        "header_contains": ""
        "body_contains": ""
