test_config:
  test_case_name: "TC_PS_008"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_PS_008_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_PS_008_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_008/TC_PS_008_pass.pcap"
      tests:
        - name: "PS_008 variation 1"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_1_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_1_JWS_payload"
        - name: "PS_008 variation 2"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_2_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_2_JWS_payload"
        - name: "PS_008 variation 3"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_3_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_3_JWS_payload"
        - name: "PS_008 variation 4"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_4_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_4_JWS_payload"
    - name: "TC_PS_008_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_008/TC_PS_008_fail.pcap"
      tests:
        - name: "PS_008 variation 1"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_1_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_1_JWS_payload"
        - name: "PS_008 variation 2"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_2_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_2_JWS_payload"
        - name: "PS_008 variation 3"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_3_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_3_JWS_payload"
        - name: "PS_008 variation 4"
          test_id: "PS_008"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_4_JWS_payload"
          output_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            response_status_code: "200" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_008/TC_PS_008_JWS/TC_PS_008_variation_4_JWS_payload"
