lab_config:
  global:
    type: "conformance"
    report_files:
      - type: "docx"
        path: "CTR.docx"
      - type: "pdf"
        path: "CTR.pdf"
    log:
      level: "DEBUG"
      output_file: "test_files/logs/BCF_001_logger.log"
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: "192.168.50.228"
  entities:
    # Test System
    - name: "TS"
      mode: "STUB_SERVER"
      function: "OSP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS_LIS"
          fqdn: ""  # Optional
          ip: "192.168.50.134"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.50.1"  # Optional
          dns: [ ]  # Optional
          port_mapping:
            - protocol: "HTTP"
              port: 80
              transport_protocol: "TCP"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "LIS"
      mode: "REAL_DEVICE"
      function: "LIS"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_LIS_TS"
          fqdn: ""  # Optional
          ip: "192.168.50.218"
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.50.1"  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "HTTP"
              port: 80
              transport_protocol: "TCP"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"