"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "LIS_001"
    "requirements":
    - "name": "RQ_LIS_001"
      "variations":
      - "all"
    - "name": "RQ_LIS_002"
      "variations":
      - "all"
    - "name": "RQ_LIS_007"
      "variations":
      - "all"
    "variations":
    - "name": "Location_URI_dereference_using_HTTP_HELD"
      "description": "Validate location URI dereferencing using HTTP HELD"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/"
          "body": "file.test_files/HTTP_messages/HTTP_HELD/Location_request"
          "content_type": "application/xml"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_LIS"
        "dst_interface": "IF_LIS_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
    - "name": "Location_URI_dereference_using_SIP_Presence_Event_Package"
      "description": "Validate location URI dereferencing using SIP Presence Event Package"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "SUBSCRIBE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_FROM_LIS.xml"
            "kwargs": {}
            "save_response_as": "LIS_001_var2_RECEIVE_response.log"
            "save_log_as": "LIS_001_var2_RECEIVE.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_LIS"
        "dst_interface": "IF_LIS_TS"
        "sip_method": "NOTIFY"
        "header_contains": ""
        "body_contains": ""
