test_config:
  conformance:
    tests:
      - name: "LIS_001"
        variations:
          - name: "Location_URI_dereference_using_HTTP_HELD"
            description: "Validate location URI dereferencing using HTTP HELD"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "# to be manually filled in run_config"
                  body: "file.test_files/HTTP_messages/HTTP_HELD/Location_request"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "Location_URI_dereference_using_SIP_Presence_Event_Package"
            description: "Validate location URI dereferencing using SIP Presence Event Package"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "SUBSCRIBE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_FROM_LIS.xml",
                    kwargs: {},
                    save_response_as: "LIS_001_var2_SEND_response.log",
                    save_log_as: "LIS_001_var2_SEND.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_LIS_001"
            variations: ["all"]
          - name: "RQ_LIS_002"
            variations: ["all"]
          - name: "RQ_LIS_007"
            variations: ["all"]
