test_config:
  test_case_name: "TC_LOG_002"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_LOG_002_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_LOG_002_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/LOG_002/TC_LOG_002_pass.pcap"
      tests:
        - name: "LOG_002 pass variation 1"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?limit=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 pass variation 2"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?start=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 pass variation 3"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?start=0"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 pass variation 4"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?logEventType=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 pass variation 5"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?startTime=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 pass variation 6"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?endTime=test"
            response_status_code: "4xx" #  leave empty if not needed
    - name: "TC_LOG_002_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/LOG_002/TC_LOG_002_fail.pcap"
      tests:
        - name: "LOG_002 fail variation 1"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?limit=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 fail variation 2"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?start=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 fail variation 3"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?start=0"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 fail variation 4"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?logEventType=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 fail variation 5"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?startTime=test"
            response_status_code: "4xx" #  leave empty if not needed
        - name: "LOG_002 fail variation 6"
          test_id: "LOG_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_LOG"
            dst_interface: "IF_LOG_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "GET" #  leave empty if not needed
            header_contains: "/LogEvents?endTime=test"
            response_status_code: "4xx" #  leave empty if not needed
