run_config:
  global:
    response_timeout: 30
    type: "conformance"
    report_files:
      - type: "pdf"
        path: "CHE_005_CTR.pdf"
    log:
      level: "DEBUG"
      output_file: "test_files/logs/CHE_005.log"
  tests:
    - name: "CHE_005"
      requirements:
        - name: "RQ_CHE_032"
          variations: [
            "CHE_005_variation_1",
            "CHE_005_variation_2"
          ]
        - name: "RQ_CHE_033"
          variations: [
            "CHE_005_variation_1",
            "CHE_005_variation_2"
          ]
      variations:
        - name: "CHE_005_variation_1"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "OK" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
        - name: "CHE_005_variation_2"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "OK" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
        - name: "CHE_005_variation_3"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "OK" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
        - name: "CHE_005_variation_4"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "OK" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
        - name: "CHE_005_variation_5"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "OK" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
        - name: "CHE_005_variation_6"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "OK" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed
        - name: "CHE_005_variation_7"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "OK" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "200" #  leave empty if not needed