"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    - "type": "docx"
      "path": "CTR.docx"
    - "type": "xml"
      "path": "CTR.xml"
    - "type": "csv"
      "path": "CTR.csv"
    - "type": "json"
      "path": "CTR.json"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "ESRP_004"
    "requirements":
    - "name": "RQ_ESRP_033"
      "variations":
      - "SIP_INVITE_with_CANCEL.xml"
    - "name": "RQ_ESRP_034"
      "variations":
      - "SIP_OPTIONS.xml"
    "variations":
    - "name": "SIP_OPTIONS.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "OPTIONS"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_OPTIONS/SIP_OPTIONS.xml"
            "kwargs": {}
            "save_response_as": "ESRP_004_var1_SEND_response.log"
            "save_log_as": "ESRP_004_var1_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_U-ESRP_ESRP"
        "dst_interface": "IF_ESRP_U-ESRP"
        "sip_method": "OPTIONS"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": "IF_ESRP_T-BCF"
        "dst_interface": ""
    - "name": "SIP_INVITE_with_CANCEL.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_with_CANCEL.xml"
            "kwargs": {}
            "save_response_as": "ESRP_004_var2_SEND_response.log"
            "save_log_as": "ESRP_004_var2_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_U-ESRP_ESRP"
        "dst_interface": "IF_ESRP_U-ESRP"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": "IF_ESRP_T-BCF"
        "dst_interface": ""
