lab_config:
  global:
    type: "conformance"
    report_files:
      output_folder_path: "logan/CHE_001" # empty if you want to have reports in TS root dir or absolute path to the FOLDER
      filename: "CHE_001" # without format
      detailed_view: true
      types:
        - "docx"
        - "pdf"
    id_summary:
      lab:
        name: "TAMUS CACN ISO LAB"
        accred_status: "Valid"
        accred_ref: "12345"
        accred_auth: "Department of Homeland Security"
        addr_line_1: "1501 Texas Ave S"
        addr_line_2: "ATTN: Logan Freeman"
        city: "College Station"
        state: "Texas"
        country: "US"
        zip: "77840"
        url: "https://cacn.tamus.edu"
        eng_name: "Logan Freeman"
      supplier:
        name: "Foo"
        addr_line_1: "1 Foo Rd"
        addr_line_2: "Suite 1234"
        city: "Bryan"
        state: "Texas"
        country: "US"
        zip: "77801"
        url: "https://www.foo.com"
      iut:
        type: "CHE"
        name: "IUT_CHE"
        version: "0.0.0.1"
        test_period: "20250617"
        date_of_receipt: "20250615"
        location: "n/a"
        cs_id: "00001"
      test_env:
        ixit_id: "00001-ixit"
        spec_name: "i3"
        spec_version: "v3revF"
        ts_version: "0.5"
        test_period_start: "20250616" # ?
        test_period_end: "20250617" # ?
        log_ref: "1234567" # ?
        log_ret_date: "20250617" # ?
    log:
      level: "DEBUG"
      output_file: "logan/CHE_001/CHE_001.log"
    comments:
      - author: "X"
        comment: "This is test comment X."
      - author: "Y"
        comment: "I am the Y comment."
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: "192.168.1.15"
  entities:
    # Test System 1
    - name: "TS-1"
      mode: "STUB_SERVER"
      function: "BCF"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS-1_CHE"
          fqdn: ""  # Optional
          ip: "192.168.1.158"
          mask: "255.255.255.248"
          gateway: ""  # Optional
          dns: [ ]  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "CHE"
      mode: "REAL_DEVICE"
      function: "CHE"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_CHE_TS-1"
          fqdn: ""  # Optional
          ip: "192.168.1.17"
          mask: "255.255.255.248"
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_CHE_TS-2"
          fqdn: ""  # Optional
          ip: "192.168.1.17"
          mask: "255.255.255.248"  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
            - protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"