"run_config":
  "global":
    "type": "conformance"
    "id_summary":
      "lab":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
        "eng_name": ""
        "accred_status": ""
        "accred_ref": ""
        "accred_auth": ""
      "supplier":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
      "iut":
        "type": ""
        "name": ""
        "version": ""
        "test_period": ""
        "date_of_receipt": ""
        "location": ""
        "cs_id": ""
        "test_env": ""
      "test_env":
        "ixit_id": ""
        "spec_name": ""
        "spec_version": ""
        "ts_version": ""
        "test_period_start": ""
        "test_period_end": ""
        "log_ref": ""
        "log_ret_date": ""
    "comments":
    - "author": ""
      "comment": ""
    "report_files":
      "output_folder_path": ""
      "filename": "test_report"
      "detailed_view": false
      "types":
      - "pdf"
      - "docx"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
    "response_timeout": 30
  "tests":
  - "name": "CHE_002"
    "requirements":
    - "name": "RQ_CHE_006"
      "variations":
      - "all"
    "variations":
    - "name": "SIP_INVITE_SDP_with_g711alaw_audio.xml"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var1_SEND_response.log"
            "save_log_as": "CHE_002_var1_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_g711ulaw_audio.xml"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var2_SEND_response.log"
            "save_log_as": "CHE_002_var2_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var3_SEND_response.log"
            "save_log_as": "CHE_002_var3_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var4_SEND_response.log"
            "save_log_as": "CHE_002_var4_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var5_SEND_response.log"
            "save_log_as": "CHE_002_var5_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
            "kwargs": {}
            "save_response_as": "CHE_002_var6_SEND_response.log"
            "save_log_as": "CHE_002_var6_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
