test_config:
  conformance:
    tests:
      - name: "ECRF_LVF_002"
        variations:
          - name: "Point_as_a_location_in_findService_request"
            description: "Validate HTTP 200 OK response on findService request with point geolocation"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "/lost"   # part after f.e. http://IP:PORT
                  body: "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_point"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "Circle_as_a_location_in_findService_request"
            description: "Validate HTTP 200 OK response on findService request with circle geolocation"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "/lost"  # part after f.e. http://IP:PORT
                  body: "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_circle"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "Ellipse_as_a_location_in_findService_request"
            description: "Validate HTTP 200 OK response on findService request with ellipse geolocation"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "/lost"  # part after f.e. http://IP:PORT
                  body: "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_ellipse"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "Arc-band_as_a_location_in_findService_request"
            description: "Validate HTTP 200 OK response on findService request with arc-band geolocation"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "/lost"  # part after f.e. http://IP:PORT
                  body: "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_arc-band"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "Polygon_as_a_location_in_findService_request"
            description: "Validate HTTP 200 OK response on findService request with polygon geolocation"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "/lost"  # part after f.e. http://IP:PORT
                  body: "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_polygon"
                  sipp_scenario: {}
                  run_in_background: "False"
          - name: "Civic_address_as_a_location_in_findService_request"
            description: "Validate HTTP 200 OK response on findService request with civic address"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "/lost"  # part after f.e. http://IP:PORT
                  body: "file.test_files/HTTP_messages/HTTP_LoST/findService_civic_address"
                  sipp_scenario: {}
                  run_in_background: "False"
        requirements:
          - name: "RQ_ECRF-LVF_022"
            variations: ["Civic_address_as_a_location_in_findService_request"]
          - name: "RQ_ECRF-LVF_046"
            variations: [
              "Point_as_a_location_in_findService_request",
              "Circle_as_a_location_in_findService_request",
              "Ellipse_as_a_location_in_findService_request",
              "Arc-band_as_a_location_in_findService_request",
              "Polygon_as_a_location_in_findService_request"
            ]
          - name: "RQ_ECRF-LVF_053"
            variations: ["all"]