run_config:
  global:
    response_timeout: 30
    type: "conformance"
    report_files:
      - type: "pdf"
        path: "CHE_004_CTR.pdf"
    log:
      level: "DEBUG"
      output_file: "test_files/logs/CHE_004.log"
  tests:
    - name: "CHE_004"
      requirements:
        - name: "RQ_CHE_003"
          variations: [
            "CHE_004_variation_1",
            "CHE_004_variation_2"
          ]
        - name: "RQ_CHE_004"
          variations: [
            "CHE_004_variation_1"
          ]
        - name: "RQ_CHE_005"
          variations: [
            "CHE_004_variation_1",
            "CHE_004_variation_2"
          ]
      variations:
        - name: "CHE_004_variation_1"
          mode: "pcap" # pcap / online
          pcap_file: "test_files/pcaps/CHE_004/TC_CHE_004_fail.pcap" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            stimulus_message:
              src_interface: "IF_TS_CHE"
              dst_interface: "IF_CHE_TS"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
        - name: "CHE_003_variation_2"
          mode: "pcap" # pcap / online
          pcap_file: "test_files/pcaps/CHE_004/TC_CHE_004_fail.pcap" # optional
          params: # optional - only for online required
            stimulus_message: ""
            headers: ["", ""]
          filtering_options: # optional
            output_message:
              src_interface: "IF_CHE_TS"
              dst_interface: "IF_TS_CHE"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed