test_config: "test_files/configs/BRIDGE/BRIDGE_002/test_config.yaml"
lab_config: "test_files/configs/BRIDGE/BRIDGE_002/lab_config.yaml"
run_config: "test_files/configs/BRIDGE/BRIDGE_002/run_config.yaml"