lab_config:
  global:
    type: "conformance"
    id_summary:
      lab:
        name: ""
        addr_line_1: ""
        addr_line_2: ""
        city: ""
        state: ""
        country: ""
        zip: ""
        url: ""
        eng_name: ""
        accred_status: ""
        accred_ref: ""
        accred_auth: ""
      supplier:
        name: ""
        addr_line_1: ""
        addr_line_2: ""
        city: ""
        state: ""
        country: ""
        zip: ""
        url: ""
      iut:
        type: ""
        name: ""
        version: ""
        test_period: ""
        date_of_receipt: ""
        location: ""
        cs_id: ""
        test_env: ""
      test_env:
        ixit_id: ""
        spec_name: ""
        spec_version: ""
        ts_version: ""
        test_period_start: ""
        test_period_end: ""
        log_ref: ""
        log_ret_date: ""
    comments:
      - author: ""
        comment: ""
    report_files:
      output_folder_path: ""
      "detailed_view": true
      filename: "test_report"
      types:
        - "pdf"
        - "docx"
    log:
      level: "DEBUG"
      output_file: "test_files/logs/logger.log"
    response_timeout: 30
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    # Test System
    - name: "TS"
      mode: "STUB_SERVER"
      function: "BCF"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS_BRIDGE"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: [ ]  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "BRIDGE"
      mode: "REAL_DEVICE"
      function: "BRIDGE"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_BRIDGE_TS"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"