"run_config":
  "global":
    "type": "conformance"
    "id_summary":
      "lab":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
        "eng_name": ""
        "accred_status": ""
        "accred_ref": ""
        "accred_auth": ""
      "supplier":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
      "iut":
        "type": ""
        "name": ""
        "version": ""
        "test_period": ""
        "date_of_receipt": ""
        "location": ""
        "cs_id": ""
        "test_env": ""
      "test_env":
        "ixit_id": ""
        "spec_name": ""
        "spec_version": ""
        "ts_version": ""
        "test_period_start": ""
        "test_period_end": ""
        "log_ref": ""
        "log_ret_date": ""
    "comments":
    - "author": ""
      "comment": ""
    "report_files":
      "output_folder_path": ""
      "detailed_view": true
      "filename": "test_report"
      "types":
      - "pdf"
      - "docx"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
    "response_timeout": 30
  "tests":
  - "name": "BRIDGE_002"
    "requirements":
    - "name": "RQ_BRIDGE_002"
      "variations":
      - "all"
    "variations":
    - "name": "ServiceState"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_ServiceState.xml"
              "param_name": "[service]"
              "value": "# to be manually filled in run_config"
              "output_file": "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ServiceState.xml"
          "type": "SIP"
          "method": "SUBSCRIBE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ServiceState.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_002_var1_SEND_response.log"
            "save_log_as": "BRIDGE_002_var1_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "SUBSCRIBE"
        "header_contains": ""
        "body_contains": ""
    - "name": "ElementState"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_ElementState.xml"
              "param_name": "[service]"
              "value": "# to be manually filled in run_config"
              "output_file": "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ElementState.xml"
          "type": "SIP"
          "method": "SUBSCRIBE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ElementState.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_002_var2_SEND_response.log"
            "save_log_as": "BRIDGE_002_var2_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "SUBSCRIBE"
        "header_contains": ""
        "body_contains": ""
