test_config:
  conformance:
    tests:
      - name: "BRIDGE_002"
        variations:
          - name: "ServiceState"
            description: "Validate support of ServiceState"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_ServiceState.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ServiceState.xml"
                  type: "SIP"
                  method: "SUBSCRIBE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ServiceState.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_002_var1_SEND_response.log",
                    save_log_as: "BRIDGE_002_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "ElementState"
            description: "Validate support of ElementState"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_ElementState.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ElementState.xml"
                  type: "SIP"
                  method: "SUBSCRIBE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_002/SIP_SUBSCRIBE_ElementState.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_002_var2_SEND_response.log",
                    save_log_as: "BRIDGE_002_var2_SEND.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_BRIDGE_002"
            variations: ["all"]