test_config: "test_files/configs/_dev/BCF_001_Artem/test_config.yaml"
lab_config: "test_files/configs/_dev/BCF_001_Artem/lab_config.yaml"
run_config: "test_files/configs/_dev/BCF_001_Artem/run_config.yaml"