lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: "192.168.50.228" # Home - 50.228 VT - 68.122
  entities:
    - name: "OSP"
      mode: "STUB_SERVER"
      function: "OSP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_OSP_O-BCF-1"
          fqdn: ""
          ip: "192.168.50.133" # Home - 50.133 VT - 68.123
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
              # transport: ["TCP", "UDP"]
    - name: "O-BCF-1"
      mode: "REAL_DEVICE"
      function: "BCF"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_O-BCF-1_OSP"
          fqdn: ""
          ip: "192.168.50.218"  # Home - 50.218 VT - 68.128
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
              # transport: ["mTLSv1.3", "mTLSv1.2", "TCP", "UDP"]
        - name: "IF_O-BCF-1_ESRP-1"
          fqdn: ""
          ip: "192.168.50.218"  # Home - 50.218 VT - 68.128
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "ESRP-1"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP-1_O-BCF-1"
          fqdn: ""  # optional
          ip: "192.168.50.134" # Home - 50.134 VT - 68.124
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.1.1"  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
              # transport: ["TCP", "UDP"]