lab_config:
  global:
    type: "conformance"
    report_files:
      output_folder_path: "" # empty if you want to have reports in TS root dir or absolute path to the FOLDER
      filename: "test_report" # without format
      detailed_view: true
      types:
        - "docx"
        - "pdf"
    id_summary:
      lab:
        name: "Test LAB"
        accred_status: "Accredited"
        accred_ref: "123412"
        accred_auth: "12344"
        addr_line_1: "1"
        addr_line_2: "2"
        city: "Web"
        state: "Internet"
        country: "Earth"
        zip: "001001"
        url: "www"
        eng_name: "Arty"
      supplier:
        name: "Arty"
        addr_line_1: "1"
        addr_line_2: "2"
        city: "Web"
        state: "Internet"
        country: "Earth"
        zip: "001001"
        url: "www"
      iut:
        type: "BCF"
        name: "IUT_BCF"
        version: "0.0.0.1"
        test_period: "Sun 15 Jun"
        date_of_receipt: "15.06.2025"
        location: "Web"
        cs_id: "11111"
      test_env:
        ixit_id: "11111"
        spec_name: "111"
        spec_version: "1111"
        ts_version: "1111"
        test_period_start: "15.06.2025" # ?
        test_period_end: "15.06.2025" # ?
        log_ref: "123412" # ?
        log_ret_date: "1234124" # ?
    log:
      level: "DEBUG"
      output_file: "test_files/logs/BCF_001_logger.log"
    comments:
      - author: "Lab"
        comment: "this is test env"
      - author: "Arty"
        comment: "This is my own test env"
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: "192.168.50.228" # Home - 50.228 VT - 68.122
  entities:
    - name: "OSP"
      mode: "STUB_SERVER"
      function: "OSP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_OSP_O-BCF-1"
          fqdn: ""
          ip: "192.168.50.133" # Home - 50.133 VT - 68.123
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
              # transport: ["TCP", "UDP"]
    - name: "O-BCF-1"
      mode: "REAL_DEVICE"
      function: "BCF"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_O-BCF-1_OSP"
          fqdn: ""
          ip: "192.168.50.218"  # Home - 50.218 VT - 68.128
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
              # transport: ["mTLSv1.3", "mTLSv1.2", "TCP", "UDP"]
        - name: "IF_O-BCF-1_ESRP-1"
          fqdn: ""
          ip: "192.168.50.218"  # Home - 50.218 VT - 68.128
          mask: "255.255.255.0"  # Leave empty if not required
          gateway: "192.168.1.1"  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "ESRP-1"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP-1_O-BCF-1"
          fqdn: ""  # optional
          ip: "192.168.50.134" # Home - 50.134 VT - 68.124
          mask: "255.255.255.0"  # Optional
          gateway: "192.168.1.1"  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
              # transport: ["TCP", "UDP"]