run_config:
  global:
    response_timeout: 30
    type: "conformance"
    report_files:
      - type: "xml"
        path: "CTR.xml"
      - type: "docx"
        path: "CTR.docx"
      - type: "pdf"
        path: "CTR.pdf"
      - type: "csv"
        path: "CTR.csv"
      - type: "json"
        path: "CTR.json"
    log:
      level: "DEBUG"
      output_file: "test_files/logs/BCF_001_logger.log"
  tests:
    - name: "BCF_001"
      requirements:
        - name: "RQ_BCF_001"
          variations: [
            "SIP_INVITE_from_OSP.xml",
            "SIP_INVITE_from_OSP_incorrect_1.xml",
            "SIP_INVITE_from_OSP_incorrect_2.xml",
            "SIP_INVITE_from_OSP_incorrect_3.xml",
            "SIP_MESSAGE_from_OSP.xml",
            "SIP_MESSAGE_from_OSP_incorrect_1.xml",
            "SIP_MESSAGE_from_OSP_incorrect_2.xml",
            "SIP_MESSAGE_from_OSP_incorrect_3.xml",
          ]
        - name: "RQ_BCF_002"
          variations: [
            "all",
          ]
        - name: "RQ_BCF_003"
          variations: [
            "all",
          ]
        - name: "RQ_BCF_005"
          variations: [
            "all",
          ]
        - name: "RQ_BCF_007"
          variations: [
            "all",
          ]
        - name: "RQ_BCF_009"
          variations: [
            "all",
          ]
        - name: "RQ_BCF_010"
          variations: [
            "all",
          ]
      variations:
        - name: "SIP_INVITE_from_OSP.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optional
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var1_RECEIVE_response.log",
                    save_log_as: "BCF_001_var1_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_from_OSP.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var1_SEND_response.log",
                    save_log_as: "BCF_001_var1_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
        - name: "SIP_INVITE_from_OSP_incorrect_1.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optiona
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var2_RECEIVE_response.log",
                    save_log_as: "BCF_001_var2_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_from_OSP_incorrect_1.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var2_SEND_response.log",
                    save_log_as: "BCF_001_var2_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
        - name: "SIP_INVITE_from_OSP_incorrect_2.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optiona
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var3_RECEIVE_response.log",
                    save_log_as: "BCF_001_var3_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_from_OSP_incorrect_2.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var3_SEND_response.log",
                    save_log_as: "BCF_001_var3_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
        - name: "SIP_INVITE_from_OSP_incorrect_3.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optiona
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var4_RECEIVE_response.log",
                    save_log_as: "BCF_001_var4_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_INVITE_from_OSP_incorrect_3.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var4_SEND_response.log",
                    save_log_as: "BCF_001_var4_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "INVITE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
        - name: "SIP_MESSAGE_from_OSP.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optiona
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var5_RECEIVE_response.log",
                    save_log_as: "BCF_001_var5_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_from_OSP.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var5_SEND_response.log",
                    save_log_as: "BCF_001_var5_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
        - name: "SIP_MESSAGE_from_OSP_incorrect_1.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optiona
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var6_RECEIVE_response.log",
                    save_log_as: "BCF_001_var6_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_from_OSP_incorrect_1.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var6_SEND_response.log",
                    save_log_as: "BCF_001_var6_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
        - name: "SIP_MESSAGE_from_OSP_incorrect_2.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optiona
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var7_RECEIVE_response.log",
                    save_log_as: "BCF_001_var7_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_from_OSP_incorrect_2.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var7_SEND_response.log",
                    save_log_as: "BCF_001_var7_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
        - name: "SIP_MESSAGE_from_OSP_incorrect_3.xml"
          mode: "online" # pcap / online
          pcap_file: "" # optiona
          params:
              messages:
                - action: "receive"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var8_RECEIVE_response.log",
                    save_log_as: "BCF_001_var8_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "MESSAGE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "test_files/configs/_dev/BCF_001_Artem/SIP_MESSAGE_from_OSP_incorrect_3.xml",
                    kwargs: {},
                    save_response_as: "BCF_001_var8_SEND_response.log",
                    save_log_as: "BCF_001_var8_SEND.log"
                  }
                  run_in_background: "False"
          filtering_options: # optional
            - message_type: "stimulus" # stimulus/output/other
              src_interface: "IF_OSP_O-BCF-1"
              dst_interface: "IF_O-BCF-1_OSP"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""
            - message_type: "output" # stimulus/output/other
              src_interface: "IF_O-BCF-1_ESRP-1"
              dst_interface: "IF_ESRP-1_O-BCF-1"
              sip_method: "MESSAGE" #  leave empty if not needed
              http_request_method: "" #  leave empty if not needed
              response_status_code: "" #  leave empty if not needed
              header_contains: ""
              body_contains: ""