test_config:
  test_case_name: "TC_PS_006"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_PS_006_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_PS_006_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_006/TC_PS_006_pass.pcap"
      tests:
        - name: "PS_006 variation 1"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=OriginationRoutePolicy&policyQueueName=test@example.com"
        - name: "PS_006 variation 2"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=ng911.example&policyQueueName=test@example.com"
        - name: "PS_006 variation 3"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=ng911.example&policyType=OtherRoutePolicy"
        - name: "PS_006 variation 4"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=ng911.example&policyType=OriginationRoutePolicy"
        - name: "PS_006 variation 5"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=test"
        - name: "PS_006 variation 6"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=test"
        - name: "PS_006 variation 7"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=OriginationRoutePolicy&policyQueueName=test"
        - name: "PS_006 variation 8"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=OtherRoutePolicy&policyId=123"
    - name: "TC_PS_006_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_006/TC_PS_006_fail.pcap"
      tests:
        - name: "PS_006 variation 1"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=OriginationRoutePolicy&policyQueueName=test@example.com"
        - name: "PS_006 variation 2"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=ng911.example&policyQueueName=test@example.com"
        - name: "PS_006 variation 3"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=ng911.example&policyType=OtherRoutePolicy"
        - name: "PS_006 variation 4"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=ng911.example&policyType=OriginationRoutePolicy"
        - name: "PS_006 variation 5"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyOwner=test"
        - name: "PS_006 variation 6"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=test"
        - name: "PS_006 variation 7"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=OriginationRoutePolicy&policyQueueName=test"
        - name: "PS_006 variation 8"
          test_id: "PS_006"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "DELETE" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "?policyType=OtherRoutePolicy&policyId=123"