test_config:
  test_case_name: "TC_PS_002"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_PS_002_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_PS_002_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_002/TC_PS_002_pass.pcap"
      tests:
        - name: "PS_002 variation 1"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_1_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 2"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_2_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 3"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_3_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 4"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_4_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 5"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_5_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 6"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_6_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 7"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_7_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 8"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_8_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 9"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_9_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 10"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_10_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 11"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_11_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 12"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_12_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 13"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_13_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 14"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_14_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
    - name: "TC_PS_002_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_002/TC_PS_002_fail.pcap"
      tests:
        - name: "PS_002 variation 1"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_1_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 2"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_2_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 3"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_3_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 4"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_4_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 5"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_5_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 6"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_6_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 7"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_7_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 8"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_8_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 9"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_9_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 10"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_10_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
        - name: "PS_002 variation 11"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_11_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 12"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_12_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 13"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_13_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
          - name: "PS_002 variation 14"
          test_id: "PS_002"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            body_contains: "pcaps/PS_002/TC_PS_002_JWS/TC_PS_002_variation_14_JWS_payload"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
