lab_config:
  pca_certificate_file: "cert_PCA/PCA.crt" # TODO: Add field support from ConfigService side
  pca_certificate_key: "cert_PCA/PCA.key" # TODO: Add field support from ConfigService side
  entities:
    - name: "Test System"
      type: "OSP"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS_LOG"
          fqdn: ""
          ip: "192.168.64.15"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "HTTP"
              port: 80
    - name: "Logging Service"
      type: "LOG"
      fqdn: ""
      certificate_file: "cert_with_subjectAltName/bcf.ng911.test_self_signed.crt"
      certificate_key: "cert_with_subjectAltName/bcf.ng911.test.key"
      interfaces:
        - name: "IF_LOG_TS"
          fqdn: ""
          ip: "192.168.64.16"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "HTTP"
              port: 8080
