test_config:
  test_case_name: "TC_PS_007"
  global:
    response_timeout: 30
  report_files:
    - type: "xml"
      path: "TC_PS_007_CTR.xml"
  log:
    level: "DEBUG"
    output_file: "test_files/logs/logger.log"
  scenarios:
    - name: "TC_PS_007_pass"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_007/TC_PS_007_pass.pcap"
      tests:
        - name: "PS_007 variation 1"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_1-2_JWS_payload"
        - name: "PS_007 variation 2"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "PUT" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_1-2_JWS_payload"
        - name: "PS_007 variation 3"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_3_JWS_payload"
        - name: "PS_007 variation 4"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_4_JWS_payload"
        - name: "PS_007 variation 5"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_5_JWS_payload"
        - name: "PS_007 variation 6"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_6_JWS_payload"
        - name: "PS_007 variation 7"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_7_JWS_payload"
        - name: "PS_007 variation 8"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_8_JWS_payload"
        - name: "PS_007 variation 9"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_9_JWS_payload"
        - name: "PS_007 variation 10"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_10_JWS_payload"
    - name: "TC_PS_007_fail"
      mode: "pcap"  # pcap/capture
      pcap_file: "pcaps/PS_007/TC_PS_007_fail.pcap"
      tests:
        - name: "PS_007 variation 1"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_1-2_JWS_payload"
        - name: "PS_007 variation 2"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "PUT" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_1-2_JWS_payload"
        - name: "PS_007 variation 3"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_3_JWS_payload"
        - name: "PS_007 variation 4"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_4_JWS_payload"
        - name: "PS_007 variation 5"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_5_JWS_payload"
        - name: "PS_007 variation 6"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_6_JWS_payload"
        - name: "PS_007 variation 7"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_7_JWS_payload"
        - name: "PS_007 variation 8"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_8_JWS_payload"
        - name: "PS_007 variation 9"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_9_JWS_payload"
        - name: "PS_007 variation 10"
          test_id: "PS_007"
          ixit_file_path: ""
          stimulus_message:
            src_interface: "IF_TS_PS"
            dst_interface: "IF_PS_TS"
            sip_method: "" #  leave empty if not needed
            http_request_method: "POST" #  leave empty if not needed
            response_status_code: "4xx" #  leave empty if not needed
            header_contains: "/Policies"
            body_contains: "pcaps/PS_007/TC_PS_007_JWS/TC_PS_007_variation_10_JWS_payload"
