"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    - "type": "docx"
      "path": "CTR.docx"
    - "type": "xml"
      "path": "CTR.xml"
    - "type": "csv"
      "path": "CTR.csv"
    - "type": "json"
      "path": "CTR.json"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "LIS_002"
    "requirements":
    - "name": "RQ_LIS_006"
      "variations":
      - "all"
    "variations":
    - "name": "Getting_locationURI_from_LIS"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/HTTP_messages/HTTP_HELD/Location_request_for_locationURI"
              "param_name": "DEVICE_URI"
              "value": "# tel/sip URI to be manually filled in run_config"
              "output_file": "file./tmp/LIS_002/LIS_002_Location_request_for_locationURI"
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "# to be manually filled in run_config"
          "body": "file./tmp/LIS_002/LIS_002_Location_request_for_locationURI"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_LIS"
        "dst_interface": "IF_LIS_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
