test_config:
  conformance:
    tests:
      - name: "LIS_002"
        variations:
          - name: "Getting_locationURI_from_LIS"
            description: "Validate getting locationURI from LIS"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - method_name: "replace_string_in_file"
                      kwargs:
                        input_file: "file.test_files/HTTP_messages/HTTP_HELD/Location_request_for_locationURI"
                        param_name: "DEVICE_URI"
                        # tel/sip URI to be manually filled in run_config
                        # URI need to be known by LIS
                        value: "# tel/sip URI to be manually filled in run_config"
                        output_file: "file./tmp/LIS_002/LIS_002_Location_request_for_locationURI"
                  type: "HTTP"
                  method: "POST"
                  response_code: "200"
                  http_url: "# to be manually filled in run_config"  # part after f.e. http://IP:PORT
                  body: "file./tmp/LIS_002/LIS_002_Location_request_for_locationURI"
                  sipp_scenario: {}
                  run_in_background: "False"
        requirements:
          - name: "RQ_LIS_006"
            variations: ["all"]