lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    # Test System BCF
    - name: "BCF"
      mode: "STUB_SERVER"
      function: "BCF"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_BCF_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_BCF_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "ESRP"
      mode: "REAL_DEVICE"
      function: "ESRP"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP_BCF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_BCF_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_ESRP_LIS"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_LIS_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
            - name: "IF_ESRP_LIS_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_ESRP_ECRF-LVF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_ECRF-LVF_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_T-BCF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_T-BCF_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    # Test System LIS
    - name: "LIS"
      mode: "STUB_SERVER"
      function: "LIS"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_LIS_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_LIS_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
            - name: "IF_LIS_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    # Test System ECRF-LVF
    - name: "ECRF-LVF"
      mode: "STUB_SERVER"
      function: "ECRF-LVF"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ECRF-LVF_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_ECRF-LVF_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
    # Test System T-BCF
    - name: "T-BCF"
      mode: "STUB_SERVER"
      function: "BCF"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_T-BCF_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_T-BCF_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"