lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    # Test System
    - name: "ESRP"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP_LIS"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]   #  Leave empty if not required
          port_mapping:
#            - name: "IF_ESRP_LIS_SIP_5061_TLSv1.2"
#              protocol: "SIP"
#              port: 5061
#              transport_protocol: "TLSv1.2"
            - name: "IF_ESRP_LIS_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
            - name: "IF_ESRP_LIS_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
    - name: "LIS"
      mode: "REAL_DEVICE"
      function: "LIS"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api: # All values listed to be added manually
        http_url_suffix_held: "" # F.e. for http://IP:PORT/location provide '/location'
        sip_uri_user: ""  # SIP URI user part for SIP Presence Event Package
        device_uri: ""  # LIS_002: SIP URI/tel of target device known by LIS. Used for getting its locationURI
      interfaces:
        - name: "IF_LIS_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
#            - name: "IF_LIS_ESRP_SIP_5061_TLSv1.2"
#              protocol: "SIP"
#              port: 5061
#              transport_protocol: "TLSv1.2"
            - name: "IF_LIS_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
            - name: "IF_LIS_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"

