lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    # Test System BCF
    - name: "BCF"
      mode: "STUB_SERVER"
      function: "BCF"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_BCF_CHE"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_BCF_CHE_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    # Test System BCF-RECEIVER
    - name: "BCF-RECEIVER"
      mode: "STUB_SERVER"
      function: "BCF"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_BCF-RECEIVER_CHE"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_BCF-RECEIVER_CHE_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "CHE"
      mode: "REAL_DEVICE"
      function: "CHE"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api: # All values listed to be added manually
        sender_tel_number: "" # Tel number of sender acceptable by CHE and auto-answered
      interfaces:
        - name: "IF_CHE_BCF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_CHE_BCF_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_CHE_BCF-RECEIVER"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_CHE_BCF-RECEIVER_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_CHE_LIS"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_CHE_LIS_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
            - name: "IF_CHE_LIS_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
    # Test System LIS
    - name: "LIS"
      mode: "STUB_SERVER"
      function: "LIS"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_LIS_CHE"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_LIS_CHE_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
            - name: "IF_LIS_CHE_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"