lab_config:
  pca_certificate_file: ""       # PCA-issued certificate for TLS auth
  pca_certificate_key: ""        # Key matching PCA certificate
  test_suite_host_ip: ""         # Test suite host IP (controller)
  entities:
    # Test System OSP
    - name: "OSP"
      mode: "STUB_SERVER"
      function: "OSP"
      role: ["SENDER"]
      fqdn: ""                   # Fully Qualified Domain Name
      certificate_file: ""       # TLS certificate
      certificate_key: ""        # TLS key
      interfaces:
        - name: "IF_OSP_BCF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_OSP_BCF_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"

    # Test System BCF
    - name: "BCF"
      mode: "STUB_SERVER"
      function: "BCF"
      role: ["OTHER", "SENDER"]
      fqdn: ""                   # Fully Qualified Domain Name
      certificate_file: ""       # TLS certificate
      certificate_key: ""        # TLS key
      interfaces:
        - name: "IF_BCF_OSP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_BCF_OSP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_BCF_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_BCF_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"

    # IUT
    - name: "ESRP"    # ESRP Under Test
      mode: "REAL_DEVICE"
      function: "ESRP"
      role: ["IUT"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP_BCF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_BCF_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_ESRP_LIS"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_LIS_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
            - name: "IF_ESRP_LIS_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_ESRP_ECRF-LVF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_ECRF-LVF_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_CHFE"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_CHFE_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_ESRP_SAL"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_SAL_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_DR"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_DR_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_PS"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_PS_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_ADR"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_ADR_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_ADR-2"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_ADR-2_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_ADR-3"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_ADR-3_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_LOG"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_LOG_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ESRP_ESRP-2"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]                # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_ESRP-2_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"

    # Test System LIS
    - name: "LIS"
      mode: "STUB_SERVER"
      function: "LIS"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api_http_url_prefix: ""  # Optional
      interfaces:
        - name: "IF_LIS_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_LIS_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
            - name: "IF_LIS_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"

    # Test System ECRF-LVF
    - name: "ECRF-LVF"
      mode: "STUB_SERVER"
      function: "ECRF-LVF"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api_http_url_prefix: ""  # Optional
      interfaces:
        - name: "IF_ECRF-LVF_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_ECRF-LVF_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"

    # Test System CHFE
    - name: "CHFE"
      mode: "STUB_SERVER"
      function: "CHFE"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_CHFE_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_CHFE_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"

    # Test System SAL
    - name: "SAL"
      mode: "STUB_SERVER"
      function: "ECRF-LVF"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_SAL_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_SAL_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"

    # Test System DR (Discrepancy Report server)
    - name: "DR"
      mode: "STUB_SERVER"
      function: "ECRF-LVF"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_DR_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_DR_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"

    # Test System SAL
    - name: "SAL"
      mode: "STUB_SERVER"
      function: "ECRF-LVF"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_SAL_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_SAL_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"

    # Test System PS (Policy Store)
    - name: "PS"
      mode: "STUB_SERVER"
      function: "PS"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_PS_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_PS_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"

    # Test System ADR (Additional Data Repository)
    - name: "ADR"
      mode: "STUB_SERVER"
      function: "ADR"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api_http_url_prefix: ""  # Optional
      interfaces:
        - name: "IF_ADR_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_ADR_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
              
    # Test System ADR-2 (Additional Data Repository)
    - name: "ADR-2"
      mode: "STUB_SERVER"
      function: "ADR"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api_http_url_prefix: ""  # Optional
      interfaces:
        - name: "IF_ADR-2_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_ADR-2_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
              
    # Test System ADR-3 (Additional Data Repository)
    - name: "ADR-3"
      mode: "STUB_SERVER"
      function: "ADR"
      role: ["RECEIVER"]
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api_http_url_prefix: ""  # Optional
      interfaces:
        - name: "IF_ADR-3_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_ADR-3_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
              
    # Test System LOG
    - name: "LOG"             # Simulated log service
      mode: "STUB_SERVER"     # Acts as a stub server for HTTP requests
      function: "LOG"
      role: ["RECEIVER"]          # Sends HTTP messages
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_LOG_ESRP"   # Interface between LOG and BCF
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""         # Leave empty if not required
          dns: [ ]            # Leave empty if not required
          port_mapping:
            - name: "IF_LOG_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"

    # Test System downstream ESRP (ESRP-2)
    - name: "ESRP-2"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: ["RECEIVER"]
      fqdn: ""                   # Fully Qualified Domain Name
      certificate_file: ""       # TLS certificate
      certificate_key: ""        # TLS key
      interfaces:
        - name: "IF_ESRP-2_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""            # Leave empty if not required
          dns: [ ]               # Leave empty if not required
          port_mapping:
            - name: "IF_ESRP-2_ESRP_SIP_5060_TCP"
              protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"