lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    # Test System
    - name: "ESRP"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP_ECRF-LVF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - name: "IF_ESRP_ECRF-LVF_HTTP_4443_TLSv1.2"
              protocol: "HTTP"
              port: 4443
              transport_protocol: "TLSv1.2"
            - name: "IF_ESRP_ECRF-LVF_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
    - name: "ECRF-LVF"
      mode: "REAL_DEVICE"
      function: "ECRF-LVF"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      api:
        http_url_suffix_lost: ""  # F.e. for http://IP:PORT/lost provide '/lost'
      interfaces:
        - name: "IF_ECRF-LVF_ESRP"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
#            - name: "IF_ECRF-LVF_ESRP_HTTP_4443_TLSv1.2"
#              protocol: "HTTP"
#              port: 4443
#              transport_protocol: "TLSv1.2"
            - name: "IF_ECRF-LVF_ESRP_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_ECRF-LVF_TS-ECRF-LVF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []   #  Leave empty if not required
          port_mapping:
            - name: "IF_ECRF-LVF_TS-ECRF-LVF_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
    - name: "TS-ECRF-LVF"
      mode: "STUB_SERVER"
      function: "ECRF-LVF"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS-ECRF-LVF_ECRF-LVF"
          fqdn: ""
          ip: ""
          mask: ""
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - name: "IF_TS-ECRF-LVF_ECRF-LVF_HTTP_8080_TCP"
              protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"