ixit_o-bcf-1:
  name: "O-BCF-1"
  type: "BCF"
  vendor: "XYZ Software"
  sw_version: "v0.1.1"
  hw_version: "v0.1"
  mac_address: "c2:1c:d8:db:3b:a9"
  login: "admin"
  password: "admin1"
  configuration_file: "xyz_vendor/o-bcf-1.conf"
  sw_file: "xyz_vendor/bcf_v0.1.1.bin"
