ixit_esrp-1:
  name: "ESRP-1"
  type: "ESRP"
  vendor: "XYZ Software"
  sw_version: "v0.1.1"
  hw_version: "v0.1"
  mac_address: "66:27:03:b5:df:a1"
  login: "admin"
  password: "admin1"
  configuration_file: "xyz_vendor/esrp1.conf"
  sw_file: "xyz_vendor/esrp_v0.1.1.bin"
