lab_config:
  entities:
    - name: "OSP"
      type: "OSP"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_OSP_O-BCF-1"
          fqdn: ""
          ip: "10.108.0.4"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5061
    - name: "O-BCF-1"
      type: "BCF"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_O-BCF-1_OSP"
          fqdn: ""
          ip: "10.108.0.3"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
        - name: "IF_O-BCF-1_ESRP_1"
          fqdn: ""
          ip: "10.108.0.3"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5060
    - name: "ESRP-1"
      type: "ESRP"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP-1_O-BCF-1"
          fqdn: ""  # optional
          ip: "10.108.0.4"
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060