test_config:
  conformance:
    tests:
      - name: "CHE_002"
        variations:
          - name: "SIP_INVITE_SDP_with_g711alaw_audio.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with g711alaw audio media"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var1_SEND_response.log",
                    save_log_as: "CHE_002_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_g711ulaw_audio.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with g711ulaw audio media"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711ulaw_audio.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var2_SEND_response.log",
                    save_log_as: "CHE_002_var2_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 1b"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1b.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var3_SEND_response.log",
                    save_log_as: "CHE_002_var3_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 1.1"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var4_SEND_response.log",
                    save_log_as: "CHE_002_var4_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 2.0"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var5_SEND_response.log",
                    save_log_as: "CHE_002_var5_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 3.0"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml",
                    kwargs: {},
                    save_response_as: "CHE_002_var6_SEND_response.log",
                    save_log_as: "CHE_002_var6_SEND.log"
                  }
                  run_in_background: "False"

# Test disabled - text media is not supported in currently used SIPp version

#          - name: "SIP_INVITE_SDP_with_text.xml"
#            description: "Validate SIP 200 OK response for SIP INVITE with t140 text media"
#            params:
#              messages:
#                - action: "send"
#                  prep_steps: []
#                  type: "SIP"
#                  method: "INVITE"
#                  response_code: "200"
#                  http_url: ""
#                  body: ""
#                  sipp_scenario: {
#                    scenario_file_path: "test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_text.xml",
#                    kwargs: {},
#                    save_response_as: "CHE_002_var7_SEND_response.log",
#                    save_log_as: "CHE_002_var7_SEND.log"
#                  }
#                  run_in_background: "False"
        requirements:
          - name: "RQ_CHE_006"
            variations: ["all"]