test_config:
  conformance:
    tests:
      - name: "BCF_003"
        variations:
          - name: "TCP"
            description: "Validate if O-BCF sends packets via TLS when received by TCP"
            params:
              messages:
                - action: "receive"
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "ESRP",
                             extract_field: 'certificate_file'
                      }
                      save_result_as: "var.esrp_cert"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "ESRP",
                             extract_field: 'certificate_key'
                      }
                      save_result_as: "var.esrp_key"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: "var.esrp_cert"
                  certificate_key: "var.esrp_key"
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                              t: "l1"
                    },
                    save_response_as: "BCF_001_var1_RECEIVE_response.log",
                    save_log_as: "BCF_001_var1_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: ""
                  certificate_key: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                    kwargs: {
                              t: "t1"
                    },
                    save_response_as: "BCF_003_var1_SEND_response.log",
                    save_log_as: "BCF_003_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "UDP"
            description: "Validate if O-BCF sends packets via TLS when received by UDP"
            params:
              messages:
                - action: "receive"
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                        config_part: "lab_config['lab_config']['entities']",
                        where_field: "name",
                        where_value: "ESRP",
                        extract_field: 'certificate_file'
                      }
                      save_result_as: "var.esrp_cert"
                    - method_name: "extract_from_config"
                      kwargs: {
                        config_part: "lab_config['lab_config']['entities']",
                        where_field: "name",
                        where_value: "ESRP",
                        extract_field: 'certificate_key'
                      }
                      save_result_as: "var.esrp_key"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: "var.esrp_cert"
                  certificate_key: "var.esrp_key"
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                      t: "l1"
                    },
                    save_response_as: "BCF_003_var2_RECEIVE_response.log",
                    save_log_as: "BCF_003_var2_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: [ ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: ""
                  certificate_key: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                    kwargs: {
                      t: "u1"
                    },
                    save_response_as: "BCF_003_var2_SEND_response.log",
                    save_log_as: "BCF_003_var2_SEND.log"
                  }
                  run_in_background: "False"
          - name: "TLS"
            description: "Validate if O-BCF sends packets via TLS when received by TLS"
            params:
              messages:
                - action: "receive"
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "ESRP",
                             extract_field: 'certificate_file'
                      }
                      save_result_as: "var.esrp_cert"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "ESRP",
                             extract_field: 'certificate_key'
                      }
                      save_result_as: "var.esrp_key"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: "var.esrp_cert"
                  certificate_key: "var.esrp_key"
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                              t: "l1"
                    },
                    save_response_as: "BCF_003_var3_RECEIVE_response.log",
                    save_log_as: "BCF_003_var3_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "OSP",
                             extract_field: 'certificate_file'
                      }
                      save_result_as: "var.osp_cert"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "OSP",
                             extract_field: 'certificate_key'
                      }
                      save_result_as: "var.osp_key"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: "var.osp_cert"
                  certificate_key: "var.osp_key"
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_from_OSP.xml",
                    kwargs: {
                              t: "l1"
                    },
                    save_response_as: "BCF_003_var3_SEND_response.log",
                    save_log_as: "BCF_003_var3_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SCTP"
            description: "Validate if O-BCF sends packets via TLS when received by SCTP"
            params:
              messages:
                - action: "receive"
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "ESRP",
                             extract_field: 'certificate_file'
                      }
                      save_result_as: "var.esrp_cert"
                    - method_name: "extract_from_config"
                      kwargs: {
                             config_part: "lab_config['lab_config']['entities']",
                             where_field: "name",
                             where_value: "ESRP",
                             extract_field: 'certificate_key'
                      }
                      save_result_as: "var.esrp_key"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: "var.esrp_cert"
                  certificate_key: "var.esrp_key"
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_RECEIVE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                              t: "l1"
                    },
                    save_response_as: "BCF_003_var4_RECEIVE_response.log",
                    save_log_as: "BCF_003_var4_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps:
                    - method_name: "extract_from_config"
                      kwargs: {
                        config_part: "lab_config['lab_config']['entities']",
                        where_field: "name",
                        where_value: "O-BCF",
                        extract_field: 'ip'
                      }
                      save_result_as: "var.obcf_ip"
                    - method_name: "extract_from_config"
                      kwargs: {
                        config_part: "lab_config['lab_config']['entities']",
                        where_field: "name",
                        where_value: "O-BCF",
                        extract_field: 'port'
                      }
                      save_result_as: "var.obcf_port"
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  certificate_file: ""
                  certificate_key: ""
                  sipp_scenario: {}
                  method_run: {
                    method_name: "send_SIP_INVITE_via_SCTP",
                    kwargs: {
                      remote_ip: "var.obcf_ip",
                      remote_port: "var.obcf_port"
                    },
                    save_result_as: "BCF_003_var4_SEND.log"
                  }
                  run_in_background: "False"
        requirements:
          - name: "RQ_BCF_031"
            variations: ["all"]
          - name: "RQ_BCF_032"
            variations: ["all"]
          - name: "RQ_BCF_033"
            variations: ["all"]
