"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    - "type": "docx"
      "path": "CTR.docx"
    - "type": "xml"
      "path": "CTR.xml"
    - "type": "csv"
      "path": "CTR.csv"
    - "type": "json"
      "path": "CTR.json"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "CHE_005"
    "requirements":
    - "name": "RQ_CHE_033"
      "variations":
      - "all"
    - "name": "RQ_CHE_034"
      "variations":
      - "all"
    "variations":
    - "name": "SIP_INVITE_to_test_interface_with_g711alaw_audio"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml"
            "kwargs": {}
            "save_response_as": "CHE_005_var1_SEND_response.log"
            "save_log_as": "CHE_005_var1_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "SIP_INVITE_to_test_interface_with_g711ulaw_audio"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
            "kwargs": {}
            "save_response_as": "CHE_005_var2_SEND_response.log"
            "save_log_as": "CHE_005_var2_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
    - "name": "SIP_INVITE_to_test_interface_with_h264_video_1b"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_test_SDP_with_H.264_video_level_1b.xml"
            "kwargs": {}
            "save_response_as": "CHE_005_var3_SEND_response.log"
            "save_log_as": "CHE_005_var3_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "SIP_INVITE_to_test_interface_with_h264_video_1.1"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_test_SDP_with_H.264_video_level_1.1.xml"
            "kwargs": {}
            "save_response_as": "CHE_005_var4_SEND_response.log"
            "save_log_as": "CHE_005_var4_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "SIP_INVITE_to_test_interface_with_h264_video_2.0"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_test_SDP_with_H.264_video_level_2.0.xml"
            "kwargs": {}
            "save_response_as": "CHE_005_var5_SEND_response.log"
            "save_log_as": "CHE_005_var5_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "SIP_INVITE_to_test_interface_with_h264_video_3.0"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_suite/test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_test_SDP_with_H.264_video_level_3.0.xml"
            "kwargs": {}
            "save_response_as": "CHE_005_var6_SEND_response.log"
            "save_log_as": "CHE_005_var6_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains":
        "body_contains":
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
