lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    - name: "OSP"
      mode: "STUB_SERVER"
      function: "OSP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_OSP_BCF"
          fqdn: ""
          ip: ""
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5061
              transport_protocol: "TLSv1.2"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "UDP"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "SCTP"
            - protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
    - name: "BCF"
      mode: "REAL_DEVICE"
      function: "BCF"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_BCF_OSP"
          fqdn: ""
          ip: ""
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5061
              transport_protocol: "TLSv1.2"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "UDP"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "SCTP"
            - protocol: "HTTP"
              port: 8080
              transport_protocol: "TCP"
        - name: "IF_BCF_ESRP"
          fqdn: ""
          ip: ""
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "SIP"
              port: 5061
              transport_protocol: "TLSv1.2"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "ESRP"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP_BCF"
          fqdn: ""  # optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5061
              transport_protocol: "TLSv1.2"
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
