test_config:
  conformance:
    tests:
      - name: "CHE_004"
        variations:
          - name: "CHE_004_variation_1"
            description: "Validate SIP INVITE sent by CHE for callbacks"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_EMERGENCY_SINGLE.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_EMERGENCY_SINGLE.log"
                  }
                - action: "receive"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_RECEIVE.log"
                  }
          - name: "CHE_004_variation_2"
            description: "Validate SIP INVITE sent by CHE for outbound calls"
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_RECEIVE.log"
                  }
        requirements:
          - name: "RQ_CHE_003"
            variations: [
              "CHE_004_variation_1",
              "CHE_004_variation_2"
            ]
          - name: "RQ_CHE_004"
            variations: [
              "CHE_004_variation_1"
            ]
          - name: "RQ_CHE_005"
            variations: [
              "CHE_004_variation_1",
              "CHE_004_variation_2"
            ]