launch_config:
  output_folder: "/tmp/pcap_tests/"
  global_config:
    lab_info: "templates/ALL_TESTS/lab_info.yaml"
    type: "conformance"
    log:
      level: "DEBUG"
      output_file: "CHFE_DEBUG.log"
    report_files:
      prefix: "CHFE"
      suffix: "CHFE_ALL_TESTS" # optional
      output_folder_path: "" # empty if you want to have reports in TS root dir or absolute path to the FOLDER
      detailed_view: true
      types:
        - "docx"
        - "pdf"
    id_summary:
      eng_name: "ENTER NAME"
      supplier:
        name: "ENTER SUPPLIER NAME"
        addr_line_1: "ENTER ADDRESS"
        addr_line_2: ""
        city: "ENTER CITY"
        state: "ENTER STATE"
        country: "ENTER COUNTRY"
        zip: "ENTER ZIP CODE"
        url: "ENTER URL"
      test_env:
#        ts_version: "4.0.2"
        ixit_id: "11111"
        test_method: "test_method"
        test_period_start: "ENTER CURRENT DATE" # ?
        test_period_end: "ENTER CURRENT DATE" # ?
        log_ref: "00001" # ?
        log_ret_date: "ENTER CURRENT DATE" # ?
    comments:
      - author: "ENTER AUTHOR NAME"
        comment: "THIS IS A TEST RUN ONLY, RESULTS ARE NOT VALID!"
  tests:
   - iut:
       type: "CHFE"
       name: "IF_CHFE_OSP"
       version: "0.0.0.1"
#       test_period: "ENTER CURRENT DATE"
       date_of_receipt: "ENTER CURRENT DATE"
       location: "ENTER LOCATION"
       cs_id: "CS00001"
     lab_config: "test_suite/pcaps/CHFE_007/lab_config_chfe.yaml"
     requirements: ['RQ_CHFE_312']
