lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    # Test System
    - name: "TS"
      mode: "STUB_SERVER"
      function: "BCF"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS_BRIDGE"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: [ ]  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "BRIDGE"
      mode: "REAL_DEVICE"
      function: "BRIDGE"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_BRIDGE_TS"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"