run_config:
  global:
    response_timeout: 30
    type: conformance
    report_files:
    - type: pdf
      path: CTR.pdf
    - type: docx
      path: CTR.docx
    - type: xml
      path: CTR.xml
    - type: csv
      path: CTR.csv
    - type: json
      path: CTR.json
    log:
      level: DEBUG
      output_file: test_files/logs/logger.log
  tests:
  - name: BRIDGE_001
    requirements:
    - name: RQ_BRIDGE_001
      variations:
      - all
    variations:
    - name: SIP_INVITE_SDP_with_g711alaw_audio.xml
      mode: 'online'
      pcap_file: '# OPTIONAL'
      params:
        messages:
        - action: send
          prep_steps: []
          type: SIP
          method: INVITE
          response_code: ''
          http_url: ''
          body: ''
          sipp_scenario:
            scenario_file_path: file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml
            kwargs: {}
            save_response_as: BRIDGE_001_var1_SEND_response.log
            save_log_as: BRIDGE_001_var1_SEND.log
          run_in_background: 'False'
      filtering_options:
      - message_type: 'stimulus'
        src_interface: 'IF_TS_BRIDGE'
        dst_interface: 'IF_BRIDGE_TS'
        sip_method: 'INVITE'
        http_request_method: ''
        response_status_code: '200'
        header_contains: ''
        body_contains: ''
    - name: SIP_INVITE_SDP_with_g711ulaw_audio.xml
      mode: 'online'
      pcap_file: '# OPTIONAL'
      params:
        messages:
        - action: send
          prep_steps: []
          type: SIP
          method: INVITE
          response_code: ''
          http_url: ''
          body: ''
          sipp_scenario:
            scenario_file_path: file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711ulaw_audio.xml
            kwargs: {}
            save_response_as: BRIDGE_001_var2_SEND_response.log
            save_log_as: BRIDGE_001_var2_SEND.log
          run_in_background: 'False'
      filtering_options:
      - message_type: 'stimulus'
        src_interface: 'IF_TS_BRIDGE'
        dst_interface: 'IF_BRIDGE_TS'
        sip_method: 'INVITE'
        http_request_method: ''
        response_status_code: '200'
        header_contains: ''
        body_contains: ''
    - name: SIP_INVITE_SDP_with_H.264_video_level_1b.xml
      mode: 'online'
      pcap_file: '# OPTIONAL'
      params:
        messages:
        - action: send
          prep_steps: []
          type: SIP
          method: INVITE
          response_code: ''
          http_url: ''
          body: ''
          sipp_scenario:
            scenario_file_path: file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1b.xml
            kwargs: {}
            save_response_as: BRIDGE_001_var3_SEND_response.log
            save_log_as: BRIDGE_001_var3_SEND.log
          run_in_background: 'False'
      filtering_options:
      - message_type: 'stimulus'
        src_interface: 'IF_TS_BRIDGE'
        dst_interface: 'IF_BRIDGE_TS'
        sip_method: 'INVITE'
        http_request_method: ''
        response_status_code: '200'
        header_contains: ''
        body_contains: ''
    - name: SIP_INVITE_SDP_with_H.264_video_level_1.1.xml
      mode: 'online'
      pcap_file: '# OPTIONAL'
      params:
        messages:
        - action: send
          prep_steps: []
          type: SIP
          method: INVITE
          response_code: ''
          http_url: ''
          body: ''
          sipp_scenario:
            scenario_file_path: file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml
            kwargs: {}
            save_response_as: BRIDGE_001_var4_SEND_response.log
            save_log_as: BRIDGE_001_var4_SEND.log
          run_in_background: 'False'
      filtering_options:
      - message_type: 'stimulus'
        src_interface: 'IF_TS_BRIDGE'
        dst_interface: 'IF_BRIDGE_TS'
        sip_method: 'INVITE'
        http_request_method: ''
        response_status_code: '200'
        header_contains: ''
        body_contains: ''
    - name: SIP_INVITE_SDP_with_H.264_video_level_2.0.xml
      mode: 'online'
      pcap_file: '# OPTIONAL'
      params:
        messages:
        - action: send
          prep_steps: []
          type: SIP
          method: INVITE
          response_code: ''
          http_url: ''
          body: ''
          sipp_scenario:
            scenario_file_path: file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml
            kwargs: {}
            save_response_as: BRIDGE_001_var5_SEND_response.log
            save_log_as: BRIDGE_001_var5_SEND.log
          run_in_background: 'False'
      filtering_options:
      - message_type: 'stimulus'
        src_interface: 'IF_TS_BRIDGE'
        dst_interface: 'IF_BRIDGE_TS'
        sip_method: 'INVITE'
        http_request_method: ''
        response_status_code: '200'
        header_contains: ''
        body_contains: ''
    - name: SIP_INVITE_SDP_with_H.264_video_level_3.0.xml
      mode: 'online'
      pcap_file: '# OPTIONAL'
      params:
        messages:
        - action: send
          prep_steps: []
          type: SIP
          method: INVITE
          response_code: ''
          http_url: ''
          body: ''
          sipp_scenario:
            scenario_file_path: file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml
            kwargs: {}
            save_response_as: BRIDGE_001_var6_SEND_response.log
            save_log_as: BRIDGE_001_var6_SEND.log
          run_in_background: 'False'
      filtering_options:
      - message_type: 'stimulus'
        src_interface: 'IF_TS_BRIDGE'
        dst_interface: 'IF_BRIDGE_TS'
        sip_method: 'INVITE'
        http_request_method: ''
        response_status_code: '200'
        header_contains: ''
        body_contains: ''