lab_config:
  entities:
    - name: "Test System"
      type: "OSP"
      fqdn: ""
      certificate_file: "pcaps/PS_005/bcf.ng911.test_PCA.crt"
      certificate_key: "pcaps/PS_005/bcf.ng911.test.key"
      interfaces:
        - name: "IF_TS_PS"
          fqdn: ""
          ip: "192.168.64.15"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "HTTP"
              port: 80
    - name: "Policy Store"
      type: "PS"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_PS_TS"
          fqdn: ""
          ip: "192.168.64.16"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "HTTP"
              port: 8080
