"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    - "type": "docx"
      "path": "CTR.docx"
    - "type": "xml"
      "path": "CTR.xml"
    - "type": "csv"
      "path": "CTR.csv"
    - "type": "json"
      "path": "CTR.json"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "CHE_003"
    "requirements":
    - "name": "RQ_CHE_008"
      "variations":
      - "all"
    - "name": "RQ_CHE_009"
      "variations":
      - "SIP_INVITE_SDP_with_language_tags.xml"
    "variations":
    - "name": "SIP_INVITE_SDP_with_g711alaw_audio.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml"
            "kwargs": {}
            "save_response_as": "CHE_003_var1_SEND_response.log"
            "save_log_as": "CHE_003_var1_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "SIP_INVITE_SDP_with_language_tags.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_language_tags.xml"
            "kwargs": {}
            "save_response_as": "CHE_003_var2_SEND_response.log"
            "save_log_as": "CHE_003_var2_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_CHE"
        "dst_interface": "IF_CHE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
    - "name": "SIP_INVITE for outgoing calls"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "receive"
          "prep_steps": []
          "type": "SIP"
          "method": "INVITE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_RECEIVE.xml"
            "kwargs": {}
            "save_response_as": "CHE_003_var3_RECEIVE_response.log"
            "save_log_as": "CHE_003_var3_RECEIVE.log"
          "run_in_background": "True"
        - "action": "manual"
          "instead": ""
          "type": ""
          "method": ""
          "prompt": "MANUAL ACTION REQUIRED - please trigger outgoing call on CHE\
            \ and press any key to continue..."
          "next_action": ""
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_CHE_TS2"
        "dst_interface": "IF_TS2_CHE"
      - "message_type": "output"
        "src_interface": ""
        "dst_interface": ""
        "sip_method": "INVITE"
        "header_contains":
        "body_contains":
