test_config:
  conformance:
    tests:
      - name: "CHE_003"
        variations:
          - name: "SIP_INVITE_SDP_with_g711alaw_audio.xml"
            description: "Validate SDP answer from CHE on 'SIP INVITE + SDP' without language tags"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml",
                    kwargs: {},
                    save_response_as: "CHE_003_var1_SEND_response.log",
                    save_log_as: "CHE_003_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_with_language_tags.xml"
            description: "Validate SDP answer from CHE on 'SIP INVITE + SDP' with language tags"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_with_language_tags.xml",
                    kwargs: {},
                    save_response_as: "CHE_003_var2_SEND_response.log",
                    save_log_as: "CHE_003_var2_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE for outgoing calls"
            description: "Validate SDP offer from CHE for outgoing calls"
            params:
              messages:
                - action: "receive"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_RECEIVE.xml",
                    kwargs: {},
                    save_response_as: "CHE_003_var3_RECEIVE_response.log",
                    save_log_as: "CHE_003_var3_RECEIVE.log"
                  }
                  run_in_background: "True"
                - action: "manual"
                  instead: ""
                  type: ""
                  method: ""
                  prompt: "MANUAL ACTION REQUIRED - please trigger outgoing call on CHE 
                                    and press any key to continue..."
                  next_action: ""
        requirements:
          - name: "RQ_CHE_008"
            variations: ["all"]
          - name: "RQ_CHE_009"
            variations: ["SIP_INVITE_SDP_with_language_tags.xml"]
