"run_config":
  "global":
    "type": "conformance"
    "id_summary":
      "lab":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
        "eng_name": ""
        "accred_status": ""
        "accred_ref": ""
        "accred_auth": ""
      "supplier":
        "name": ""
        "addr_line_1": ""
        "addr_line_2": ""
        "city": ""
        "state": ""
        "country": ""
        "zip": ""
        "url": ""
      "iut":
        "type": ""
        "name": ""
        "version": ""
        "test_period": ""
        "date_of_receipt": ""
        "location": ""
        "cs_id": ""
        "test_env": ""
      "test_env":
        "ixit_id": ""
        "spec_name": ""
        "spec_version": ""
        "ts_version": ""
        "test_period_start": ""
        "test_period_end": ""
        "log_ref": ""
        "log_ret_date": ""
    "comments":
    - "author": ""
      "comment": ""
    "report_files":
      "output_folder_path": ""
      "filename": "test_report"
      "detailed_view": false
      "types":
      - "pdf"
      - "docx"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
    "response_timeout": 30
  "tests":
  - "name": "ESRP_001"
    "requirements":
    - "name": "RQ_ESRP_005"
      "variations":
      - "all"
    - "name": "RQ_ESRP_006"
      "variations":
      - "all"
    - "name": "RQ_ESRP_007"
      "variations":
      - "all"
    - "name": "RQ_ESRP_008"
      "variations":
      - "all"
    "variations":
    - "name": "QueueState update after changing ServiceState"
      "mode": "# pcap/online to be manually filled"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "id": "send_subscribe_servicestate"
          "next_action": "send_subscribe_queuestate"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_ServiceState.xml"
              "param_name": "[service]"
              "value": "ESRP"
              "output_file": "file./tmp/ESRP_001/SIP_SUBSCRIBE_ServiceState.xml"
          "type": "SIP"
          "method": "SUBSCRIBE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/ESRP_001/SIP_SUBSCRIBE_ServiceState.xml"
            "kwargs": {}
            "save_response_as": "ESRP_001_ServiceState_response.log"
            "save_log_as": "ESRP_001_ServiceState.log"
          "run_in_background": "True"
        - "action": "send"
          "id": "send_subscribe_queuestate"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_SUBSCRIBE/SIP_SUBSCRIBE_QueueState.xml"
              "param_name": "[service]"
              "value": "# Queue URI to be manually filled in run_config"
              "output_file": "file./tmp/ESRP_001/SIP_SUBSCRIBE_QueueState.xml"
          "type": "SIP"
          "method": "SUBSCRIBE"
          "response_code": ""
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/ESRP_001/SIP_SUBSCRIBE_QueueState.xml"
            "kwargs": {}
            "save_response_as": "ESRP_001_QueueState_response.log"
            "save_log_as": "ESRP_001_QueueState.log"
          "run_in_background": "True"
        - "action": "manual"
          "instead": ""
          "type": ""
          "method": ""
          "prompt": "MANUAL ACTION REQUIRED - please simulate change of ServiceState\
            \ to 'Down' and press any key to continue..."
          "next_action": "send_subscribe_servicestate"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ESRP"
        "dst_interface": "IF_ESRP_TS"
        "sip_method": "SUBSCRIBE"
        "header_contains": ""
        "body_contains": ""