"run_config":
  "global":
    "type": "conformance"
    "id_summary":
      "lab":
        "name": "TAMUS CACN ISO LAB"
        "accred_status": "Valid"
        "accred_ref": "12345"
        "accred_auth": "Department of Homeland Security"
        "addr_line_1": "1501 Texas Ave S"
        "addr_line_2": "ATTN: Logan Freeman"
        "city": "College Station"
        "state": "Texas"
        "country": "US"
        "zip": "77840"
        "url": "https://cacn.tamus.edu"
        "eng_name": "Logan Freeman"
      "supplier":
        "name": "Foo"
        "addr_line_1": "1 Foo Rd"
        "addr_line_2": "Suite 1234"
        "city": "Bryan"
        "state": "Texas"
        "country": "US"
        "zip": "77801"
        "url": "https://www.foo.com"
      "iut":
        "type": "LOG"
        "name": "IUT_LOG"
        "version": "0.0.0.1"
        "test_period": "20250617"
        "date_of_receipt": "20250615"
        "location": "n/a"
        "cs_id": "00001"
      "test_env":
        "ixit_id": "00001-ixit"
        "spec_name": "i3"
        "spec_version": "v3revF"
        "ts_version": "0.5"
        "test_period_start": "20250616"
        "test_period_end": "20250617"
        "log_ref": "1234567"
        "log_ret_date": "20250617"
    "report_files":
      "output_folder_path": "logan/BRIDGE_001"
      "filename": "BRIDGE_001"
      "detailed_view": true
      "types":
      - "pdf"
      - "docx"
    "log":
      "level": "DEBUG"
      "output_file": "logan/BRIDGE_001/BRIDGE_001.log"
    "comments":
    - "author": "X"
      "comment": "This is test comment X."
    - "author": "Y"
      "comment": "I am the Y comment."
  "tests":
  - "name": "BRIDGE_001"
    "requirements":
    - "name": "RQ_BRIDGE_001"
      "variations":
      - "all"
    "variations":
    - "name": "SIP_INVITE_SDP_with_g711alaw_audio.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml"
              "param_name": "urn:service:sos"
              "value": "sip:[service]@[remote_ip]:[remote_port]"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml"
              "param_name": "[service]"
              "value": "f38ec99a-cdee-4d8e-bedb-d8bf07065e39"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_001_var1_SEND_response.log"
            "save_log_as": "BRIDGE_001_var1_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_g711ulaw_audio.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
              "param_name": "urn:service:sos"
              "value": "sip:[service]@[remote_ip]:[remote_port]"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
              "param_name": "[service]"
              "value": "f38ec99a-cdee-4d8e-bedb-d8bf07065e39"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_001_var2_SEND_response.log"
            "save_log_as": "BRIDGE_001_var2_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
              "param_name": "urn:service:sos"
              "value": "sip:[service]@[remote_ip]:[remote_port]"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
              "param_name": "[service]"
              "value": "f38ec99a-cdee-4d8e-bedb-d8bf07065e39"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_001_var3_SEND_response.log"
            "save_log_as": "BRIDGE_001_var3_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
              "param_name": "urn:service:sos"
              "value": "sip:[service]@[remote_ip]:[remote_port]"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
              "param_name": "[service]"
              "value": "f38ec99a-cdee-4d8e-bedb-d8bf07065e39"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_001_var4_SEND_response.log"
            "save_log_as": "BRIDGE_001_var4_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
              "param_name": "urn:service:sos"
              "value": "sip:[service]@[remote_ip]:[remote_port]"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
              "param_name": "[service]"
              "value": "f38ec99a-cdee-4d8e-bedb-d8bf07065e39"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_001_var5_SEND_response.log"
            "save_log_as": "BRIDGE_001_var5_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
    - "name": "SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
      "mode": "online"
      "pcap_file": "# OPTIONAL"
      "params":
        "messages":
        - "action": "send"
          "prep_steps":
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
              "param_name": "urn:service:sos"
              "value": "sip:[service]@[remote_ip]:[remote_port]"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
          - "method_name": "replace_string_in_file"
            "kwargs":
              "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
              "param_name": "[service]"
              "value": "f38ec99a-cdee-4d8e-bedb-d8bf07065e39"
              "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
          "type": "SIP"
          "method": "INVITE"
          "response_code": "200"
          "http_url": ""
          "body": ""
          "sipp_scenario":
            "scenario_file_path": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
            "kwargs": {}
            "save_response_as": "BRIDGE_001_var6_SEND_response.log"
            "save_log_as": "BRIDGE_001_var6_SEND.log"
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_BRIDGE"
        "dst_interface": "IF_BRIDGE_TS"
        "sip_method": "INVITE"
        "header_contains": ""
        "body_contains": ""
