test_config:
  conformance:
    tests:
      - name: "BRIDGE_001"
        variations:
          - name: "SIP_INVITE_SDP_with_g711alaw_audio.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with g711alaw audio media"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711alaw_audio.xml"
                        "param_name": "urn:service:sos"
                        "value": "sip:[service]@[remote_ip]:[remote_port]"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711alaw_audio.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_001_var1_SEND_response.log",
                    save_log_as: "BRIDGE_001_var1_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_g711ulaw_audio.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with g711ulaw audio media"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
                        "param_name": "urn:service:sos"
                        "value": "sip:[service]@[remote_ip]:[remote_port]"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_g711ulaw_audio.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_001_var2_SEND_response.log",
                    save_log_as: "BRIDGE_001_var2_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 1b"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
                        "param_name": "urn:service:sos"
                        "value": "sip:[service]@[remote_ip]:[remote_port]"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1b.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_001_var3_SEND_response.log",
                    save_log_as: "BRIDGE_001_var3_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 1.1"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
                        "param_name": "urn:service:sos"
                        "value": "sip:[service]@[remote_ip]:[remote_port]"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_1.1.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_001_var4_SEND_response.log",
                    save_log_as: "BRIDGE_001_var4_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 2.0"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
                        "param_name": "urn:service:sos"
                        "value": "sip:[service]@[remote_ip]:[remote_port]"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_2.0.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_001_var5_SEND_response.log",
                    save_log_as: "BRIDGE_001_var5_SEND.log"
                  }
                  run_in_background: "False"
          - name: "SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
            description: "Validate SIP 200 OK response for SIP INVITE with H.264 video media with baseline profile level 3.0"
            params:
              messages:
                - action: "send"
                  prep_steps:
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file.test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
                        "param_name": "urn:service:sos"
                        "value": "sip:[service]@[remote_ip]:[remote_port]"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
                    - "method_name": "replace_string_in_file"
                      "kwargs":
                        "input_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
                        "param_name": "[service]"
                        "value": "# to be manually filled in run_config"
                        "output_file": "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml"
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""  # part after f.e. http://IP:PORT
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "file./tmp/BRIDGE_001/SIP_INVITE_SDP_with_H.264_video_level_3.0.xml",
                    kwargs: {},
                    save_response_as: "BRIDGE_001_var6_SEND_response.log",
                    save_log_as: "BRIDGE_001_var6_SEND.log"
                  }
                  run_in_background: "False"

# Test disabled - text media is not supported in currently used SIPp version

#          - name: "SIP_INVITE_SDP_with_text.xml"
#            description: "Validate SIP 200 OK response for SIP INVITE with t140 text media"
#            params:
#              messages:
#                - action: "send"
#                  prep_steps: []
#                  type: "SIP"
#                  method: "INVITE"
#                  response_code: "200"
#                  http_url: ""  # part after f.e. http://IP:PORT
#                  body: ""
#                  sipp_scenario: {
#                    scenario_file_path: "test_files/SIPp_scenarios/SIP_INVITE/SIP_INVITE_SDP_with_text.xml",
#                    kwargs: {},
#                    save_response_as: "BRIDGE_001_var7_SEND_response.log",
#                    save_log_as: "BRIDGE_001_var7_SEND.log"
#                  }
#                  run_in_background: "False"
        requirements:
          - name: "RQ_BRIDGE_001"
            variations: ["all"]