test_config:
  conformance:
    tests:
      - name: "CHE_005"
        variations:
          - name: "CHE_005_variation_1"
            description: "Validate CHE response for SIP INVITE with 'urn:service:test.sos' with g711alaw audio media type in SDP offer"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_test_SDP_with g711alaw_audio.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_test_SDP_with g711alaw_audio.log"
                  }
          - name: "CHE_005_variation_2"
            description: "Validate CHE response for SIP INVITE with 'urn:service:test.sos' with g711ulaw audio media type in SDP offer"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_test_SDP_with g711ulaw_audio.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_test_SDP_with g711ulaw_audio.log"
                  }
          - name: "CHE_005_variation_3"
            description: "Validate CHE response for SIP INVITE with 'urn:service:test.sos' with H.264 video media with baseline profile level 1b in SDP offer"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_test_SDP_with_H.264_video_level_1b.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_test_SDP_with_H.264_video_level_1b.log"
                  }
          - name: "CHE_005_variation_4"
            description: "Validate CHE response for SIP INVITE with 'urn:service:test.sos' with H.264 video media with baseline profile level 1.1 in SDP offer"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_test_SDP_with_H.264_video_level_1.1.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_test_SDP_with_H.264_video_level_1.1.log"
                  }
          - name: "CHE_005_variation_5"
            description: "Validate CHE response for SIP INVITE with 'urn:service:test.sos' with H.264 video media with baseline profile level 2.0 in SDP offer"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_test_SDP_with_H.264_video_level_2.0.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_test_SDP_with_H.264_video_level_2.0.log"
                  }
          - name: "CHE_005_variation_6"
            description: "Validate CHE response for SIP INVITE with 'urn:service:test.sos' with H.264 video media with baseline profile level 3.0 in SDP offer"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_test_SDP_with_H.264_video_level_3.0.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_test_SDP_with_H.264_video_level_3.0.log"
                  }
          - name: "CHE_005_variation_7"
            description: "Validate CHE response for SIP INVITE with 'urn:service:test.sos' with text media in SDP offer"
            params:
              messages:
                - action: "send"
                  prep_steps: []
                  type: "SIP"
                  method: "INVITE"
                  response_code: "200"
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_test_SDP_with_text.xml",
                    kwargs: {},
                    save_response_as: "",
                    save_log_as: "SIP_INVITE_test_SDP_with_text.log"
                  }
        requirements:
          - name: "RQ_CHE_032"
            variations: [
              "CHE_005_variation_1",
              "CHE_005_variation_2"
            ]
          - name: "RQ_CHE_033"
            variations: [
              "CHE_005_variation_1",
              "CHE_005_variation_2"
            ]