lab_config:
  entities:
    - name: "Test System"
      type: "OSP"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_TS_LOG"
          fqdn: ""
          ip: "192.168.64.15"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: [ ]  #  Leave empty if not required
          port_mapping:
            - protocol: "HTTP"
              port: 80
    - name: "Logging Service"
      type: "LOG"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_LOG_TS"
          fqdn: ""
          ip: "192.168.64.16"
          mask: ""  # Leave empty if not required
          gateway: ""  #  Leave empty if not required
          dns: []  #  Leave empty if not required
          port_mapping:
            - protocol: "HTTP"
              port: 8080
