test_config:
  conformance:
    tests:
      - name: "Test of BCF element"
        variations:
          - name: "BCF pass"
            description: "Test variation which would be played from pcap with success result"
            params:
              messages:
                - action: "send"
                  prep_steps: [
                    {
                      method_name: "function_name",
                      kwargs: {
                        name1: "NAME_OF_THE_VAR_1"
                      },
                      save_result_as: [
                        "NAME_OF_THE_VAR_2",
                        "NAME_OF_THE_VAR_3"
                      ]
                    },
                  ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                      name2: "NAME_OF_THE_VAR_2",
                      name3: "NAME_OF_THE_VAR_3"
                    },
                    save_response_as: "NAME_OF_THE_VAR_4",
                    save_log_as: "log_file.log"
                  }
                  run_in_background: "True"
                - action: "send"
                  prep_steps: [
                    {
                      method_name: "function_name",
                      kwargs:{
                               name1: "NAME_OF_THE_VAR_1"
                      },
                      save_result_as: [
                        "NAME_OF_THE_VAR_2",
                        "NAME_OF_THE_VAR_3"
                      ]
                    },
                  ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_RECEIVE.xml",
                    kwargs:{
                        name2: "NAME_OF_THE_VAR_2",
                        name3: "NAME_OF_THE_VAR_3"
                    },
                    save_response_as: "NAME_OF_THE_VAR_4",
                    save_log_as: "log_file.log"
                  }
                  run_in_background: "True"
          - name: "BCF fail"
            description: "Test variation which would be played from pcap with success result"
            params:
              messages:
                - action: "send"
                  prep_steps: [
                    {
                      method_name: "function_name",
                      kwargs: {
                        name1: "NAME_OF_THE_VAR_1"
                      },
                      save_result_as: [
                        "NAME_OF_THE_VAR_2",
                        "NAME_OF_THE_VAR_3"
                      ]
                    },
                  ]
                  type: "SIP"
                  method: "INVITE"
                  response_code: ""
                  http_url: ""
                  body: ""
                  sipp_scenario: {
                    scenario_file_path: "SIP_INVITE_RECEIVE.xml",
                    kwargs: {
                      name2: "NAME_OF_THE_VAR_2",
                      name3: "NAME_OF_THE_VAR_3"
                    },
                    save_response_as: "NAME_OF_THE_VAR_4",
                    save_log_as: "log_file.log"
                  }
                  run_in_background: "True"
        requirements:
          - name: "RQ_BCF_001"
            variations: ["BCF pass", "BCF fail"]
          - name: "RQ_BCF_002"
            variations: ["BCF pass", "BCF fail"]
          - name: "RQ_BCF_003"
            variations: ["BCF pass", "BCF fail"]
          - name: "RQ_BCF_005"
            variations: ["BCF pass", "BCF fail"]
          - name: "RQ_BCF_007"
            variations: ["BCF pass", "BCF fail"]
          - name: "RQ_BCF_009"
            variations: ["BCF pass", "BCF fail"]
          - name: "RQ_BCF_010"
            variations: ["BCF pass", "BCF fail"]


