"run_config":
  "global":
    "response_timeout": 30
    "type": "conformance"
    "report_files":
    - "type": "pdf"
      "path": "CTR.pdf"
    - "type": "docx"
      "path": "CTR.docx"
    - "type": "xml"
      "path": "CTR.xml"
    - "type": "csv"
      "path": "CTR.csv"
    - "type": "json"
      "path": "CTR.json"
    "log":
      "level": "DEBUG"
      "output_file": "test_files/logs/logger.log"
  "tests":
  - "name": "ECRF_LVF_002"
    "requirements":
    - "name": "RQ_ECRF-LVF_022"
      "variations":
      - "Civic_address_as_a_location_in_findService_request"
    - "name": "RQ_ECRF-LVF_046"
      "variations":
      - "Point_as_a_location_in_findService_request"
      - "Circle_as_a_location_in_findService_request"
      - "Ellipse_as_a_location_in_findService_request"
      - "Arc-band_as_a_location_in_findService_request"
      - "Polygon_as_a_location_in_findService_request"
    - "name": "RQ_ECRF-LVF_053"
      "variations":
      - "all"
    "variations":
    - "name": "Point_as_a_location_in_findService_request"
      "mode": "pcap"
      "pcap_file": "pcaps/ECRF_LVF_002/TC_ECRF_LVF_002_pass.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/lost"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_point"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
    - "name": "Circle_as_a_location_in_findService_request"
      "mode": "pcap"
      "pcap_file": "pcaps/ECRF_LVF_002/TC_ECRF_LVF_002_pass.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/lost"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_circle"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
    - "name": "Ellipse_as_a_location_in_findService_request"
      "mode": "pcap"
      "pcap_file": "pcaps/ECRF_LVF_002/TC_ECRF_LVF_002_pass.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/lost"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_ellipse"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
    - "name": "Arc-band_as_a_location_in_findService_request"
      "mode": "pcap"
      "pcap_file": "pcaps/ECRF_LVF_002/TC_ECRF_LVF_002_pass.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/lost"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_arc-band"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
    - "name": "Polygon_as_a_location_in_findService_request"
      "mode": "pcap"
      "pcap_file": "pcaps/ECRF_LVF_002/TC_ECRF_LVF_002_pass.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/lost"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/findService_geodetic_polygon"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
    - "name": "Civic_address_as_a_location_in_findService_request"
      "mode": "pcap"
      "pcap_file": "pcaps/ECRF_LVF_002/TC_ECRF_LVF_002_pass.pcap"
      "params":
        "messages":
        - "action": "send"
          "prep_steps": []
          "type": "HTTP"
          "method": "POST"
          "response_code": "200"
          "http_url": "/lost"
          "body": "file.test_files/HTTP_messages/HTTP_LoST/findService_civic_address"
          "sipp_scenario": {}
          "run_in_background": "False"
      "filtering_options":
      - "message_type": "stimulus"
        "src_interface": "IF_TS_ECRF-LVF"
        "dst_interface": "IF_ECRF-LVF_TS"
        "http_request_method": "POST"
        "response_status_code": "200"
        "header_contains": ""
        "body_contains": ""
