name: Convert MD to PDF

on:
  workflow_dispatch:
    inputs:
      md_files:
        description: 'Markdown file to convert'
        required: true
        default: 'BCF/TD/TD_BCF_001.md BCF/TD/TD_BCF_002.md' 

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Pandoc and WeasyPrint
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc python3-pip
        pip3 install weasyprint

    - name: Create output directory
      run: mkdir -p output

    - name: Convert Markdown to PDF and DOCX
      run: |
        for md_file in ${{ github.event.inputs.md_files }}; do
          base=$(basename "$md_file" .md)
          html_file="output/$base.html"
          pdf_file="output/$base.pdf"
          docx_file="output/$base.docx"
          pandoc "$md_file" -o "$html_file"
          weasyprint "$html_file" "$pdf_file"
          pandoc "$md_file" -o "$docx_file"
        done

    - name: Upload PDF files
      uses: actions/upload-artifact@v4
      with:
        name: converted-pdfs
        path: output/*.pdf

    - name: Upload DOCX files
      uses: actions/upload-artifact@v4
      with:
        name: converted-docx
        path: output/*.docx
