name: Security Pipeline

on:
  workflow_dispatch:
  pull_request:

jobs:

  hygiene:
    uses: ./.github/workflows/dependency_hygiene_check.yml

  security_scanning:
    needs: hygiene
    uses: ./.github/workflows/dependency_security.yml

#  sbom_generation:
#    needs: security_scanning
#    uses: ./.github/workflows/sbom.yml
