lab_config:
  pca_certificate_file: ""
  pca_certificate_key: ""
  test_suite_host_ip: ""
  entities:
    # Test System OSP
    - name: "OSP"
      mode: "STUB_SERVER"
      function: "OSP"
      role: "SENDER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_OSP_O-BCF"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: [ ]  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    - name: "O-BCF"
      mode: "REAL_DEVICE"
      function: "BCF"
      role: "IUT"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_O-BCF_OSP"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
        - name: "IF_O-BCF_ESRP"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"
    # Test System ESRP
    - name: "ESRP"
      mode: "STUB_SERVER"
      function: "ESRP"
      role: "RECEIVER"
      fqdn: ""
      certificate_file: ""
      certificate_key: ""
      interfaces:
        - name: "IF_ESRP_O-BCF"
          fqdn: ""  # Optional
          ip: ""
          mask: ""  # Optional
          gateway: ""  # Optional
          dns: []  # Optional
          port_mapping:
            - protocol: "SIP"
              port: 5060
              transport_protocol: "TCP"